// Copyright (c) 2022 F5, Inc. All rights reserved.
// Code generated by ves-gen-schema-go. DO NOT EDIT.

package securemesh_site_v2

import (
	"bytes"
	"context"
	"fmt"
	io "io"
	"net/http"
	"strings"

	"github.com/gogo/protobuf/proto"
	"github.com/grpc-ecosystem/grpc-gateway/runtime"
	"google.golang.org/grpc"

	"gopkg.volterra.us/stdlib/client"
	"gopkg.volterra.us/stdlib/codec"
	"gopkg.volterra.us/stdlib/errors"
	"gopkg.volterra.us/stdlib/server"
	"gopkg.volterra.us/stdlib/svcfw"
)

var (
	_ = fmt.Sprintf("dummy for fmt import use")
)

// Create ManagedSecureMeshSiteV2CustomAPI GRPC Client satisfying server.CustomClient
type ManagedSecureMeshSiteV2CustomAPIGrpcClient struct {
	conn       *grpc.ClientConn
	grpcClient ManagedSecureMeshSiteV2CustomAPIClient
	// map of rpc name to its invocation
	rpcFns map[string]func(context.Context, string, ...grpc.CallOption) (proto.Message, error)
}

func (c *ManagedSecureMeshSiteV2CustomAPIGrpcClient) doRPCListCloudResources(ctx context.Context, yamlReq string, opts ...grpc.CallOption) (proto.Message, error) {
	req := &ListCloudResourcesRequest{}
	if err := codec.FromYAML(yamlReq, req); err != nil {
		return nil, fmt.Errorf("YAML Request %s is not of type *ves.io.schema.views.securemesh_site_v2.ListCloudResourcesRequest", yamlReq)
	}
	rsp, err := c.grpcClient.ListCloudResources(ctx, req, opts...)
	return rsp, err
}

func (c *ManagedSecureMeshSiteV2CustomAPIGrpcClient) DoRPC(ctx context.Context, rpc string, opts ...server.CustomCallOpt) (proto.Message, error) {
	rpcFn, exists := c.rpcFns[rpc]
	if !exists {
		return nil, fmt.Errorf("Error, no such rpc %s", rpc)
	}
	cco := server.NewCustomCallOpts()
	for _, opt := range opts {
		opt(cco)
	}
	if cco.YAMLReq == "" {
		return nil, fmt.Errorf("Error, empty request body")
	}
	ctx = client.AddHdrsToCtx(cco.Headers, ctx)

	rsp, err := rpcFn(ctx, cco.YAMLReq, cco.GrpcCallOpts...)
	if err != nil {
		return nil, errors.Wrap(err, "Doing custom RPC using GRPC")
	}
	if cco.OutCallResponse != nil {
		cco.OutCallResponse.ProtoMsg = rsp
	}
	return rsp, nil
}

func NewManagedSecureMeshSiteV2CustomAPIGrpcClient(cc *grpc.ClientConn) server.CustomClient {
	ccl := &ManagedSecureMeshSiteV2CustomAPIGrpcClient{
		conn:       cc,
		grpcClient: NewManagedSecureMeshSiteV2CustomAPIClient(cc),
	}
	rpcFns := make(map[string]func(context.Context, string, ...grpc.CallOption) (proto.Message, error))
	rpcFns["ListCloudResources"] = ccl.doRPCListCloudResources
	ccl.rpcFns = rpcFns
	return ccl
}

// Create ManagedSecureMeshSiteV2CustomAPI REST Client satisfying server.CustomClient
type ManagedSecureMeshSiteV2CustomAPIRestClient struct {
	baseURL string
	client  http.Client
	// map of rpc name to its invocation
	rpcFns map[string]func(context.Context, *server.CustomCallOpts) (proto.Message, error)
}

func (c *ManagedSecureMeshSiteV2CustomAPIRestClient) doRPCListCloudResources(ctx context.Context, callOpts *server.CustomCallOpts) (proto.Message, error) {
	if callOpts.URI == "" {
		return nil, fmt.Errorf("Error, URI should be specified, got empty")
	}
	url := fmt.Sprintf("%s%s", c.baseURL, callOpts.URI)

	yamlReq := callOpts.YAMLReq
	req := &ListCloudResourcesRequest{}
	if err := codec.FromYAML(yamlReq, req); err != nil {
		return nil, fmt.Errorf("YAML Request %s is not of type *ves.io.schema.views.securemesh_site_v2.ListCloudResourcesRequest: %s", yamlReq, err)
	}

	var hReq *http.Request
	hm := strings.ToLower(callOpts.HTTPMethod)
	switch hm {
	case "post", "put":
		jsn, err := codec.ToJSON(req, codec.ToWithUseProtoFieldName())
		if err != nil {
			return nil, errors.Wrap(err, "Custom RestClient converting YAML to JSON")
		}
		var op string
		if hm == "post" {
			op = http.MethodPost
		} else {
			op = http.MethodPut
		}
		newReq, err := http.NewRequest(op, url, bytes.NewBuffer([]byte(jsn)))
		if err != nil {
			return nil, errors.Wrapf(err, "Creating new HTTP %s request for custom API", op)
		}
		hReq = newReq
	case "get":
		newReq, err := http.NewRequest(http.MethodGet, url, nil)
		if err != nil {
			return nil, errors.Wrap(err, "Creating new HTTP GET request for custom API")
		}
		hReq = newReq
		q := hReq.URL.Query()
		_ = q
		q.Add("deletion", fmt.Sprintf("%v", req.Deletion))
		q.Add("site_name", fmt.Sprintf("%v", req.SiteName))

		hReq.URL.RawQuery += q.Encode()
	case "delete":
		newReq, err := http.NewRequest(http.MethodDelete, url, nil)
		if err != nil {
			return nil, errors.Wrap(err, "Creating new HTTP DELETE request for custom API")
		}
		hReq = newReq
	default:
		return nil, fmt.Errorf("Error, invalid/empty HTTPMethod(%s) specified, should be POST|DELETE|GET", callOpts.HTTPMethod)
	}
	hReq = hReq.WithContext(ctx)
	hReq.Header.Set("Content-Type", "application/json")
	client.AddHdrsToReq(callOpts.Headers, hReq)

	rsp, err := c.client.Do(hReq)
	if err != nil {
		return nil, errors.Wrap(err, "Custom API RestClient")
	}
	defer rsp.Body.Close()

	// checking whether the status code is a successful status code (2xx series)
	if rsp.StatusCode < 200 || rsp.StatusCode > 299 {
		body, err := io.ReadAll(rsp.Body)
		return nil, fmt.Errorf("Unsuccessful custom API %s on %s, status code %d, body %s, err %s", callOpts.HTTPMethod, callOpts.URI, rsp.StatusCode, body, err)
	}

	body, err := io.ReadAll(rsp.Body)
	if err != nil {
		return nil, errors.Wrap(err, "Custom API RestClient read body")
	}
	pbRsp := &ListCloudResourceResponse{}
	if err := codec.FromJSON(string(body), pbRsp); err != nil {
		return nil, errors.Wrapf(err, "JSON Response %s is not of type *ves.io.schema.views.securemesh_site_v2.ListCloudResourceResponse", body)
	}
	if callOpts.OutCallResponse != nil {
		callOpts.OutCallResponse.ProtoMsg = pbRsp
		callOpts.OutCallResponse.JSON = string(body)
	}
	return pbRsp, nil
}

func (c *ManagedSecureMeshSiteV2CustomAPIRestClient) DoRPC(ctx context.Context, rpc string, opts ...server.CustomCallOpt) (proto.Message, error) {
	rpcFn, exists := c.rpcFns[rpc]
	if !exists {
		return nil, fmt.Errorf("Error, no such rpc %s", rpc)
	}
	cco := server.NewCustomCallOpts()
	for _, opt := range opts {
		opt(cco)
	}

	rsp, err := rpcFn(ctx, cco)
	if err != nil {
		return nil, errors.Wrap(err, "Doing custom RPC using Rest")
	}
	return rsp, nil
}

func NewManagedSecureMeshSiteV2CustomAPIRestClient(baseURL string, hc http.Client) server.CustomClient {
	ccl := &ManagedSecureMeshSiteV2CustomAPIRestClient{
		baseURL: baseURL,
		client:  hc,
	}

	rpcFns := make(map[string]func(context.Context, *server.CustomCallOpts) (proto.Message, error))
	rpcFns["ListCloudResources"] = ccl.doRPCListCloudResources
	ccl.rpcFns = rpcFns
	return ccl
}

// Create managedSecureMeshSiteV2CustomAPIInprocClient

// INPROC Client (satisfying ManagedSecureMeshSiteV2CustomAPIClient interface)
type managedSecureMeshSiteV2CustomAPIInprocClient struct {
	ManagedSecureMeshSiteV2CustomAPIServer
}

func (c *managedSecureMeshSiteV2CustomAPIInprocClient) ListCloudResources(ctx context.Context, in *ListCloudResourcesRequest, opts ...grpc.CallOption) (*ListCloudResourceResponse, error) {
	ctx = server.ContextWithRpcFQN(ctx, "ves.io.schema.views.securemesh_site_v2.ManagedSecureMeshSiteV2CustomAPI.ListCloudResources")
	return c.ManagedSecureMeshSiteV2CustomAPIServer.ListCloudResources(ctx, in)
}

func NewManagedSecureMeshSiteV2CustomAPIInprocClient(svc svcfw.Service) ManagedSecureMeshSiteV2CustomAPIClient {
	return &managedSecureMeshSiteV2CustomAPIInprocClient{ManagedSecureMeshSiteV2CustomAPIServer: NewManagedSecureMeshSiteV2CustomAPIServer(svc)}
}

// RegisterGwManagedSecureMeshSiteV2CustomAPIHandler registers with grpc-gw with an inproc-client backing so that
// rest to grpc happens without a grpc.Dial (thus avoiding additional certs for mTLS)
func RegisterGwManagedSecureMeshSiteV2CustomAPIHandler(ctx context.Context, mux *runtime.ServeMux, svc interface{}) error {
	s, ok := svc.(svcfw.Service)
	if !ok {
		return fmt.Errorf("svc is not svcfw.Service")
	}
	return RegisterManagedSecureMeshSiteV2CustomAPIHandlerClient(ctx, mux, NewManagedSecureMeshSiteV2CustomAPIInprocClient(s))
}

// Create managedSecureMeshSiteV2CustomAPISrv

// SERVER (satisfying ManagedSecureMeshSiteV2CustomAPIServer interface)
type managedSecureMeshSiteV2CustomAPISrv struct {
	svc svcfw.Service
}

func (s *managedSecureMeshSiteV2CustomAPISrv) ListCloudResources(ctx context.Context, in *ListCloudResourcesRequest) (*ListCloudResourceResponse, error) {
	ah := s.svc.GetAPIHandler("ves.io.schema.views.securemesh_site_v2.ManagedSecureMeshSiteV2CustomAPI")
	cah, ok := ah.(ManagedSecureMeshSiteV2CustomAPIServer)
	if !ok {
		return nil, fmt.Errorf("ah %v is not of type *ManagedSecureMeshSiteV2CustomAPIServer", ah)
	}

	var (
		rsp *ListCloudResourceResponse
		err error
	)

	bodyFields := svcfw.GenAuditReqBodyFields(ctx, s.svc, "ves.io.schema.views.securemesh_site_v2.ListCloudResourcesRequest", in)
	defer func() {
		if len(bodyFields) > 0 {
			server.ExtendAPIAudit(ctx, svcfw.PublicAPIBodyLog.Uid, bodyFields)
		}
		userMsg := "The 'ManagedSecureMeshSiteV2CustomAPI.ListCloudResources' operation on 'securemesh_site_v2'"
		if err == nil {
			userMsg += " was successfully performed."
		} else {
			userMsg += " failed to be performed."
		}
		server.AddUserMsgToAPIAudit(ctx, userMsg)
	}()

	if err := svcfw.FillOneofDefaultChoice(ctx, s.svc, in); err != nil {
		err = server.MaybePublicRestError(ctx, errors.Wrapf(err, "Filling oneof default choice"))
		return nil, server.GRPCStatusFromError(err).Err()
	}

	if s.svc.Config().EnableAPIValidation {
		if rvFn := s.svc.GetRPCValidator("ves.io.schema.views.securemesh_site_v2.ManagedSecureMeshSiteV2CustomAPI.ListCloudResources"); rvFn != nil {
			if verr := rvFn(ctx, in); verr != nil {
				err = server.MaybePublicRestError(ctx, errors.Wrapf(verr, "Validating Request"))
				return nil, server.GRPCStatusFromError(err).Err()
			}
		}
	}

	rsp, err = cah.ListCloudResources(ctx, in)
	if err != nil {
		return rsp, server.GRPCStatusFromError(server.MaybePublicRestError(ctx, err)).Err()
	}
	bodyFields = append(bodyFields, svcfw.GenAuditRspBodyFields(ctx, s.svc, "ves.io.schema.views.securemesh_site_v2.ListCloudResourceResponse", rsp)...)

	return rsp, nil
}

func NewManagedSecureMeshSiteV2CustomAPIServer(svc svcfw.Service) ManagedSecureMeshSiteV2CustomAPIServer {
	return &managedSecureMeshSiteV2CustomAPISrv{svc: svc}
}

var ManagedSecureMeshSiteV2CustomAPISwaggerJSON string = `{
    "swagger": "2.0",
    "info": {
        "title": "Configure Secure Mesh Site",
        "description": "Secure Mesh Site related public APIs served by lucario.\nIt is always scoped by system namespace.",
        "version": "version not set"
    },
    "schemes": [
        "http",
        "https"
    ],
    "consumes": [
        "application/json"
    ],
    "produces": [
        "application/json"
    ],
    "tags": [],
    "paths": {
        "/public/namespaces/system/securemesh_site_v2/{site_name}/cloud_resources": {
            "get": {
                "summary": "List Cloud Resources",
                "description": "API to list all resource for given site",
                "operationId": "ves.io.schema.views.securemesh_site_v2.ManagedSecureMeshSiteV2CustomAPI.ListCloudResources",
                "responses": {
                    "200": {
                        "description": "A successful response.",
                        "schema": {
                            "$ref": "#/definitions/securemesh_site_v2ListCloudResourceResponse"
                        }
                    },
                    "401": {
                        "description": "Returned when operation is not authorized",
                        "schema": {
                            "format": "string"
                        }
                    },
                    "403": {
                        "description": "Returned when there is no permission to access resource",
                        "schema": {
                            "format": "string"
                        }
                    },
                    "404": {
                        "description": "Returned when resource is not found",
                        "schema": {
                            "format": "string"
                        }
                    },
                    "409": {
                        "description": "Returned when operation on resource is conflicting with current value",
                        "schema": {
                            "format": "string"
                        }
                    },
                    "429": {
                        "description": "Returned when operation has been rejected as it is happening too frequently",
                        "schema": {
                            "format": "string"
                        }
                    },
                    "500": {
                        "description": "Returned when server encountered an error in processing API",
                        "schema": {
                            "format": "string"
                        }
                    },
                    "503": {
                        "description": "Returned when service is unavailable temporarily",
                        "schema": {
                            "format": "string"
                        }
                    },
                    "504": {
                        "description": "Returned when server timed out processing request",
                        "schema": {
                            "format": "string"
                        }
                    }
                },
                "parameters": [
                    {
                        "name": "site_name",
                        "description": "site name\n\nsite name",
                        "in": "path",
                        "required": true,
                        "type": "string",
                        "x-displayname": "Site Name"
                    },
                    {
                        "name": "deletion",
                        "description": "query param deletion to get only to be deleted and all resource",
                        "in": "query",
                        "required": false,
                        "type": "boolean",
                        "format": "boolean",
                        "x-displayname": "Deletion"
                    }
                ],
                "tags": [
                    "ManagedSecureMeshSiteV2CustomAPI"
                ],
                "externalDocs": {
                    "description": "Examples of this operation",
                    "url": "https://docs.cloud.f5.com/docs-v2/platform/reference/api-ref/ves-io-schema-views-securemesh_site_v2-managedsecuremeshsitev2customapi-listcloudresources"
                },
                "x-ves-proto-rpc": "ves.io.schema.views.securemesh_site_v2.ManagedSecureMeshSiteV2CustomAPI.ListCloudResources"
            },
            "x-displayname": "Configure Secure Mesh Site",
            "x-ves-proto-service": "ves.io.schema.views.securemesh_site_v2.ManagedSecureMeshSiteV2CustomAPI",
            "x-ves-proto-service-type": "CUSTOM_PUBLIC"
        }
    },
    "definitions": {
        "securemesh_site_v2AwsCloudResourceListType": {
            "type": "object",
            "description": "AWS Cloud Resources",
            "title": "AWS Cloud Resource List Type",
            "x-displayname": "AWS Cloud Resources",
            "x-ves-proto-message": "ves.io.schema.views.securemesh_site_v2.AwsCloudResourceListType",
            "properties": {
                "aws_cloud_resources": {
                    "type": "array",
                    "description": " List of AWS Cloud Resource",
                    "title": "AWS Cloud Resource",
                    "items": {
                        "$ref": "#/definitions/securemesh_site_v2AwsCloudResourceType"
                    },
                    "x-displayname": "AWS Cloud Resources"
                }
            }
        },
        "securemesh_site_v2AwsCloudResourceType": {
            "type": "object",
            "description": "AWS Cloud Resource Type",
            "title": "AWS Cloud Resource Type",
            "x-displayname": "AWS Cloud Resource",
            "x-ves-proto-message": "ves.io.schema.views.securemesh_site_v2.AwsCloudResourceType",
            "properties": {
                "resource_id": {
                    "type": "array",
                    "description": " Resource Id",
                    "title": "Resource Id",
                    "items": {
                        "type": "string"
                    },
                    "x-displayname": "Resource ID"
                },
                "resource_type": {
                    "type": "string",
                    "description": " Resource Type",
                    "title": "Resource Type",
                    "x-displayname": "Resource Type"
                }
            }
        },
        "securemesh_site_v2ListCloudResourceResponse": {
            "type": "object",
            "description": "List all cloud resources",
            "title": "Cloud Resource Response",
            "x-displayname": "Cloud Resource Response",
            "x-ves-oneof-field-cloud_resource_choice": "[\"aws_cloud_resources\"]",
            "x-ves-proto-message": "ves.io.schema.views.securemesh_site_v2.ListCloudResourceResponse",
            "properties": {
                "aws_cloud_resources": {
                    "description": "Exclusive with []\n AWS Cloud Resources",
                    "title": "AWS Cloud Resource List Type",
                    "$ref": "#/definitions/securemesh_site_v2AwsCloudResourceListType",
                    "x-displayname": "AWS Cloud Resources"
                }
            }
        }
    },
    "x-displayname": "Configure Secure Mesh Site",
    "x-ves-proto-file": "ves.io/schema/views/securemesh_site_v2/public_customapi_lucario.proto"
}`
