//
// Copyright (c) 2018 Volterra, Inc. All rights reserved.
// Code generated by ves-gen-tf-provider. DO NOT EDIT.
//

package volterra

import (
	"context"
	"fmt"
	"log"
	"strings"

	"github.com/hashicorp/terraform-plugin-sdk/v2/helper/schema"

	"gopkg.volterra.us/stdlib/client/vesapi"

	ves_io_schema "github.com/volterraedge/terraform-provider-volterra/pbgo/extschema/schema"
	ves_io_schema_vs_profiles_services_http_router "github.com/volterraedge/terraform-provider-volterra/pbgo/extschema/schema/vs_profiles/services/http_router"
)

// resourceVolterraHttpRouter is implementation of Volterra's HttpRouter resources
func resourceVolterraHttpRouter() *schema.Resource {
	return &schema.Resource{
		Create: resourceVolterraHttpRouterCreate,
		Read:   resourceVolterraHttpRouterRead,
		Update: resourceVolterraHttpRouterUpdate,
		Delete: resourceVolterraHttpRouterDelete,

		Schema: map[string]*schema.Schema{

			"annotations": {
				Type:     schema.TypeMap,
				Optional: true,
			},

			"description": {
				Type:     schema.TypeString,
				Optional: true,
			},

			"disable": {
				Type:     schema.TypeBool,
				Optional: true,
			},

			"labels": {
				Type:     schema.TypeMap,
				Optional: true,
			},

			"name": {
				Type:     schema.TypeString,
				Required: true,
				ForceNew: true,
			},

			"namespace": {
				Type:     schema.TypeString,
				Required: true,
				ForceNew: true,
			},

			"app_service": {
				Type:     schema.TypeString,
				Optional: true,
			},

			"full_path": {
				Type:     schema.TypeString,
				Optional: true,
			},

			"sub_path": {
				Type:     schema.TypeString,
				Optional: true,
			},

			"user_spec": {

				Type: schema.TypeList,

				Optional: true,
				Elem: &schema.Schema{
					Type: schema.TypeString,
				},
			},
		},
	}
}

// resourceVolterraHttpRouterCreate creates HttpRouter resource
func resourceVolterraHttpRouterCreate(d *schema.ResourceData, meta interface{}) error {
	client := meta.(*APIClient)

	createMeta := &ves_io_schema.ObjectCreateMetaType{}
	createSpec := &ves_io_schema_vs_profiles_services_http_router.CreateSpecType{}
	createReq := &ves_io_schema_vs_profiles_services_http_router.CreateRequest{
		Metadata: createMeta,
		Spec:     createSpec,
	}

	if v, ok := d.GetOk("annotations"); ok && !isIntfNil(v) {

		ms := map[string]string{}

		for k, v := range v.(map[string]interface{}) {
			val := v.(string)
			ms[k] = val
		}
		createMeta.Annotations = ms
	}

	if v, ok := d.GetOk("description"); ok && !isIntfNil(v) {
		createMeta.Description =
			v.(string)
	}

	if v, ok := d.GetOk("disable"); ok && !isIntfNil(v) {
		createMeta.Disable =
			v.(bool)
	}

	if v, ok := d.GetOk("labels"); ok && !isIntfNil(v) {

		ms := map[string]string{}

		for k, v := range v.(map[string]interface{}) {
			val := v.(string)
			ms[k] = val
		}
		createMeta.Labels = ms
	}

	if v, ok := d.GetOk("name"); ok && !isIntfNil(v) {
		createMeta.Name =
			v.(string)
	}

	if v, ok := d.GetOk("namespace"); ok && !isIntfNil(v) {
		createMeta.Namespace =
			v.(string)
	}

	//app_service
	if v, ok := d.GetOk("app_service"); ok && !isIntfNil(v) {

		createSpec.AppService =
			v.(string)

	}

	//full_path
	if v, ok := d.GetOk("full_path"); ok && !isIntfNil(v) {

		createSpec.FullPath =
			v.(string)

	}

	//sub_path
	if v, ok := d.GetOk("sub_path"); ok && !isIntfNil(v) {

		createSpec.SubPath =
			v.(string)

	}

	//user_spec
	if v, ok := d.GetOk("user_spec"); ok && !isIntfNil(v) {

		ls := make([]string, len(v.([]interface{})))
		for i, v := range v.([]interface{}) {
			if v == nil {
				return fmt.Errorf("please provide valid non-empty string value of field user_spec")
			}
			if str, ok := v.(string); ok {
				ls[i] = str
			}
		}
		createSpec.UserSpec = ls

	}

	log.Printf("[DEBUG] Creating Volterra HttpRouter object with struct: %+v", createReq)

	createHttpRouterResp, err := client.CreateObject(context.Background(), ves_io_schema_vs_profiles_services_http_router.ObjectType, createReq)
	if err != nil {
		return fmt.Errorf("error creating HttpRouter: %s", err)
	}
	d.SetId(createHttpRouterResp.GetObjSystemMetadata().GetUid())

	return resourceVolterraHttpRouterRead(d, meta)
}

func resourceVolterraHttpRouterRead(d *schema.ResourceData, meta interface{}) error {
	client := meta.(*APIClient)
	name := d.Get("name").(string)
	namespace := d.Get("namespace").(string)

	resp, err := client.GetObject(context.Background(), ves_io_schema_vs_profiles_services_http_router.ObjectType, namespace, name)
	if err != nil {
		if strings.Contains(err.Error(), "status code 404") {
			log.Printf("[INFO] HttpRouter %s no longer exists", d.Id())
			d.SetId("")
			return nil
		}
		return fmt.Errorf("Error finding Volterra HttpRouter %q: %s", d.Id(), err)
	}

	return setHttpRouterFields(client, d, resp)
}

func setHttpRouterFields(client *APIClient, d *schema.ResourceData, resp vesapi.GetObjectResponse) error {
	metadata := resp.GetObjMetadata()

	d.Set("annotations", metadata.GetAnnotations())

	d.Set("description", metadata.GetDescription())

	d.Set("disable", metadata.GetDisable())

	d.Set("labels", metadata.GetLabels())

	d.Set("name", metadata.GetName())

	d.Set("namespace", metadata.GetNamespace())

	return nil
}

// resourceVolterraHttpRouterUpdate updates HttpRouter resource
func resourceVolterraHttpRouterUpdate(d *schema.ResourceData, meta interface{}) error {
	client := meta.(*APIClient)

	updateMeta := &ves_io_schema.ObjectReplaceMetaType{}
	updateSpec := &ves_io_schema_vs_profiles_services_http_router.ReplaceSpecType{}
	updateReq := &ves_io_schema_vs_profiles_services_http_router.ReplaceRequest{
		Metadata: updateMeta,
		Spec:     updateSpec,
	}

	if v, ok := d.GetOk("annotations"); ok && !isIntfNil(v) {

		ms := map[string]string{}

		for k, v := range v.(map[string]interface{}) {
			val := v.(string)
			ms[k] = val
		}
		updateMeta.Annotations = ms
	}

	if v, ok := d.GetOk("description"); ok && !isIntfNil(v) {
		updateMeta.Description =
			v.(string)
	}

	if v, ok := d.GetOk("disable"); ok && !isIntfNil(v) {
		updateMeta.Disable =
			v.(bool)
	}

	if v, ok := d.GetOk("labels"); ok && !isIntfNil(v) {

		ms := map[string]string{}

		for k, v := range v.(map[string]interface{}) {
			val := v.(string)
			ms[k] = val
		}
		updateMeta.Labels = ms
	}

	if v, ok := d.GetOk("name"); ok && !isIntfNil(v) {
		updateMeta.Name =
			v.(string)
	}

	if v, ok := d.GetOk("namespace"); ok && !isIntfNil(v) {
		updateMeta.Namespace =
			v.(string)
	}

	if v, ok := d.GetOk("app_service"); ok && !isIntfNil(v) {

		updateSpec.AppService =
			v.(string)

	}

	if v, ok := d.GetOk("full_path"); ok && !isIntfNil(v) {

		updateSpec.FullPath =
			v.(string)

	}

	if v, ok := d.GetOk("sub_path"); ok && !isIntfNil(v) {

		updateSpec.SubPath =
			v.(string)

	}

	if v, ok := d.GetOk("user_spec"); ok && !isIntfNil(v) {

		ls := make([]string, len(v.([]interface{})))
		for i, v := range v.([]interface{}) {
			if v == nil {
				return fmt.Errorf("please provide valid non-empty string value of field user_spec")
			}
			if str, ok := v.(string); ok {
				ls[i] = str
			}
		}
		updateSpec.UserSpec = ls

	}

	log.Printf("[DEBUG] Updating Volterra HttpRouter obj with struct: %+v", updateReq)

	err := client.ReplaceObject(context.Background(), ves_io_schema_vs_profiles_services_http_router.ObjectType, updateReq)
	if err != nil {
		return fmt.Errorf("error updating HttpRouter: %s", err)
	}

	return resourceVolterraHttpRouterRead(d, meta)
}

func resourceVolterraHttpRouterDelete(d *schema.ResourceData, meta interface{}) error {
	client := meta.(*APIClient)
	name := d.Get("name").(string)
	namespace := d.Get("namespace").(string)

	_, err := client.GetObject(context.Background(), ves_io_schema_vs_profiles_services_http_router.ObjectType, namespace, name)
	if err != nil {
		if strings.Contains(err.Error(), "status code 404") {
			log.Printf("[INFO] HttpRouter %s no longer exists", d.Id())
			d.SetId("")
			return nil
		}
		return fmt.Errorf("Error finding Volterra HttpRouter before deleting %q: %s", d.Id(), err)
	}

	log.Printf("[DEBUG] Deleting Volterra HttpRouter obj with name %+v in namespace %+v", name, namespace)
	opts := []vesapi.CallOpt{
		vesapi.WithFailIfReferred(),
	}

	err = client.DeleteObject(context.Background(), ves_io_schema_vs_profiles_services_http_router.ObjectType, namespace, name, opts...)
	if err != nil {
		return fmt.Errorf("error deleting HttpRouter: %w", err)
	}
	return nil

}
