// Code generated by protoc-gen-gogo. DO NOT EDIT.
// source: ves.io/schema/views/virtual_server/public_customapi.proto

// Virtual Server
//
// x-displayName: "Virtual Server"

package virtual_server

import (
	context "context"
	fmt "fmt"
	_ "github.com/gogo/googleapis/google/api"
	_ "github.com/gogo/protobuf/gogoproto"
	proto "github.com/gogo/protobuf/proto"
	golang_proto "github.com/golang/protobuf/proto"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
	_ "github.com/volterraedge/terraform-provider-volterra/pbgo/extschema/schema"
	irule "github.com/volterraedge/terraform-provider-volterra/pbgo/extschema/schema/bigcne/irule"
	traffic_policy "github.com/volterraedge/terraform-provider-volterra/pbgo/extschema/schema/traffic_policy"
	_ "github.com/volterraedge/terraform-provider-volterra/pbgo/extschema/schema/vesenv"
	virtual_address "github.com/volterraedge/terraform-provider-volterra/pbgo/extschema/schema/views/virtual_address"
	io "io"
	math "math"
	math_bits "math/bits"
	reflect "reflect"
	strings "strings"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = golang_proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.GoGoProtoPackageIsVersion3 // please upgrade the proto package

// Get Associated Objects Request
//
// x-displayName: "Get Associated Objects Request"
// Request message for associated-objects API
type GetAssociatedObjectsRequest struct {
	// Namespace
	//
	// x-displayName: "Namespace"
	// x-example: "value"
	// Namespace for the virtual server
	Namespace string `protobuf:"bytes,1,opt,name=namespace,proto3" json:"namespace,omitempty"`
	// Name
	//
	// x-displayName: "Name"
	// x-example: "value"
	// Name of the virtual server
	Name string `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
}

func (m *GetAssociatedObjectsRequest) Reset()      { *m = GetAssociatedObjectsRequest{} }
func (*GetAssociatedObjectsRequest) ProtoMessage() {}
func (*GetAssociatedObjectsRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_0aeca9a4eff8139f, []int{0}
}
func (m *GetAssociatedObjectsRequest) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *GetAssociatedObjectsRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_GetAssociatedObjectsRequest.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *GetAssociatedObjectsRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GetAssociatedObjectsRequest.Merge(m, src)
}
func (m *GetAssociatedObjectsRequest) XXX_Size() int {
	return m.Size()
}
func (m *GetAssociatedObjectsRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_GetAssociatedObjectsRequest.DiscardUnknown(m)
}

var xxx_messageInfo_GetAssociatedObjectsRequest proto.InternalMessageInfo

func (m *GetAssociatedObjectsRequest) GetNamespace() string {
	if m != nil {
		return m.Namespace
	}
	return ""
}

func (m *GetAssociatedObjectsRequest) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

// Get Associated Objects Response
//
// x-displayName: "Get Associated Objects Response"
// Response for get-associated-objects API
type GetAssociatedObjectsResponse struct {
	// Virtual Addresses
	//
	// x-displayName: "Virtual Address List"
	// Virtual address objects for this virtual server
	VirtualAddresses []*virtual_address.Object `protobuf:"bytes,1,rep,name=virtual_addresses,json=virtualAddresses,proto3" json:"virtual_addresses,omitempty"`
	// iRules
	//
	// x-displayName: "iRule List"
	// iRules for this virtual server
	Irules []*irule.Object `protobuf:"bytes,2,rep,name=irules,proto3" json:"irules,omitempty"`
	// Traffic Policies
	//
	// x-displayName: "Traffic Policies"
	TrafficPolicies []*traffic_policy.Object `protobuf:"bytes,3,rep,name=traffic_policies,json=trafficPolicies,proto3" json:"traffic_policies,omitempty"`
}

func (m *GetAssociatedObjectsResponse) Reset()      { *m = GetAssociatedObjectsResponse{} }
func (*GetAssociatedObjectsResponse) ProtoMessage() {}
func (*GetAssociatedObjectsResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_0aeca9a4eff8139f, []int{1}
}
func (m *GetAssociatedObjectsResponse) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *GetAssociatedObjectsResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_GetAssociatedObjectsResponse.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *GetAssociatedObjectsResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GetAssociatedObjectsResponse.Merge(m, src)
}
func (m *GetAssociatedObjectsResponse) XXX_Size() int {
	return m.Size()
}
func (m *GetAssociatedObjectsResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_GetAssociatedObjectsResponse.DiscardUnknown(m)
}

var xxx_messageInfo_GetAssociatedObjectsResponse proto.InternalMessageInfo

func (m *GetAssociatedObjectsResponse) GetVirtualAddresses() []*virtual_address.Object {
	if m != nil {
		return m.VirtualAddresses
	}
	return nil
}

func (m *GetAssociatedObjectsResponse) GetIrules() []*irule.Object {
	if m != nil {
		return m.Irules
	}
	return nil
}

func (m *GetAssociatedObjectsResponse) GetTrafficPolicies() []*traffic_policy.Object {
	if m != nil {
		return m.TrafficPolicies
	}
	return nil
}

func init() {
	proto.RegisterType((*GetAssociatedObjectsRequest)(nil), "ves.io.schema.views.virtual_server.GetAssociatedObjectsRequest")
	golang_proto.RegisterType((*GetAssociatedObjectsRequest)(nil), "ves.io.schema.views.virtual_server.GetAssociatedObjectsRequest")
	proto.RegisterType((*GetAssociatedObjectsResponse)(nil), "ves.io.schema.views.virtual_server.GetAssociatedObjectsResponse")
	golang_proto.RegisterType((*GetAssociatedObjectsResponse)(nil), "ves.io.schema.views.virtual_server.GetAssociatedObjectsResponse")
}

func init() {
	proto.RegisterFile("ves.io/schema/views/virtual_server/public_customapi.proto", fileDescriptor_0aeca9a4eff8139f)
}
func init() {
	golang_proto.RegisterFile("ves.io/schema/views/virtual_server/public_customapi.proto", fileDescriptor_0aeca9a4eff8139f)
}

var fileDescriptor_0aeca9a4eff8139f = []byte{
	// 640 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x9c, 0x94, 0xcf, 0x6b, 0xd4, 0x40,
	0x14, 0xc7, 0x77, 0xb2, 0x52, 0x68, 0x3c, 0xb8, 0x06, 0x0f, 0xcb, 0x76, 0x19, 0xca, 0x22, 0xd8,
	0x62, 0x93, 0xd1, 0x8a, 0x88, 0xa7, 0xda, 0x7a, 0xf0, 0xc7, 0xa5, 0x65, 0x4f, 0x22, 0x48, 0x99,
	0x24, 0x6f, 0xd3, 0xd1, 0x24, 0x13, 0x67, 0x26, 0xb1, 0x45, 0x16, 0xa4, 0x47, 0x4f, 0xa2, 0x7f,
	0x81, 0x17, 0xf1, 0x4f, 0x10, 0x7a, 0xd9, 0x9b, 0x3d, 0x49, 0xd1, 0x4b, 0x8f, 0x36, 0xeb, 0x41,
	0x04, 0xa1, 0x7f, 0x82, 0x74, 0x92, 0x56, 0x13, 0xca, 0x2a, 0xde, 0xde, 0xe4, 0xfb, 0xde, 0x67,
	0x7e, 0x7c, 0xdf, 0x8b, 0x79, 0x33, 0x03, 0xe9, 0x30, 0x4e, 0xa4, 0xb7, 0x01, 0x11, 0x25, 0x19,
	0x83, 0x67, 0x92, 0x64, 0x4c, 0xa8, 0x94, 0x86, 0xeb, 0x12, 0x44, 0x06, 0x82, 0x24, 0xa9, 0x1b,
	0x32, 0x6f, 0xdd, 0x4b, 0xa5, 0xe2, 0x11, 0x4d, 0x98, 0x93, 0x08, 0xae, 0xb8, 0xd5, 0x2b, 0x4a,
	0x9d, 0xa2, 0xd4, 0xd1, 0xa5, 0x4e, 0xb5, 0xb4, 0x63, 0x07, 0x4c, 0x6d, 0xa4, 0xae, 0xe3, 0xf1,
	0x88, 0x04, 0x3c, 0xe0, 0x44, 0x97, 0xba, 0xe9, 0x40, 0xaf, 0xf4, 0x42, 0x47, 0x05, 0xb2, 0xd3,
	0x0d, 0x38, 0x0f, 0x42, 0x20, 0x34, 0x61, 0x84, 0xc6, 0x31, 0x57, 0x54, 0x31, 0x1e, 0xcb, 0x52,
	0xbd, 0x54, 0x3d, 0xab, 0xcb, 0x02, 0x2f, 0x06, 0xc2, 0x44, 0x1a, 0x02, 0xe1, 0xee, 0x63, 0xf0,
	0x54, 0x99, 0x38, 0x53, 0x4d, 0xe4, 0xc9, 0x9f, 0x94, 0xf9, 0xaa, 0xa8, 0x04, 0x1d, 0x0c, 0x98,
	0xb7, 0x9e, 0xf0, 0x90, 0x79, 0x5b, 0x55, 0x4e, 0xb7, 0xf6, 0x38, 0x34, 0x64, 0x3e, 0x55, 0x50,
	0xaa, 0xbd, 0x9a, 0x0a, 0x12, 0xe2, 0xac, 0xb6, 0xd9, 0x95, 0x49, 0xcf, 0x4b, 0x7d, 0x5f, 0x80,
	0x94, 0x95, 0x3d, 0x7b, 0xab, 0xe6, 0xcc, 0x1d, 0x50, 0xcb, 0x52, 0x72, 0x8f, 0x51, 0x05, 0xfe,
	0xaa, 0x16, 0x65, 0x1f, 0x9e, 0xa6, 0x20, 0x95, 0xd5, 0x35, 0xa7, 0x63, 0x1a, 0x81, 0x4c, 0xa8,
	0x07, 0x6d, 0x34, 0x8b, 0xe6, 0xa6, 0xfb, 0xbf, 0x3f, 0x58, 0x96, 0x79, 0xe6, 0x68, 0xd1, 0x36,
	0xb4, 0xa0, 0xe3, 0xde, 0x5b, 0xc3, 0xec, 0x9e, 0x4e, 0x94, 0x09, 0x8f, 0x25, 0x58, 0x8f, 0xcc,
	0xf3, 0xb5, 0x13, 0x81, 0x6c, 0xa3, 0xd9, 0xe6, 0xdc, 0xd9, 0xc5, 0xcb, 0xce, 0x24, 0x8f, 0xcb,
	0x6c, 0xa7, 0x00, 0xae, 0x34, 0x47, 0x43, 0xd4, 0x6f, 0x95, 0xe2, 0xf2, 0x31, 0xc9, 0x5a, 0x32,
	0xa7, 0xb4, 0x45, 0xb2, 0x6d, 0x68, 0x66, 0xaf, 0xc6, 0x2c, 0x6c, 0x74, 0x74, 0x4e, 0x05, 0x55,
	0x96, 0x59, 0xd4, 0x6c, 0x55, 0x4c, 0x62, 0x20, 0xdb, 0x4d, 0x8d, 0xba, 0x58, 0x43, 0x55, 0xbd,
	0x3c, 0x86, 0xb5, 0x46, 0x43, 0xf4, 0x63, 0x68, 0xfa, 0x10, 0xf1, 0xab, 0x0b, 0x0a, 0xa4, 0xea,
	0x9f, 0x2b, 0x13, 0xd7, 0x4a, 0xdc, 0xe2, 0x4f, 0xc3, 0x9c, 0xbe, 0xad, 0xdb, 0x7b, 0x79, 0xed,
	0x9e, 0xf5, 0xce, 0x30, 0x2f, 0x9c, 0xf6, 0x62, 0xd6, 0x92, 0xf3, 0xf7, 0x96, 0x77, 0x26, 0xb8,
	0xd7, 0xb9, 0xf5, 0xff, 0x80, 0xc2, 0xac, 0xde, 0x4b, 0xb4, 0xfb, 0xc1, 0x40, 0xf9, 0xc7, 0xf6,
	0xe2, 0xe0, 0xfa, 0xa6, 0x67, 0x4b, 0xf0, 0x52, 0x01, 0x11, 0xc8, 0x0d, 0x5b, 0x2a, 0x1a, 0xfb,
	0x54, 0xf8, 0x76, 0xc4, 0x63, 0xa6, 0xb8, 0x58, 0xc8, 0x40, 0xda, 0x8c, 0xdb, 0x89, 0xe0, 0x9b,
	0x5b, 0xb6, 0x00, 0xea, 0x6f, 0x7f, 0xf9, 0xf6, 0xc6, 0xb8, 0x6f, 0xdd, 0x2d, 0x07, 0x9a, 0x9c,
	0xf4, 0x8d, 0x24, 0xcf, 0x4f, 0xe2, 0x61, 0x6d, 0xfa, 0x4b, 0x6d, 0x48, 0xe8, 0xc9, 0x99, 0xec,
	0xa2, 0x61, 0x65, 0xe7, 0xc6, 0x68, 0x07, 0x35, 0x3f, 0xef, 0xa0, 0xf9, 0x7f, 0xb8, 0x55, 0x71,
	0x91, 0xed, 0x4f, 0x6d, 0xa3, 0x85, 0x56, 0x5e, 0xa3, 0xbd, 0x03, 0xdc, 0xd8, 0x3f, 0xc0, 0x8d,
	0xc3, 0x03, 0x8c, 0x5e, 0xe4, 0x18, 0xbd, 0xcf, 0x31, 0xda, 0xcd, 0x31, 0xda, 0xcb, 0x31, 0xfa,
	0x9a, 0x63, 0xf4, 0x3d, 0xc7, 0x8d, 0xc3, 0x1c, 0xa3, 0x57, 0x63, 0xdc, 0x18, 0x8d, 0x31, 0xda,
	0x1b, 0xe3, 0xc6, 0xfe, 0x18, 0x37, 0x1e, 0x3e, 0x08, 0x78, 0xf2, 0x24, 0x70, 0x32, 0x1e, 0x2a,
	0x10, 0x82, 0x3a, 0xa9, 0x24, 0x3a, 0x18, 0x70, 0x11, 0x1d, 0xdd, 0x35, 0x63, 0x3e, 0x08, 0xfb,
	0x58, 0x26, 0x89, 0x1b, 0x70, 0x02, 0x9b, 0xaa, 0x1c, 0xc0, 0x09, 0xbf, 0x39, 0x77, 0x4a, 0x0f,
	0xe0, 0xb5, 0x5f, 0x01, 0x00, 0x00, 0xff, 0xff, 0x94, 0x49, 0xd0, 0xc3, 0x13, 0x05, 0x00, 0x00,
}

func (this *GetAssociatedObjectsRequest) Equal(that interface{}) bool {
	if that == nil {
		return this == nil
	}

	that1, ok := that.(*GetAssociatedObjectsRequest)
	if !ok {
		that2, ok := that.(GetAssociatedObjectsRequest)
		if ok {
			that1 = &that2
		} else {
			return false
		}
	}
	if that1 == nil {
		return this == nil
	} else if this == nil {
		return false
	}
	if this.Namespace != that1.Namespace {
		return false
	}
	if this.Name != that1.Name {
		return false
	}
	return true
}
func (this *GetAssociatedObjectsResponse) Equal(that interface{}) bool {
	if that == nil {
		return this == nil
	}

	that1, ok := that.(*GetAssociatedObjectsResponse)
	if !ok {
		that2, ok := that.(GetAssociatedObjectsResponse)
		if ok {
			that1 = &that2
		} else {
			return false
		}
	}
	if that1 == nil {
		return this == nil
	} else if this == nil {
		return false
	}
	if len(this.VirtualAddresses) != len(that1.VirtualAddresses) {
		return false
	}
	for i := range this.VirtualAddresses {
		if !this.VirtualAddresses[i].Equal(that1.VirtualAddresses[i]) {
			return false
		}
	}
	if len(this.Irules) != len(that1.Irules) {
		return false
	}
	for i := range this.Irules {
		if !this.Irules[i].Equal(that1.Irules[i]) {
			return false
		}
	}
	if len(this.TrafficPolicies) != len(that1.TrafficPolicies) {
		return false
	}
	for i := range this.TrafficPolicies {
		if !this.TrafficPolicies[i].Equal(that1.TrafficPolicies[i]) {
			return false
		}
	}
	return true
}
func (this *GetAssociatedObjectsRequest) GoString() string {
	if this == nil {
		return "nil"
	}
	s := make([]string, 0, 6)
	s = append(s, "&virtual_server.GetAssociatedObjectsRequest{")
	s = append(s, "Namespace: "+fmt.Sprintf("%#v", this.Namespace)+",\n")
	s = append(s, "Name: "+fmt.Sprintf("%#v", this.Name)+",\n")
	s = append(s, "}")
	return strings.Join(s, "")
}
func (this *GetAssociatedObjectsResponse) GoString() string {
	if this == nil {
		return "nil"
	}
	s := make([]string, 0, 7)
	s = append(s, "&virtual_server.GetAssociatedObjectsResponse{")
	if this.VirtualAddresses != nil {
		s = append(s, "VirtualAddresses: "+fmt.Sprintf("%#v", this.VirtualAddresses)+",\n")
	}
	if this.Irules != nil {
		s = append(s, "Irules: "+fmt.Sprintf("%#v", this.Irules)+",\n")
	}
	if this.TrafficPolicies != nil {
		s = append(s, "TrafficPolicies: "+fmt.Sprintf("%#v", this.TrafficPolicies)+",\n")
	}
	s = append(s, "}")
	return strings.Join(s, "")
}
func valueToGoStringPublicCustomapi(v interface{}, typ string) string {
	rv := reflect.ValueOf(v)
	if rv.IsNil() {
		return "nil"
	}
	pv := reflect.Indirect(rv).Interface()
	return fmt.Sprintf("func(v %v) *%v { return &v } ( %#v )", typ, typ, pv)
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConn

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion4

// CustomAPIClient is the client API for CustomAPI service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://godoc.org/google.golang.org/grpc#ClientConn.NewStream.
type CustomAPIClient interface {
	// Get Associated Objects
	//
	// x-displayName: "Get Associated Objects"
	// GetAssociatedObjects is an API to get associated objects for the specified virtual server, like virtual addresses, traffic policies, and iRules.
	GetAssociatedObjects(ctx context.Context, in *GetAssociatedObjectsRequest, opts ...grpc.CallOption) (*GetAssociatedObjectsResponse, error)
}

type customAPIClient struct {
	cc *grpc.ClientConn
}

func NewCustomAPIClient(cc *grpc.ClientConn) CustomAPIClient {
	return &customAPIClient{cc}
}

func (c *customAPIClient) GetAssociatedObjects(ctx context.Context, in *GetAssociatedObjectsRequest, opts ...grpc.CallOption) (*GetAssociatedObjectsResponse, error) {
	out := new(GetAssociatedObjectsResponse)
	err := c.cc.Invoke(ctx, "/ves.io.schema.views.virtual_server.CustomAPI/GetAssociatedObjects", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// CustomAPIServer is the server API for CustomAPI service.
type CustomAPIServer interface {
	// Get Associated Objects
	//
	// x-displayName: "Get Associated Objects"
	// GetAssociatedObjects is an API to get associated objects for the specified virtual server, like virtual addresses, traffic policies, and iRules.
	GetAssociatedObjects(context.Context, *GetAssociatedObjectsRequest) (*GetAssociatedObjectsResponse, error)
}

// UnimplementedCustomAPIServer can be embedded to have forward compatible implementations.
type UnimplementedCustomAPIServer struct {
}

func (*UnimplementedCustomAPIServer) GetAssociatedObjects(ctx context.Context, req *GetAssociatedObjectsRequest) (*GetAssociatedObjectsResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetAssociatedObjects not implemented")
}

func RegisterCustomAPIServer(s *grpc.Server, srv CustomAPIServer) {
	s.RegisterService(&_CustomAPI_serviceDesc, srv)
}

func _CustomAPI_GetAssociatedObjects_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetAssociatedObjectsRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(CustomAPIServer).GetAssociatedObjects(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/ves.io.schema.views.virtual_server.CustomAPI/GetAssociatedObjects",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(CustomAPIServer).GetAssociatedObjects(ctx, req.(*GetAssociatedObjectsRequest))
	}
	return interceptor(ctx, in, info, handler)
}

var _CustomAPI_serviceDesc = grpc.ServiceDesc{
	ServiceName: "ves.io.schema.views.virtual_server.CustomAPI",
	HandlerType: (*CustomAPIServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "GetAssociatedObjects",
			Handler:    _CustomAPI_GetAssociatedObjects_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "ves.io/schema/views/virtual_server/public_customapi.proto",
}

func (m *GetAssociatedObjectsRequest) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *GetAssociatedObjectsRequest) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *GetAssociatedObjectsRequest) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	if len(m.Name) > 0 {
		i -= len(m.Name)
		copy(dAtA[i:], m.Name)
		i = encodeVarintPublicCustomapi(dAtA, i, uint64(len(m.Name)))
		i--
		dAtA[i] = 0x12
	}
	if len(m.Namespace) > 0 {
		i -= len(m.Namespace)
		copy(dAtA[i:], m.Namespace)
		i = encodeVarintPublicCustomapi(dAtA, i, uint64(len(m.Namespace)))
		i--
		dAtA[i] = 0xa
	}
	return len(dAtA) - i, nil
}

func (m *GetAssociatedObjectsResponse) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *GetAssociatedObjectsResponse) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *GetAssociatedObjectsResponse) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	if len(m.TrafficPolicies) > 0 {
		for iNdEx := len(m.TrafficPolicies) - 1; iNdEx >= 0; iNdEx-- {
			{
				size, err := m.TrafficPolicies[iNdEx].MarshalToSizedBuffer(dAtA[:i])
				if err != nil {
					return 0, err
				}
				i -= size
				i = encodeVarintPublicCustomapi(dAtA, i, uint64(size))
			}
			i--
			dAtA[i] = 0x1a
		}
	}
	if len(m.Irules) > 0 {
		for iNdEx := len(m.Irules) - 1; iNdEx >= 0; iNdEx-- {
			{
				size, err := m.Irules[iNdEx].MarshalToSizedBuffer(dAtA[:i])
				if err != nil {
					return 0, err
				}
				i -= size
				i = encodeVarintPublicCustomapi(dAtA, i, uint64(size))
			}
			i--
			dAtA[i] = 0x12
		}
	}
	if len(m.VirtualAddresses) > 0 {
		for iNdEx := len(m.VirtualAddresses) - 1; iNdEx >= 0; iNdEx-- {
			{
				size, err := m.VirtualAddresses[iNdEx].MarshalToSizedBuffer(dAtA[:i])
				if err != nil {
					return 0, err
				}
				i -= size
				i = encodeVarintPublicCustomapi(dAtA, i, uint64(size))
			}
			i--
			dAtA[i] = 0xa
		}
	}
	return len(dAtA) - i, nil
}

func encodeVarintPublicCustomapi(dAtA []byte, offset int, v uint64) int {
	offset -= sovPublicCustomapi(v)
	base := offset
	for v >= 1<<7 {
		dAtA[offset] = uint8(v&0x7f | 0x80)
		v >>= 7
		offset++
	}
	dAtA[offset] = uint8(v)
	return base
}
func (m *GetAssociatedObjectsRequest) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	l = len(m.Namespace)
	if l > 0 {
		n += 1 + l + sovPublicCustomapi(uint64(l))
	}
	l = len(m.Name)
	if l > 0 {
		n += 1 + l + sovPublicCustomapi(uint64(l))
	}
	return n
}

func (m *GetAssociatedObjectsResponse) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	if len(m.VirtualAddresses) > 0 {
		for _, e := range m.VirtualAddresses {
			l = e.Size()
			n += 1 + l + sovPublicCustomapi(uint64(l))
		}
	}
	if len(m.Irules) > 0 {
		for _, e := range m.Irules {
			l = e.Size()
			n += 1 + l + sovPublicCustomapi(uint64(l))
		}
	}
	if len(m.TrafficPolicies) > 0 {
		for _, e := range m.TrafficPolicies {
			l = e.Size()
			n += 1 + l + sovPublicCustomapi(uint64(l))
		}
	}
	return n
}

func sovPublicCustomapi(x uint64) (n int) {
	return (math_bits.Len64(x|1) + 6) / 7
}
func sozPublicCustomapi(x uint64) (n int) {
	return sovPublicCustomapi(uint64((x << 1) ^ uint64((int64(x) >> 63))))
}
func (this *GetAssociatedObjectsRequest) String() string {
	if this == nil {
		return "nil"
	}
	s := strings.Join([]string{`&GetAssociatedObjectsRequest{`,
		`Namespace:` + fmt.Sprintf("%v", this.Namespace) + `,`,
		`Name:` + fmt.Sprintf("%v", this.Name) + `,`,
		`}`,
	}, "")
	return s
}
func (this *GetAssociatedObjectsResponse) String() string {
	if this == nil {
		return "nil"
	}
	repeatedStringForVirtualAddresses := "[]*Object{"
	for _, f := range this.VirtualAddresses {
		repeatedStringForVirtualAddresses += strings.Replace(fmt.Sprintf("%v", f), "Object", "virtual_address.Object", 1) + ","
	}
	repeatedStringForVirtualAddresses += "}"
	repeatedStringForIrules := "[]*Object{"
	for _, f := range this.Irules {
		repeatedStringForIrules += strings.Replace(fmt.Sprintf("%v", f), "Object", "irule.Object", 1) + ","
	}
	repeatedStringForIrules += "}"
	repeatedStringForTrafficPolicies := "[]*Object{"
	for _, f := range this.TrafficPolicies {
		repeatedStringForTrafficPolicies += strings.Replace(fmt.Sprintf("%v", f), "Object", "traffic_policy.Object", 1) + ","
	}
	repeatedStringForTrafficPolicies += "}"
	s := strings.Join([]string{`&GetAssociatedObjectsResponse{`,
		`VirtualAddresses:` + repeatedStringForVirtualAddresses + `,`,
		`Irules:` + repeatedStringForIrules + `,`,
		`TrafficPolicies:` + repeatedStringForTrafficPolicies + `,`,
		`}`,
	}, "")
	return s
}
func valueToStringPublicCustomapi(v interface{}) string {
	rv := reflect.ValueOf(v)
	if rv.IsNil() {
		return "nil"
	}
	pv := reflect.Indirect(rv).Interface()
	return fmt.Sprintf("*%v", pv)
}
func (m *GetAssociatedObjectsRequest) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowPublicCustomapi
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: GetAssociatedObjectsRequest: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: GetAssociatedObjectsRequest: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Namespace", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowPublicCustomapi
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthPublicCustomapi
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthPublicCustomapi
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.Namespace = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		case 2:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Name", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowPublicCustomapi
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthPublicCustomapi
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthPublicCustomapi
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.Name = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		default:
			iNdEx = preIndex
			skippy, err := skipPublicCustomapi(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if skippy < 0 {
				return ErrInvalidLengthPublicCustomapi
			}
			if (iNdEx + skippy) < 0 {
				return ErrInvalidLengthPublicCustomapi
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func (m *GetAssociatedObjectsResponse) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowPublicCustomapi
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: GetAssociatedObjectsResponse: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: GetAssociatedObjectsResponse: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field VirtualAddresses", wireType)
			}
			var msglen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowPublicCustomapi
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				msglen |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if msglen < 0 {
				return ErrInvalidLengthPublicCustomapi
			}
			postIndex := iNdEx + msglen
			if postIndex < 0 {
				return ErrInvalidLengthPublicCustomapi
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.VirtualAddresses = append(m.VirtualAddresses, &virtual_address.Object{})
			if err := m.VirtualAddresses[len(m.VirtualAddresses)-1].Unmarshal(dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			iNdEx = postIndex
		case 2:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Irules", wireType)
			}
			var msglen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowPublicCustomapi
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				msglen |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if msglen < 0 {
				return ErrInvalidLengthPublicCustomapi
			}
			postIndex := iNdEx + msglen
			if postIndex < 0 {
				return ErrInvalidLengthPublicCustomapi
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.Irules = append(m.Irules, &irule.Object{})
			if err := m.Irules[len(m.Irules)-1].Unmarshal(dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			iNdEx = postIndex
		case 3:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field TrafficPolicies", wireType)
			}
			var msglen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowPublicCustomapi
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				msglen |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if msglen < 0 {
				return ErrInvalidLengthPublicCustomapi
			}
			postIndex := iNdEx + msglen
			if postIndex < 0 {
				return ErrInvalidLengthPublicCustomapi
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.TrafficPolicies = append(m.TrafficPolicies, &traffic_policy.Object{})
			if err := m.TrafficPolicies[len(m.TrafficPolicies)-1].Unmarshal(dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			iNdEx = postIndex
		default:
			iNdEx = preIndex
			skippy, err := skipPublicCustomapi(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if skippy < 0 {
				return ErrInvalidLengthPublicCustomapi
			}
			if (iNdEx + skippy) < 0 {
				return ErrInvalidLengthPublicCustomapi
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func skipPublicCustomapi(dAtA []byte) (n int, err error) {
	l := len(dAtA)
	iNdEx := 0
	depth := 0
	for iNdEx < l {
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return 0, ErrIntOverflowPublicCustomapi
			}
			if iNdEx >= l {
				return 0, io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= (uint64(b) & 0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		wireType := int(wire & 0x7)
		switch wireType {
		case 0:
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return 0, ErrIntOverflowPublicCustomapi
				}
				if iNdEx >= l {
					return 0, io.ErrUnexpectedEOF
				}
				iNdEx++
				if dAtA[iNdEx-1] < 0x80 {
					break
				}
			}
		case 1:
			iNdEx += 8
		case 2:
			var length int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return 0, ErrIntOverflowPublicCustomapi
				}
				if iNdEx >= l {
					return 0, io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				length |= (int(b) & 0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if length < 0 {
				return 0, ErrInvalidLengthPublicCustomapi
			}
			iNdEx += length
		case 3:
			depth++
		case 4:
			if depth == 0 {
				return 0, ErrUnexpectedEndOfGroupPublicCustomapi
			}
			depth--
		case 5:
			iNdEx += 4
		default:
			return 0, fmt.Errorf("proto: illegal wireType %d", wireType)
		}
		if iNdEx < 0 {
			return 0, ErrInvalidLengthPublicCustomapi
		}
		if depth == 0 {
			return iNdEx, nil
		}
	}
	return 0, io.ErrUnexpectedEOF
}

var (
	ErrInvalidLengthPublicCustomapi        = fmt.Errorf("proto: negative length found during unmarshaling")
	ErrIntOverflowPublicCustomapi          = fmt.Errorf("proto: integer overflow")
	ErrUnexpectedEndOfGroupPublicCustomapi = fmt.Errorf("proto: unexpected end of group")
)
