// Code generated by protoc-gen-gogo. DO NOT EDIT.
// source: ves.io/schema/app_security/public_threat_campaign_api.proto

// Application Security Monitoring APIs
//
// x-displayName: "Application Security Monitoring APIs"

package app_security

import (
	context "context"
	fmt "fmt"
	_ "github.com/gogo/googleapis/google/api"
	_ "github.com/gogo/protobuf/gogoproto"
	proto "github.com/gogo/protobuf/proto"
	golang_proto "github.com/golang/protobuf/proto"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
	_ "github.com/volterraedge/terraform-provider-volterra/pbgo/extschema/schema"
	_ "github.com/volterraedge/terraform-provider-volterra/pbgo/extschema/schema/vesenv"
	io "io"
	math "math"
	math_bits "math/bits"
	reflect "reflect"
	strings "strings"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = golang_proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.GoGoProtoPackageIsVersion3 // please upgrade the proto package

// ThreatCampaignRequest
//
// x-displayName: "ThreatCampaignRequest"
// IdRequest would be incoming request for the threat campaign with the given ID.
type ThreatCampaignRequest struct {
	// id
	//
	// x-displayName: "Threat Campaign ID"
	// x-example: "cmp5641a5adbeabaf2708ce7663ad937df8"
	// x-required
	// Id with which the request will find entry.
	Id string `protobuf:"bytes,2,opt,name=id,proto3" json:"id,omitempty"`
}

func (m *ThreatCampaignRequest) Reset()      { *m = ThreatCampaignRequest{} }
func (*ThreatCampaignRequest) ProtoMessage() {}
func (*ThreatCampaignRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_058f990be476f057, []int{0}
}
func (m *ThreatCampaignRequest) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *ThreatCampaignRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_ThreatCampaignRequest.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *ThreatCampaignRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ThreatCampaignRequest.Merge(m, src)
}
func (m *ThreatCampaignRequest) XXX_Size() int {
	return m.Size()
}
func (m *ThreatCampaignRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_ThreatCampaignRequest.DiscardUnknown(m)
}

var xxx_messageInfo_ThreatCampaignRequest proto.InternalMessageInfo

func (m *ThreatCampaignRequest) GetId() string {
	if m != nil {
		return m.Id
	}
	return ""
}

// Threat Campaign
//
// x-displayName: "Threat Campaign"
// Threat Campaign object representing the created threat campaign.
type ThreatCampaign struct {
	// id
	//
	// x-displayName: "ID"
	// x-example: "cmp5641a5adbeabaf2708ce7663ad937df8"
	// x-required
	// The Threat Campaign ID
	Id string `protobuf:"bytes,11,opt,name=id,proto3" json:"id,omitempty"`
	// name
	//
	// x-displayName: "Name"
	// x-example: "Drupal 'Drupalgeddon2' RCE - exec48ne"
	// x-required
	// The Threat Campaign Name
	Name string `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	// attack_type
	//
	// x-displayName: "Attack Type"
	// x-example: "Server Side Code Injection"
	// The Threat Campaign Attack Type
	AttackType string `protobuf:"bytes,3,opt,name=attack_type,json=attackType,proto3" json:"attack_type,omitempty"`
	// intent
	//
	// x-displayName: "Intent"
	// x-example: "Malware Spreading - Crypto Currency Miner"
	// The Threat Campaign Intent
	Intent string `protobuf:"bytes,4,opt,name=intent,proto3" json:"intent,omitempty"`
	// risk
	//
	// x-displayName: "Risk"
	// x-example: "High"
	// x-required
	// The Threat Campaign Risk
	Risk string `protobuf:"bytes,5,opt,name=risk,proto3" json:"risk,omitempty"`
	// malwares
	//
	// x-displayName: "Malwares"
	// x-example: "['Cryptocurrency Miner']"
	// x-required
	// The Threat Campaign Malwares
	Malwares []string `protobuf:"bytes,6,rep,name=malwares,proto3" json:"malwares,omitempty"`
	// systems
	//
	// x-displayName: "Systems"
	// x-example: "['PHP', 'Unix/Linux']"
	// x-required
	// The Threat Campaign Systems
	Systems []string `protobuf:"bytes,7,rep,name=systems,proto3" json:"systems,omitempty"`
	// description
	//
	// x-displayName: "Description"
	// x-example: "This campaign aims to identify Drupal web servers vulnerable to Drupalgeddon2 RCE vulnerability (CVE-2018-7600). The threat actor instructs the server to download and execute a cryptocurrency miner.   The same threat actor was previously detected exploiting Drupal REST Module RCE vulnerability (CVE-2019-6340)."
	// The Threat Campaign Description
	Description string `protobuf:"bytes,8,opt,name=description,proto3" json:"description,omitempty"`
	// references
	//
	// x-displayName: "References"
	// x-example: "['CVE-2018-7600']"
	// The Threat Campaign References
	References []string `protobuf:"bytes,9,rep,name=references,proto3" json:"references,omitempty"`
	// last_update
	//
	// x-displayName: "Last Update"
	// x-example: "2022/11/29 20:19:17"
	// x-required
	// The Threat Campaign last update time
	LastUpdate string `protobuf:"bytes,10,opt,name=last_update,json=lastUpdate,proto3" json:"last_update,omitempty"`
}

func (m *ThreatCampaign) Reset()      { *m = ThreatCampaign{} }
func (*ThreatCampaign) ProtoMessage() {}
func (*ThreatCampaign) Descriptor() ([]byte, []int) {
	return fileDescriptor_058f990be476f057, []int{1}
}
func (m *ThreatCampaign) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *ThreatCampaign) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_ThreatCampaign.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *ThreatCampaign) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ThreatCampaign.Merge(m, src)
}
func (m *ThreatCampaign) XXX_Size() int {
	return m.Size()
}
func (m *ThreatCampaign) XXX_DiscardUnknown() {
	xxx_messageInfo_ThreatCampaign.DiscardUnknown(m)
}

var xxx_messageInfo_ThreatCampaign proto.InternalMessageInfo

func (m *ThreatCampaign) GetId() string {
	if m != nil {
		return m.Id
	}
	return ""
}

func (m *ThreatCampaign) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

func (m *ThreatCampaign) GetAttackType() string {
	if m != nil {
		return m.AttackType
	}
	return ""
}

func (m *ThreatCampaign) GetIntent() string {
	if m != nil {
		return m.Intent
	}
	return ""
}

func (m *ThreatCampaign) GetRisk() string {
	if m != nil {
		return m.Risk
	}
	return ""
}

func (m *ThreatCampaign) GetMalwares() []string {
	if m != nil {
		return m.Malwares
	}
	return nil
}

func (m *ThreatCampaign) GetSystems() []string {
	if m != nil {
		return m.Systems
	}
	return nil
}

func (m *ThreatCampaign) GetDescription() string {
	if m != nil {
		return m.Description
	}
	return ""
}

func (m *ThreatCampaign) GetReferences() []string {
	if m != nil {
		return m.References
	}
	return nil
}

func (m *ThreatCampaign) GetLastUpdate() string {
	if m != nil {
		return m.LastUpdate
	}
	return ""
}

// ThreatsRequest
//
// x-displayName: "ThreatsRequest"
// Returns threats associated with the given CVE IDs, which can be supplied explicitly or
// derived from a WAF security event.
type ThreatsRequest struct {
	// ThreatsFilter
	//
	// x-displayName: "Threats Filter"
	// x-required
	// Threats filter
	//
	// Types that are valid to be assigned to ThreatsFilter:
	//	*ThreatsRequest_CveIds
	//	*ThreatsRequest_WafSecEventId
	//	*ThreatsRequest_PrimaryTag
	ThreatsFilter isThreatsRequest_ThreatsFilter `protobuf_oneof:"threats_filter"`
	// Cursor
	//
	// x-displayName: "Cursor"
	// x-example: "eyJpZCI6ICJjbnBjNTg0ODg1LWU4YjAtNDQ5ZC05YjA4LWFhYjA4ZDEyZDYifQ=="
	// Opaque pagination cursor returned from previous response
	Cursor string `protobuf:"bytes,4,opt,name=cursor,proto3" json:"cursor,omitempty"`
	// Report Fields
	//
	// x-displayName: "Report Fields"
	// x-example: "['title', 'severity', 'summary']"
	// Optional list of fields to include in threat representation
	ReportFields []string `protobuf:"bytes,5,rep,name=report_fields,json=reportFields,proto3" json:"report_fields,omitempty"`
}

func (m *ThreatsRequest) Reset()      { *m = ThreatsRequest{} }
func (*ThreatsRequest) ProtoMessage() {}
func (*ThreatsRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_058f990be476f057, []int{2}
}
func (m *ThreatsRequest) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *ThreatsRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_ThreatsRequest.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *ThreatsRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ThreatsRequest.Merge(m, src)
}
func (m *ThreatsRequest) XXX_Size() int {
	return m.Size()
}
func (m *ThreatsRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_ThreatsRequest.DiscardUnknown(m)
}

var xxx_messageInfo_ThreatsRequest proto.InternalMessageInfo

type isThreatsRequest_ThreatsFilter interface {
	isThreatsRequest_ThreatsFilter()
	Equal(interface{}) bool
	MarshalTo([]byte) (int, error)
	Size() int
}

type ThreatsRequest_CveIds struct {
	CveIds *CVEIDList `protobuf:"bytes,2,opt,name=cve_ids,json=cveIds,proto3,oneof" json:"cve_ids,omitempty"`
}
type ThreatsRequest_WafSecEventId struct {
	WafSecEventId string `protobuf:"bytes,3,opt,name=waf_sec_event_id,json=wafSecEventId,proto3,oneof" json:"waf_sec_event_id,omitempty"`
}
type ThreatsRequest_PrimaryTag struct {
	PrimaryTag string `protobuf:"bytes,6,opt,name=primary_tag,json=primaryTag,proto3,oneof" json:"primary_tag,omitempty"`
}

func (*ThreatsRequest_CveIds) isThreatsRequest_ThreatsFilter()        {}
func (*ThreatsRequest_WafSecEventId) isThreatsRequest_ThreatsFilter() {}
func (*ThreatsRequest_PrimaryTag) isThreatsRequest_ThreatsFilter()    {}

func (m *ThreatsRequest) GetThreatsFilter() isThreatsRequest_ThreatsFilter {
	if m != nil {
		return m.ThreatsFilter
	}
	return nil
}

func (m *ThreatsRequest) GetCveIds() *CVEIDList {
	if x, ok := m.GetThreatsFilter().(*ThreatsRequest_CveIds); ok {
		return x.CveIds
	}
	return nil
}

func (m *ThreatsRequest) GetWafSecEventId() string {
	if x, ok := m.GetThreatsFilter().(*ThreatsRequest_WafSecEventId); ok {
		return x.WafSecEventId
	}
	return ""
}

func (m *ThreatsRequest) GetPrimaryTag() string {
	if x, ok := m.GetThreatsFilter().(*ThreatsRequest_PrimaryTag); ok {
		return x.PrimaryTag
	}
	return ""
}

func (m *ThreatsRequest) GetCursor() string {
	if m != nil {
		return m.Cursor
	}
	return ""
}

func (m *ThreatsRequest) GetReportFields() []string {
	if m != nil {
		return m.ReportFields
	}
	return nil
}

// XXX_OneofWrappers is for the internal use of the proto package.
func (*ThreatsRequest) XXX_OneofWrappers() []interface{} {
	return []interface{}{
		(*ThreatsRequest_CveIds)(nil),
		(*ThreatsRequest_WafSecEventId)(nil),
		(*ThreatsRequest_PrimaryTag)(nil),
	}
}

// ThreatsResponse
//
// x-displayName: "ThreatsResponse"
// Returns a list of threats tracked by F5 XC Threat Intelligence that match the query.
type ThreatsResponse struct {
	// threats
	//
	// x-displayName: "Threats"
	// A list of threats that match the query.
	Threats []string `protobuf:"bytes,1,rep,name=threats,proto3" json:"threats,omitempty"`
	// Next Cursor
	//
	// x-displayName: "Next Cursor"
	// x-example: "eyJpZCI6ICJjbnBjNTg0ODg1LWU4YjAtNDQ5ZC05YjA4LWFhYjA4ZDEyZDYifQ=="
	// Opaque cursor for fetching next page
	NextCursor string `protobuf:"bytes,2,opt,name=next_cursor,json=nextCursor,proto3" json:"next_cursor,omitempty"`
}

func (m *ThreatsResponse) Reset()      { *m = ThreatsResponse{} }
func (*ThreatsResponse) ProtoMessage() {}
func (*ThreatsResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_058f990be476f057, []int{3}
}
func (m *ThreatsResponse) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *ThreatsResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_ThreatsResponse.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *ThreatsResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ThreatsResponse.Merge(m, src)
}
func (m *ThreatsResponse) XXX_Size() int {
	return m.Size()
}
func (m *ThreatsResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_ThreatsResponse.DiscardUnknown(m)
}

var xxx_messageInfo_ThreatsResponse proto.InternalMessageInfo

func (m *ThreatsResponse) GetThreats() []string {
	if m != nil {
		return m.Threats
	}
	return nil
}

func (m *ThreatsResponse) GetNextCursor() string {
	if m != nil {
		return m.NextCursor
	}
	return ""
}

// CVEIDList
//
// x-displayName: "CVE ID List"
// A list of CVE IDs
type CVEIDList struct {
	// ids
	//
	// x-displayName: "IDs"
	// x-example: "CVE-2021-44228"
	// x-required
	// A list of CVE IDs
	Ids []string `protobuf:"bytes,1,rep,name=ids,proto3" json:"ids,omitempty"`
}

func (m *CVEIDList) Reset()      { *m = CVEIDList{} }
func (*CVEIDList) ProtoMessage() {}
func (*CVEIDList) Descriptor() ([]byte, []int) {
	return fileDescriptor_058f990be476f057, []int{4}
}
func (m *CVEIDList) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *CVEIDList) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_CVEIDList.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *CVEIDList) XXX_Merge(src proto.Message) {
	xxx_messageInfo_CVEIDList.Merge(m, src)
}
func (m *CVEIDList) XXX_Size() int {
	return m.Size()
}
func (m *CVEIDList) XXX_DiscardUnknown() {
	xxx_messageInfo_CVEIDList.DiscardUnknown(m)
}

var xxx_messageInfo_CVEIDList proto.InternalMessageInfo

func (m *CVEIDList) GetIds() []string {
	if m != nil {
		return m.Ids
	}
	return nil
}

func init() {
	proto.RegisterType((*ThreatCampaignRequest)(nil), "ves.io.schema.app_security.ThreatCampaignRequest")
	golang_proto.RegisterType((*ThreatCampaignRequest)(nil), "ves.io.schema.app_security.ThreatCampaignRequest")
	proto.RegisterType((*ThreatCampaign)(nil), "ves.io.schema.app_security.ThreatCampaign")
	golang_proto.RegisterType((*ThreatCampaign)(nil), "ves.io.schema.app_security.ThreatCampaign")
	proto.RegisterType((*ThreatsRequest)(nil), "ves.io.schema.app_security.ThreatsRequest")
	golang_proto.RegisterType((*ThreatsRequest)(nil), "ves.io.schema.app_security.ThreatsRequest")
	proto.RegisterType((*ThreatsResponse)(nil), "ves.io.schema.app_security.ThreatsResponse")
	golang_proto.RegisterType((*ThreatsResponse)(nil), "ves.io.schema.app_security.ThreatsResponse")
	proto.RegisterType((*CVEIDList)(nil), "ves.io.schema.app_security.CVEIDList")
	golang_proto.RegisterType((*CVEIDList)(nil), "ves.io.schema.app_security.CVEIDList")
}

func init() {
	proto.RegisterFile("ves.io/schema/app_security/public_threat_campaign_api.proto", fileDescriptor_058f990be476f057)
}
func init() {
	golang_proto.RegisterFile("ves.io/schema/app_security/public_threat_campaign_api.proto", fileDescriptor_058f990be476f057)
}

var fileDescriptor_058f990be476f057 = []byte{
	// 878 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xa4, 0x55, 0x41, 0x6f, 0x1b, 0x45,
	0x14, 0xf6, 0xac, 0x13, 0x27, 0x1e, 0xd3, 0x34, 0x8c, 0x68, 0xb5, 0x98, 0x68, 0x49, 0x8d, 0x90,
	0x4a, 0x61, 0x77, 0x4b, 0x11, 0x08, 0x81, 0x90, 0x8a, 0x43, 0xa1, 0x46, 0x95, 0xa8, 0x4c, 0xe0,
	0xc0, 0x81, 0xd5, 0x78, 0xf7, 0x79, 0x33, 0xc4, 0xbb, 0x33, 0xcc, 0x8c, 0xed, 0x58, 0x08, 0x09,
	0xf5, 0x84, 0x38, 0x21, 0xf8, 0x03, 0x1c, 0xf9, 0x0d, 0xe4, 0x92, 0x1b, 0x9c, 0x50, 0x04, 0x12,
	0xea, 0x81, 0x03, 0x71, 0x38, 0xc0, 0xad, 0x77, 0x2e, 0x68, 0x66, 0x77, 0xa3, 0x38, 0x2a, 0x55,
	0x24, 0x6e, 0xef, 0x7d, 0xdf, 0xfb, 0x9e, 0xe6, 0x7d, 0xf3, 0x76, 0x16, 0xbf, 0x3e, 0x01, 0x15,
	0x30, 0x1e, 0xaa, 0x78, 0x07, 0x32, 0x1a, 0x52, 0x21, 0x22, 0x05, 0xf1, 0x58, 0x32, 0x3d, 0x0b,
	0xc5, 0x78, 0x30, 0x62, 0x71, 0xa4, 0x77, 0x24, 0x50, 0x1d, 0xc5, 0x34, 0x13, 0x94, 0xa5, 0x79,
	0x44, 0x05, 0x0b, 0x84, 0xe4, 0x9a, 0x93, 0x76, 0x21, 0x0e, 0x0a, 0x71, 0x70, 0x5a, 0xdc, 0xf6,
	0x53, 0xa6, 0x77, 0xc6, 0x83, 0x20, 0xe6, 0x59, 0x98, 0xf2, 0x94, 0x87, 0x56, 0x32, 0x18, 0x0f,
	0x6d, 0x66, 0x13, 0x1b, 0x15, 0xad, 0xda, 0x1b, 0x29, 0xe7, 0xe9, 0x08, 0x42, 0x2a, 0x58, 0x48,
	0xf3, 0x9c, 0x6b, 0xaa, 0x19, 0xcf, 0x55, 0xc9, 0x3e, 0xb5, 0x78, 0x4a, 0x2e, 0x4e, 0x93, 0x1b,
	0x8b, 0xe4, 0x84, 0x8e, 0x58, 0x42, 0x35, 0x94, 0x6c, 0xe7, 0x0c, 0x0b, 0x0a, 0xf2, 0xc9, 0x99,
	0x0e, 0x9b, 0x67, 0x6a, 0x18, 0x4c, 0xa3, 0x85, 0x8a, 0xce, 0xab, 0xf8, 0xd2, 0xb6, 0xb5, 0x61,
	0xab, 0x74, 0xa1, 0x0f, 0x9f, 0x8e, 0x41, 0x69, 0xf2, 0x24, 0x76, 0x58, 0xe2, 0x3a, 0x9b, 0xe8,
	0x6a, 0xb3, 0xdb, 0xfc, 0xe1, 0xef, 0x83, 0xfa, 0x92, 0x74, 0xdc, 0x9b, 0x7d, 0x87, 0x25, 0xef,
	0x2e, 0xad, 0xa2, 0x75, 0xa7, 0xf3, 0x9d, 0x83, 0xd7, 0x16, 0xa5, 0x64, 0xcd, 0x6a, 0x5a, 0x46,
	0x63, 0x0a, 0x09, 0xc1, 0x4b, 0x39, 0xcd, 0xa0, 0xe8, 0xd2, 0xb7, 0x31, 0x79, 0x1a, 0xb7, 0xa8,
	0xd6, 0x34, 0xde, 0x8d, 0xf4, 0x4c, 0x80, 0x5b, 0xb7, 0x14, 0x2e, 0xa0, 0xed, 0x99, 0x00, 0x72,
	0x19, 0x37, 0x58, 0xae, 0x21, 0xd7, 0xee, 0x92, 0xe5, 0xca, 0xcc, 0x34, 0x93, 0x4c, 0xed, 0xba,
	0xcb, 0x45, 0x33, 0x13, 0x93, 0x36, 0x5e, 0xcd, 0xe8, 0x68, 0x4a, 0x25, 0x28, 0xb7, 0xb1, 0x59,
	0xbf, 0xda, 0xec, 0x9f, 0xe4, 0xc4, 0xc5, 0x2b, 0x6a, 0xa6, 0x34, 0x64, 0xca, 0x5d, 0xb1, 0x54,
	0x95, 0x92, 0x4d, 0xdc, 0x4a, 0x40, 0xc5, 0x92, 0x59, 0x27, 0xdc, 0x55, 0xdb, 0xf0, 0x34, 0x44,
	0x3c, 0x8c, 0x25, 0x0c, 0x41, 0x42, 0x1e, 0x83, 0x72, 0x9b, 0x56, 0x7e, 0x0a, 0x31, 0x43, 0x8c,
	0xa8, 0xd2, 0xd1, 0x58, 0x98, 0x0b, 0x71, 0x71, 0x31, 0x84, 0x81, 0x3e, 0xb0, 0x48, 0x69, 0xd1,
	0x3f, 0xa8, 0xb2, 0x48, 0x55, 0xb6, 0xde, 0xc4, 0x2b, 0xf1, 0x04, 0x22, 0x96, 0x28, 0xeb, 0x4a,
	0xeb, 0xc6, 0xb3, 0xc1, 0x7f, 0xef, 0x5a, 0xb0, 0xf5, 0xe1, 0xad, 0xde, 0x5b, 0x77, 0x98, 0xd2,
	0xb7, 0x6b, 0xfd, 0x46, 0x3c, 0x81, 0x5e, 0xa2, 0xc8, 0x73, 0x78, 0x7d, 0x4a, 0x87, 0xa6, 0x26,
	0x82, 0x09, 0xe4, 0x3a, 0x62, 0x49, 0xe1, 0xe2, 0xed, 0x5a, 0xff, 0xc2, 0x94, 0x0e, 0xdf, 0x87,
	0xf8, 0x96, 0xc1, 0x7b, 0x09, 0xb9, 0x82, 0x5b, 0x42, 0xb2, 0x8c, 0xca, 0x59, 0xa4, 0x69, 0xea,
	0x36, 0xca, 0x2a, 0x5c, 0x82, 0xdb, 0x34, 0x35, 0x6e, 0xc7, 0x63, 0xa9, 0xb8, 0xac, 0xdc, 0x2e,
	0x32, 0xf2, 0x0c, 0xbe, 0x20, 0x41, 0x70, 0xa9, 0xa3, 0x21, 0x83, 0x51, 0xa2, 0xdc, 0x65, 0x6b,
	0xc2, 0x63, 0x05, 0xf8, 0xb6, 0xc5, 0xba, 0x97, 0xf1, 0x5a, 0xf1, 0x0d, 0xa9, 0x68, 0xc8, 0x46,
	0x1a, 0x24, 0x59, 0x3a, 0xdc, 0x47, 0xa8, 0x9c, 0xfe, 0x0e, 0xbe, 0x78, 0x32, 0xbc, 0x12, 0x3c,
	0x57, 0x60, 0xee, 0xa4, 0x14, 0xb8, 0xa8, 0xb8, 0x93, 0x32, 0x35, 0x8e, 0xe6, 0xb0, 0xa7, 0xa3,
	0xf2, 0x30, 0xc5, 0xc6, 0x60, 0x03, 0x6d, 0x59, 0xa4, 0xf3, 0x06, 0x6e, 0x9e, 0xb8, 0x41, 0xae,
	0xe3, 0xba, 0x71, 0xd0, 0xf6, 0xe8, 0x7a, 0x66, 0x3b, 0x97, 0xbf, 0x41, 0xce, 0xfa, 0x7a, 0x15,
	0xad, 0xa2, 0x2a, 0x72, 0x51, 0xdf, 0x94, 0xde, 0xf8, 0xbd, 0x8e, 0x1f, 0x5f, 0xdc, 0xd6, 0x37,
	0xef, 0xf6, 0xc8, 0x6f, 0x08, 0x5f, 0x7a, 0x07, 0xf4, 0x22, 0xd1, 0x9d, 0xf5, 0x12, 0xf2, 0xe2,
	0xa3, 0xae, 0xe5, 0xa1, 0x5f, 0x4c, 0xfb, 0xda, 0xf9, 0x25, 0x9d, 0x8f, 0xe7, 0x3f, 0xba, 0xaf,
	0x0c, 0x5f, 0xde, 0x8b, 0xfd, 0x29, 0xa5, 0xc2, 0x57, 0x9a, 0xe6, 0x09, 0x95, 0x89, 0x9f, 0xf1,
	0x9c, 0x69, 0x2e, 0x5f, 0x30, 0x1f, 0xae, 0xcf, 0xb8, 0x2f, 0x24, 0xdf, 0x9b, 0xf9, 0x55, 0x17,
	0x5f, 0x02, 0x4d, 0xee, 0xfd, 0xfa, 0xe7, 0xb7, 0x8e, 0x47, 0x36, 0xca, 0x57, 0x2c, 0x3c, 0xf3,
	0x8a, 0x85, 0x9f, 0xb1, 0xe4, 0x73, 0xb2, 0x8f, 0x30, 0x3e, 0x19, 0x4c, 0x91, 0x73, 0x1c, 0xad,
	0xda, 0xd0, 0xf6, 0xf3, 0xe7, 0xaa, 0x2d, 0x2e, 0xb4, 0xb3, 0xfd, 0x3f, 0xe7, 0x78, 0xa2, 0x73,
	0x71, 0x71, 0x0e, 0xf5, 0x1a, 0xba, 0xd6, 0xbe, 0x7e, 0xb0, 0x8f, 0xea, 0xbf, 0xec, 0xa3, 0x2b,
	0x8f, 0x38, 0xc9, 0x7b, 0x83, 0x4f, 0x20, 0xd6, 0xf7, 0x7e, 0x76, 0xeb, 0x5f, 0x3a, 0xa8, 0xfb,
	0x15, 0x3a, 0x3c, 0xf2, 0x6a, 0xf7, 0x8f, 0xbc, 0xda, 0x83, 0x23, 0x0f, 0x7d, 0x31, 0xf7, 0xd0,
	0xf7, 0x73, 0x0f, 0xfd, 0x34, 0xf7, 0xd0, 0xe1, 0xdc, 0x43, 0x7f, 0xcc, 0x3d, 0xf4, 0xd7, 0xdc,
	0xab, 0x3d, 0x98, 0x7b, 0xe8, 0xeb, 0x63, 0xaf, 0x76, 0x70, 0xec, 0xa1, 0xc3, 0x63, 0xaf, 0x76,
	0xff, 0xd8, 0xab, 0x7d, 0x74, 0x37, 0xe5, 0x62, 0x37, 0x0d, 0x26, 0xdc, 0x2c, 0xb0, 0xa4, 0xc1,
	0x58, 0x85, 0x36, 0x18, 0x72, 0x99, 0x99, 0x73, 0x4f, 0x58, 0x02, 0xd2, 0xaf, 0xe8, 0x50, 0x0c,
	0x52, 0x1e, 0xc2, 0x9e, 0x2e, 0x9f, 0xd4, 0x87, 0xfc, 0x5e, 0x06, 0x0d, 0xfb, 0xb4, 0xbe, 0xf4,
	0x6f, 0x00, 0x00, 0x00, 0xff, 0xff, 0x2b, 0xca, 0x36, 0xcd, 0x83, 0x06, 0x00, 0x00,
}

func (this *ThreatCampaignRequest) Equal(that interface{}) bool {
	if that == nil {
		return this == nil
	}

	that1, ok := that.(*ThreatCampaignRequest)
	if !ok {
		that2, ok := that.(ThreatCampaignRequest)
		if ok {
			that1 = &that2
		} else {
			return false
		}
	}
	if that1 == nil {
		return this == nil
	} else if this == nil {
		return false
	}
	if this.Id != that1.Id {
		return false
	}
	return true
}
func (this *ThreatCampaign) Equal(that interface{}) bool {
	if that == nil {
		return this == nil
	}

	that1, ok := that.(*ThreatCampaign)
	if !ok {
		that2, ok := that.(ThreatCampaign)
		if ok {
			that1 = &that2
		} else {
			return false
		}
	}
	if that1 == nil {
		return this == nil
	} else if this == nil {
		return false
	}
	if this.Id != that1.Id {
		return false
	}
	if this.Name != that1.Name {
		return false
	}
	if this.AttackType != that1.AttackType {
		return false
	}
	if this.Intent != that1.Intent {
		return false
	}
	if this.Risk != that1.Risk {
		return false
	}
	if len(this.Malwares) != len(that1.Malwares) {
		return false
	}
	for i := range this.Malwares {
		if this.Malwares[i] != that1.Malwares[i] {
			return false
		}
	}
	if len(this.Systems) != len(that1.Systems) {
		return false
	}
	for i := range this.Systems {
		if this.Systems[i] != that1.Systems[i] {
			return false
		}
	}
	if this.Description != that1.Description {
		return false
	}
	if len(this.References) != len(that1.References) {
		return false
	}
	for i := range this.References {
		if this.References[i] != that1.References[i] {
			return false
		}
	}
	if this.LastUpdate != that1.LastUpdate {
		return false
	}
	return true
}
func (this *ThreatsRequest) Equal(that interface{}) bool {
	if that == nil {
		return this == nil
	}

	that1, ok := that.(*ThreatsRequest)
	if !ok {
		that2, ok := that.(ThreatsRequest)
		if ok {
			that1 = &that2
		} else {
			return false
		}
	}
	if that1 == nil {
		return this == nil
	} else if this == nil {
		return false
	}
	if that1.ThreatsFilter == nil {
		if this.ThreatsFilter != nil {
			return false
		}
	} else if this.ThreatsFilter == nil {
		return false
	} else if !this.ThreatsFilter.Equal(that1.ThreatsFilter) {
		return false
	}
	if this.Cursor != that1.Cursor {
		return false
	}
	if len(this.ReportFields) != len(that1.ReportFields) {
		return false
	}
	for i := range this.ReportFields {
		if this.ReportFields[i] != that1.ReportFields[i] {
			return false
		}
	}
	return true
}
func (this *ThreatsRequest_CveIds) Equal(that interface{}) bool {
	if that == nil {
		return this == nil
	}

	that1, ok := that.(*ThreatsRequest_CveIds)
	if !ok {
		that2, ok := that.(ThreatsRequest_CveIds)
		if ok {
			that1 = &that2
		} else {
			return false
		}
	}
	if that1 == nil {
		return this == nil
	} else if this == nil {
		return false
	}
	if !this.CveIds.Equal(that1.CveIds) {
		return false
	}
	return true
}
func (this *ThreatsRequest_WafSecEventId) Equal(that interface{}) bool {
	if that == nil {
		return this == nil
	}

	that1, ok := that.(*ThreatsRequest_WafSecEventId)
	if !ok {
		that2, ok := that.(ThreatsRequest_WafSecEventId)
		if ok {
			that1 = &that2
		} else {
			return false
		}
	}
	if that1 == nil {
		return this == nil
	} else if this == nil {
		return false
	}
	if this.WafSecEventId != that1.WafSecEventId {
		return false
	}
	return true
}
func (this *ThreatsRequest_PrimaryTag) Equal(that interface{}) bool {
	if that == nil {
		return this == nil
	}

	that1, ok := that.(*ThreatsRequest_PrimaryTag)
	if !ok {
		that2, ok := that.(ThreatsRequest_PrimaryTag)
		if ok {
			that1 = &that2
		} else {
			return false
		}
	}
	if that1 == nil {
		return this == nil
	} else if this == nil {
		return false
	}
	if this.PrimaryTag != that1.PrimaryTag {
		return false
	}
	return true
}
func (this *ThreatsResponse) Equal(that interface{}) bool {
	if that == nil {
		return this == nil
	}

	that1, ok := that.(*ThreatsResponse)
	if !ok {
		that2, ok := that.(ThreatsResponse)
		if ok {
			that1 = &that2
		} else {
			return false
		}
	}
	if that1 == nil {
		return this == nil
	} else if this == nil {
		return false
	}
	if len(this.Threats) != len(that1.Threats) {
		return false
	}
	for i := range this.Threats {
		if this.Threats[i] != that1.Threats[i] {
			return false
		}
	}
	if this.NextCursor != that1.NextCursor {
		return false
	}
	return true
}
func (this *CVEIDList) Equal(that interface{}) bool {
	if that == nil {
		return this == nil
	}

	that1, ok := that.(*CVEIDList)
	if !ok {
		that2, ok := that.(CVEIDList)
		if ok {
			that1 = &that2
		} else {
			return false
		}
	}
	if that1 == nil {
		return this == nil
	} else if this == nil {
		return false
	}
	if len(this.Ids) != len(that1.Ids) {
		return false
	}
	for i := range this.Ids {
		if this.Ids[i] != that1.Ids[i] {
			return false
		}
	}
	return true
}
func (this *ThreatCampaignRequest) GoString() string {
	if this == nil {
		return "nil"
	}
	s := make([]string, 0, 5)
	s = append(s, "&app_security.ThreatCampaignRequest{")
	s = append(s, "Id: "+fmt.Sprintf("%#v", this.Id)+",\n")
	s = append(s, "}")
	return strings.Join(s, "")
}
func (this *ThreatCampaign) GoString() string {
	if this == nil {
		return "nil"
	}
	s := make([]string, 0, 14)
	s = append(s, "&app_security.ThreatCampaign{")
	s = append(s, "Id: "+fmt.Sprintf("%#v", this.Id)+",\n")
	s = append(s, "Name: "+fmt.Sprintf("%#v", this.Name)+",\n")
	s = append(s, "AttackType: "+fmt.Sprintf("%#v", this.AttackType)+",\n")
	s = append(s, "Intent: "+fmt.Sprintf("%#v", this.Intent)+",\n")
	s = append(s, "Risk: "+fmt.Sprintf("%#v", this.Risk)+",\n")
	s = append(s, "Malwares: "+fmt.Sprintf("%#v", this.Malwares)+",\n")
	s = append(s, "Systems: "+fmt.Sprintf("%#v", this.Systems)+",\n")
	s = append(s, "Description: "+fmt.Sprintf("%#v", this.Description)+",\n")
	s = append(s, "References: "+fmt.Sprintf("%#v", this.References)+",\n")
	s = append(s, "LastUpdate: "+fmt.Sprintf("%#v", this.LastUpdate)+",\n")
	s = append(s, "}")
	return strings.Join(s, "")
}
func (this *ThreatsRequest) GoString() string {
	if this == nil {
		return "nil"
	}
	s := make([]string, 0, 9)
	s = append(s, "&app_security.ThreatsRequest{")
	if this.ThreatsFilter != nil {
		s = append(s, "ThreatsFilter: "+fmt.Sprintf("%#v", this.ThreatsFilter)+",\n")
	}
	s = append(s, "Cursor: "+fmt.Sprintf("%#v", this.Cursor)+",\n")
	s = append(s, "ReportFields: "+fmt.Sprintf("%#v", this.ReportFields)+",\n")
	s = append(s, "}")
	return strings.Join(s, "")
}
func (this *ThreatsRequest_CveIds) GoString() string {
	if this == nil {
		return "nil"
	}
	s := strings.Join([]string{`&app_security.ThreatsRequest_CveIds{` +
		`CveIds:` + fmt.Sprintf("%#v", this.CveIds) + `}`}, ", ")
	return s
}
func (this *ThreatsRequest_WafSecEventId) GoString() string {
	if this == nil {
		return "nil"
	}
	s := strings.Join([]string{`&app_security.ThreatsRequest_WafSecEventId{` +
		`WafSecEventId:` + fmt.Sprintf("%#v", this.WafSecEventId) + `}`}, ", ")
	return s
}
func (this *ThreatsRequest_PrimaryTag) GoString() string {
	if this == nil {
		return "nil"
	}
	s := strings.Join([]string{`&app_security.ThreatsRequest_PrimaryTag{` +
		`PrimaryTag:` + fmt.Sprintf("%#v", this.PrimaryTag) + `}`}, ", ")
	return s
}
func (this *ThreatsResponse) GoString() string {
	if this == nil {
		return "nil"
	}
	s := make([]string, 0, 6)
	s = append(s, "&app_security.ThreatsResponse{")
	s = append(s, "Threats: "+fmt.Sprintf("%#v", this.Threats)+",\n")
	s = append(s, "NextCursor: "+fmt.Sprintf("%#v", this.NextCursor)+",\n")
	s = append(s, "}")
	return strings.Join(s, "")
}
func (this *CVEIDList) GoString() string {
	if this == nil {
		return "nil"
	}
	s := make([]string, 0, 5)
	s = append(s, "&app_security.CVEIDList{")
	s = append(s, "Ids: "+fmt.Sprintf("%#v", this.Ids)+",\n")
	s = append(s, "}")
	return strings.Join(s, "")
}
func valueToGoStringPublicThreatCampaignApi(v interface{}, typ string) string {
	rv := reflect.ValueOf(v)
	if rv.IsNil() {
		return "nil"
	}
	pv := reflect.Indirect(rv).Interface()
	return fmt.Sprintf("func(v %v) *%v { return &v } ( %#v )", typ, typ, pv)
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConn

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion4

// ThreatCampaignAPIClient is the client API for ThreatCampaignAPI service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://godoc.org/google.golang.org/grpc#ClientConn.NewStream.
type ThreatCampaignAPIClient interface {
	// Get Threat Campaign by id
	//
	// x-displayName: "Get Threat Campaign by ID"
	// Get Threat Campaign by ID
	GetThreatCampaignById(ctx context.Context, in *ThreatCampaignRequest, opts ...grpc.CallOption) (*ThreatCampaign, error)
	// Get Threats
	//
	// x-displayName: "Get Threats"
	// Returns a list of threats tracked by F5 XC Threat Intelligence. A threat is a rollup of articles.
	// An article originates from a public web page or blog post discussing a cybersecurity threat campaign,
	// threat actor (or both combined). The public source is fed through a content pipeline to extract
	// threat intelligence information that could be valuable.
	GetThreats(ctx context.Context, in *ThreatsRequest, opts ...grpc.CallOption) (*ThreatsResponse, error)
}

type threatCampaignAPIClient struct {
	cc *grpc.ClientConn
}

func NewThreatCampaignAPIClient(cc *grpc.ClientConn) ThreatCampaignAPIClient {
	return &threatCampaignAPIClient{cc}
}

func (c *threatCampaignAPIClient) GetThreatCampaignById(ctx context.Context, in *ThreatCampaignRequest, opts ...grpc.CallOption) (*ThreatCampaign, error) {
	out := new(ThreatCampaign)
	err := c.cc.Invoke(ctx, "/ves.io.schema.app_security.ThreatCampaignAPI/GetThreatCampaignById", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *threatCampaignAPIClient) GetThreats(ctx context.Context, in *ThreatsRequest, opts ...grpc.CallOption) (*ThreatsResponse, error) {
	out := new(ThreatsResponse)
	err := c.cc.Invoke(ctx, "/ves.io.schema.app_security.ThreatCampaignAPI/GetThreats", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// ThreatCampaignAPIServer is the server API for ThreatCampaignAPI service.
type ThreatCampaignAPIServer interface {
	// Get Threat Campaign by id
	//
	// x-displayName: "Get Threat Campaign by ID"
	// Get Threat Campaign by ID
	GetThreatCampaignById(context.Context, *ThreatCampaignRequest) (*ThreatCampaign, error)
	// Get Threats
	//
	// x-displayName: "Get Threats"
	// Returns a list of threats tracked by F5 XC Threat Intelligence. A threat is a rollup of articles.
	// An article originates from a public web page or blog post discussing a cybersecurity threat campaign,
	// threat actor (or both combined). The public source is fed through a content pipeline to extract
	// threat intelligence information that could be valuable.
	GetThreats(context.Context, *ThreatsRequest) (*ThreatsResponse, error)
}

// UnimplementedThreatCampaignAPIServer can be embedded to have forward compatible implementations.
type UnimplementedThreatCampaignAPIServer struct {
}

func (*UnimplementedThreatCampaignAPIServer) GetThreatCampaignById(ctx context.Context, req *ThreatCampaignRequest) (*ThreatCampaign, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetThreatCampaignById not implemented")
}
func (*UnimplementedThreatCampaignAPIServer) GetThreats(ctx context.Context, req *ThreatsRequest) (*ThreatsResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetThreats not implemented")
}

func RegisterThreatCampaignAPIServer(s *grpc.Server, srv ThreatCampaignAPIServer) {
	s.RegisterService(&_ThreatCampaignAPI_serviceDesc, srv)
}

func _ThreatCampaignAPI_GetThreatCampaignById_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ThreatCampaignRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ThreatCampaignAPIServer).GetThreatCampaignById(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/ves.io.schema.app_security.ThreatCampaignAPI/GetThreatCampaignById",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ThreatCampaignAPIServer).GetThreatCampaignById(ctx, req.(*ThreatCampaignRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _ThreatCampaignAPI_GetThreats_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ThreatsRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ThreatCampaignAPIServer).GetThreats(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/ves.io.schema.app_security.ThreatCampaignAPI/GetThreats",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ThreatCampaignAPIServer).GetThreats(ctx, req.(*ThreatsRequest))
	}
	return interceptor(ctx, in, info, handler)
}

var _ThreatCampaignAPI_serviceDesc = grpc.ServiceDesc{
	ServiceName: "ves.io.schema.app_security.ThreatCampaignAPI",
	HandlerType: (*ThreatCampaignAPIServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "GetThreatCampaignById",
			Handler:    _ThreatCampaignAPI_GetThreatCampaignById_Handler,
		},
		{
			MethodName: "GetThreats",
			Handler:    _ThreatCampaignAPI_GetThreats_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "ves.io/schema/app_security/public_threat_campaign_api.proto",
}

func (m *ThreatCampaignRequest) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *ThreatCampaignRequest) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *ThreatCampaignRequest) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	if len(m.Id) > 0 {
		i -= len(m.Id)
		copy(dAtA[i:], m.Id)
		i = encodeVarintPublicThreatCampaignApi(dAtA, i, uint64(len(m.Id)))
		i--
		dAtA[i] = 0x12
	}
	return len(dAtA) - i, nil
}

func (m *ThreatCampaign) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *ThreatCampaign) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *ThreatCampaign) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	if len(m.Id) > 0 {
		i -= len(m.Id)
		copy(dAtA[i:], m.Id)
		i = encodeVarintPublicThreatCampaignApi(dAtA, i, uint64(len(m.Id)))
		i--
		dAtA[i] = 0x5a
	}
	if len(m.LastUpdate) > 0 {
		i -= len(m.LastUpdate)
		copy(dAtA[i:], m.LastUpdate)
		i = encodeVarintPublicThreatCampaignApi(dAtA, i, uint64(len(m.LastUpdate)))
		i--
		dAtA[i] = 0x52
	}
	if len(m.References) > 0 {
		for iNdEx := len(m.References) - 1; iNdEx >= 0; iNdEx-- {
			i -= len(m.References[iNdEx])
			copy(dAtA[i:], m.References[iNdEx])
			i = encodeVarintPublicThreatCampaignApi(dAtA, i, uint64(len(m.References[iNdEx])))
			i--
			dAtA[i] = 0x4a
		}
	}
	if len(m.Description) > 0 {
		i -= len(m.Description)
		copy(dAtA[i:], m.Description)
		i = encodeVarintPublicThreatCampaignApi(dAtA, i, uint64(len(m.Description)))
		i--
		dAtA[i] = 0x42
	}
	if len(m.Systems) > 0 {
		for iNdEx := len(m.Systems) - 1; iNdEx >= 0; iNdEx-- {
			i -= len(m.Systems[iNdEx])
			copy(dAtA[i:], m.Systems[iNdEx])
			i = encodeVarintPublicThreatCampaignApi(dAtA, i, uint64(len(m.Systems[iNdEx])))
			i--
			dAtA[i] = 0x3a
		}
	}
	if len(m.Malwares) > 0 {
		for iNdEx := len(m.Malwares) - 1; iNdEx >= 0; iNdEx-- {
			i -= len(m.Malwares[iNdEx])
			copy(dAtA[i:], m.Malwares[iNdEx])
			i = encodeVarintPublicThreatCampaignApi(dAtA, i, uint64(len(m.Malwares[iNdEx])))
			i--
			dAtA[i] = 0x32
		}
	}
	if len(m.Risk) > 0 {
		i -= len(m.Risk)
		copy(dAtA[i:], m.Risk)
		i = encodeVarintPublicThreatCampaignApi(dAtA, i, uint64(len(m.Risk)))
		i--
		dAtA[i] = 0x2a
	}
	if len(m.Intent) > 0 {
		i -= len(m.Intent)
		copy(dAtA[i:], m.Intent)
		i = encodeVarintPublicThreatCampaignApi(dAtA, i, uint64(len(m.Intent)))
		i--
		dAtA[i] = 0x22
	}
	if len(m.AttackType) > 0 {
		i -= len(m.AttackType)
		copy(dAtA[i:], m.AttackType)
		i = encodeVarintPublicThreatCampaignApi(dAtA, i, uint64(len(m.AttackType)))
		i--
		dAtA[i] = 0x1a
	}
	if len(m.Name) > 0 {
		i -= len(m.Name)
		copy(dAtA[i:], m.Name)
		i = encodeVarintPublicThreatCampaignApi(dAtA, i, uint64(len(m.Name)))
		i--
		dAtA[i] = 0x12
	}
	return len(dAtA) - i, nil
}

func (m *ThreatsRequest) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *ThreatsRequest) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *ThreatsRequest) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	if m.ThreatsFilter != nil {
		{
			size := m.ThreatsFilter.Size()
			i -= size
			if _, err := m.ThreatsFilter.MarshalTo(dAtA[i:]); err != nil {
				return 0, err
			}
		}
	}
	if len(m.ReportFields) > 0 {
		for iNdEx := len(m.ReportFields) - 1; iNdEx >= 0; iNdEx-- {
			i -= len(m.ReportFields[iNdEx])
			copy(dAtA[i:], m.ReportFields[iNdEx])
			i = encodeVarintPublicThreatCampaignApi(dAtA, i, uint64(len(m.ReportFields[iNdEx])))
			i--
			dAtA[i] = 0x2a
		}
	}
	if len(m.Cursor) > 0 {
		i -= len(m.Cursor)
		copy(dAtA[i:], m.Cursor)
		i = encodeVarintPublicThreatCampaignApi(dAtA, i, uint64(len(m.Cursor)))
		i--
		dAtA[i] = 0x22
	}
	return len(dAtA) - i, nil
}

func (m *ThreatsRequest_CveIds) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *ThreatsRequest_CveIds) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	if m.CveIds != nil {
		{
			size, err := m.CveIds.MarshalToSizedBuffer(dAtA[:i])
			if err != nil {
				return 0, err
			}
			i -= size
			i = encodeVarintPublicThreatCampaignApi(dAtA, i, uint64(size))
		}
		i--
		dAtA[i] = 0x12
	}
	return len(dAtA) - i, nil
}
func (m *ThreatsRequest_WafSecEventId) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *ThreatsRequest_WafSecEventId) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	i -= len(m.WafSecEventId)
	copy(dAtA[i:], m.WafSecEventId)
	i = encodeVarintPublicThreatCampaignApi(dAtA, i, uint64(len(m.WafSecEventId)))
	i--
	dAtA[i] = 0x1a
	return len(dAtA) - i, nil
}
func (m *ThreatsRequest_PrimaryTag) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *ThreatsRequest_PrimaryTag) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	i -= len(m.PrimaryTag)
	copy(dAtA[i:], m.PrimaryTag)
	i = encodeVarintPublicThreatCampaignApi(dAtA, i, uint64(len(m.PrimaryTag)))
	i--
	dAtA[i] = 0x32
	return len(dAtA) - i, nil
}
func (m *ThreatsResponse) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *ThreatsResponse) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *ThreatsResponse) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	if len(m.NextCursor) > 0 {
		i -= len(m.NextCursor)
		copy(dAtA[i:], m.NextCursor)
		i = encodeVarintPublicThreatCampaignApi(dAtA, i, uint64(len(m.NextCursor)))
		i--
		dAtA[i] = 0x12
	}
	if len(m.Threats) > 0 {
		for iNdEx := len(m.Threats) - 1; iNdEx >= 0; iNdEx-- {
			i -= len(m.Threats[iNdEx])
			copy(dAtA[i:], m.Threats[iNdEx])
			i = encodeVarintPublicThreatCampaignApi(dAtA, i, uint64(len(m.Threats[iNdEx])))
			i--
			dAtA[i] = 0xa
		}
	}
	return len(dAtA) - i, nil
}

func (m *CVEIDList) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *CVEIDList) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *CVEIDList) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	if len(m.Ids) > 0 {
		for iNdEx := len(m.Ids) - 1; iNdEx >= 0; iNdEx-- {
			i -= len(m.Ids[iNdEx])
			copy(dAtA[i:], m.Ids[iNdEx])
			i = encodeVarintPublicThreatCampaignApi(dAtA, i, uint64(len(m.Ids[iNdEx])))
			i--
			dAtA[i] = 0xa
		}
	}
	return len(dAtA) - i, nil
}

func encodeVarintPublicThreatCampaignApi(dAtA []byte, offset int, v uint64) int {
	offset -= sovPublicThreatCampaignApi(v)
	base := offset
	for v >= 1<<7 {
		dAtA[offset] = uint8(v&0x7f | 0x80)
		v >>= 7
		offset++
	}
	dAtA[offset] = uint8(v)
	return base
}
func (m *ThreatCampaignRequest) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	l = len(m.Id)
	if l > 0 {
		n += 1 + l + sovPublicThreatCampaignApi(uint64(l))
	}
	return n
}

func (m *ThreatCampaign) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	l = len(m.Name)
	if l > 0 {
		n += 1 + l + sovPublicThreatCampaignApi(uint64(l))
	}
	l = len(m.AttackType)
	if l > 0 {
		n += 1 + l + sovPublicThreatCampaignApi(uint64(l))
	}
	l = len(m.Intent)
	if l > 0 {
		n += 1 + l + sovPublicThreatCampaignApi(uint64(l))
	}
	l = len(m.Risk)
	if l > 0 {
		n += 1 + l + sovPublicThreatCampaignApi(uint64(l))
	}
	if len(m.Malwares) > 0 {
		for _, s := range m.Malwares {
			l = len(s)
			n += 1 + l + sovPublicThreatCampaignApi(uint64(l))
		}
	}
	if len(m.Systems) > 0 {
		for _, s := range m.Systems {
			l = len(s)
			n += 1 + l + sovPublicThreatCampaignApi(uint64(l))
		}
	}
	l = len(m.Description)
	if l > 0 {
		n += 1 + l + sovPublicThreatCampaignApi(uint64(l))
	}
	if len(m.References) > 0 {
		for _, s := range m.References {
			l = len(s)
			n += 1 + l + sovPublicThreatCampaignApi(uint64(l))
		}
	}
	l = len(m.LastUpdate)
	if l > 0 {
		n += 1 + l + sovPublicThreatCampaignApi(uint64(l))
	}
	l = len(m.Id)
	if l > 0 {
		n += 1 + l + sovPublicThreatCampaignApi(uint64(l))
	}
	return n
}

func (m *ThreatsRequest) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	if m.ThreatsFilter != nil {
		n += m.ThreatsFilter.Size()
	}
	l = len(m.Cursor)
	if l > 0 {
		n += 1 + l + sovPublicThreatCampaignApi(uint64(l))
	}
	if len(m.ReportFields) > 0 {
		for _, s := range m.ReportFields {
			l = len(s)
			n += 1 + l + sovPublicThreatCampaignApi(uint64(l))
		}
	}
	return n
}

func (m *ThreatsRequest_CveIds) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	if m.CveIds != nil {
		l = m.CveIds.Size()
		n += 1 + l + sovPublicThreatCampaignApi(uint64(l))
	}
	return n
}
func (m *ThreatsRequest_WafSecEventId) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	l = len(m.WafSecEventId)
	n += 1 + l + sovPublicThreatCampaignApi(uint64(l))
	return n
}
func (m *ThreatsRequest_PrimaryTag) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	l = len(m.PrimaryTag)
	n += 1 + l + sovPublicThreatCampaignApi(uint64(l))
	return n
}
func (m *ThreatsResponse) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	if len(m.Threats) > 0 {
		for _, s := range m.Threats {
			l = len(s)
			n += 1 + l + sovPublicThreatCampaignApi(uint64(l))
		}
	}
	l = len(m.NextCursor)
	if l > 0 {
		n += 1 + l + sovPublicThreatCampaignApi(uint64(l))
	}
	return n
}

func (m *CVEIDList) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	if len(m.Ids) > 0 {
		for _, s := range m.Ids {
			l = len(s)
			n += 1 + l + sovPublicThreatCampaignApi(uint64(l))
		}
	}
	return n
}

func sovPublicThreatCampaignApi(x uint64) (n int) {
	return (math_bits.Len64(x|1) + 6) / 7
}
func sozPublicThreatCampaignApi(x uint64) (n int) {
	return sovPublicThreatCampaignApi(uint64((x << 1) ^ uint64((int64(x) >> 63))))
}
func (this *ThreatCampaignRequest) String() string {
	if this == nil {
		return "nil"
	}
	s := strings.Join([]string{`&ThreatCampaignRequest{`,
		`Id:` + fmt.Sprintf("%v", this.Id) + `,`,
		`}`,
	}, "")
	return s
}
func (this *ThreatCampaign) String() string {
	if this == nil {
		return "nil"
	}
	s := strings.Join([]string{`&ThreatCampaign{`,
		`Name:` + fmt.Sprintf("%v", this.Name) + `,`,
		`AttackType:` + fmt.Sprintf("%v", this.AttackType) + `,`,
		`Intent:` + fmt.Sprintf("%v", this.Intent) + `,`,
		`Risk:` + fmt.Sprintf("%v", this.Risk) + `,`,
		`Malwares:` + fmt.Sprintf("%v", this.Malwares) + `,`,
		`Systems:` + fmt.Sprintf("%v", this.Systems) + `,`,
		`Description:` + fmt.Sprintf("%v", this.Description) + `,`,
		`References:` + fmt.Sprintf("%v", this.References) + `,`,
		`LastUpdate:` + fmt.Sprintf("%v", this.LastUpdate) + `,`,
		`Id:` + fmt.Sprintf("%v", this.Id) + `,`,
		`}`,
	}, "")
	return s
}
func (this *ThreatsRequest) String() string {
	if this == nil {
		return "nil"
	}
	s := strings.Join([]string{`&ThreatsRequest{`,
		`ThreatsFilter:` + fmt.Sprintf("%v", this.ThreatsFilter) + `,`,
		`Cursor:` + fmt.Sprintf("%v", this.Cursor) + `,`,
		`ReportFields:` + fmt.Sprintf("%v", this.ReportFields) + `,`,
		`}`,
	}, "")
	return s
}
func (this *ThreatsRequest_CveIds) String() string {
	if this == nil {
		return "nil"
	}
	s := strings.Join([]string{`&ThreatsRequest_CveIds{`,
		`CveIds:` + strings.Replace(fmt.Sprintf("%v", this.CveIds), "CVEIDList", "CVEIDList", 1) + `,`,
		`}`,
	}, "")
	return s
}
func (this *ThreatsRequest_WafSecEventId) String() string {
	if this == nil {
		return "nil"
	}
	s := strings.Join([]string{`&ThreatsRequest_WafSecEventId{`,
		`WafSecEventId:` + fmt.Sprintf("%v", this.WafSecEventId) + `,`,
		`}`,
	}, "")
	return s
}
func (this *ThreatsRequest_PrimaryTag) String() string {
	if this == nil {
		return "nil"
	}
	s := strings.Join([]string{`&ThreatsRequest_PrimaryTag{`,
		`PrimaryTag:` + fmt.Sprintf("%v", this.PrimaryTag) + `,`,
		`}`,
	}, "")
	return s
}
func (this *ThreatsResponse) String() string {
	if this == nil {
		return "nil"
	}
	s := strings.Join([]string{`&ThreatsResponse{`,
		`Threats:` + fmt.Sprintf("%v", this.Threats) + `,`,
		`NextCursor:` + fmt.Sprintf("%v", this.NextCursor) + `,`,
		`}`,
	}, "")
	return s
}
func (this *CVEIDList) String() string {
	if this == nil {
		return "nil"
	}
	s := strings.Join([]string{`&CVEIDList{`,
		`Ids:` + fmt.Sprintf("%v", this.Ids) + `,`,
		`}`,
	}, "")
	return s
}
func valueToStringPublicThreatCampaignApi(v interface{}) string {
	rv := reflect.ValueOf(v)
	if rv.IsNil() {
		return "nil"
	}
	pv := reflect.Indirect(rv).Interface()
	return fmt.Sprintf("*%v", pv)
}
func (m *ThreatCampaignRequest) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowPublicThreatCampaignApi
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: ThreatCampaignRequest: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: ThreatCampaignRequest: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 2:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Id", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowPublicThreatCampaignApi
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthPublicThreatCampaignApi
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthPublicThreatCampaignApi
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.Id = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		default:
			iNdEx = preIndex
			skippy, err := skipPublicThreatCampaignApi(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if skippy < 0 {
				return ErrInvalidLengthPublicThreatCampaignApi
			}
			if (iNdEx + skippy) < 0 {
				return ErrInvalidLengthPublicThreatCampaignApi
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func (m *ThreatCampaign) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowPublicThreatCampaignApi
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: ThreatCampaign: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: ThreatCampaign: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 2:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Name", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowPublicThreatCampaignApi
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthPublicThreatCampaignApi
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthPublicThreatCampaignApi
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.Name = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		case 3:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field AttackType", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowPublicThreatCampaignApi
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthPublicThreatCampaignApi
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthPublicThreatCampaignApi
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.AttackType = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		case 4:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Intent", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowPublicThreatCampaignApi
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthPublicThreatCampaignApi
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthPublicThreatCampaignApi
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.Intent = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		case 5:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Risk", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowPublicThreatCampaignApi
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthPublicThreatCampaignApi
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthPublicThreatCampaignApi
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.Risk = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		case 6:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Malwares", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowPublicThreatCampaignApi
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthPublicThreatCampaignApi
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthPublicThreatCampaignApi
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.Malwares = append(m.Malwares, string(dAtA[iNdEx:postIndex]))
			iNdEx = postIndex
		case 7:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Systems", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowPublicThreatCampaignApi
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthPublicThreatCampaignApi
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthPublicThreatCampaignApi
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.Systems = append(m.Systems, string(dAtA[iNdEx:postIndex]))
			iNdEx = postIndex
		case 8:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Description", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowPublicThreatCampaignApi
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthPublicThreatCampaignApi
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthPublicThreatCampaignApi
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.Description = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		case 9:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field References", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowPublicThreatCampaignApi
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthPublicThreatCampaignApi
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthPublicThreatCampaignApi
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.References = append(m.References, string(dAtA[iNdEx:postIndex]))
			iNdEx = postIndex
		case 10:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field LastUpdate", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowPublicThreatCampaignApi
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthPublicThreatCampaignApi
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthPublicThreatCampaignApi
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.LastUpdate = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		case 11:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Id", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowPublicThreatCampaignApi
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthPublicThreatCampaignApi
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthPublicThreatCampaignApi
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.Id = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		default:
			iNdEx = preIndex
			skippy, err := skipPublicThreatCampaignApi(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if skippy < 0 {
				return ErrInvalidLengthPublicThreatCampaignApi
			}
			if (iNdEx + skippy) < 0 {
				return ErrInvalidLengthPublicThreatCampaignApi
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func (m *ThreatsRequest) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowPublicThreatCampaignApi
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: ThreatsRequest: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: ThreatsRequest: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 2:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field CveIds", wireType)
			}
			var msglen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowPublicThreatCampaignApi
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				msglen |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if msglen < 0 {
				return ErrInvalidLengthPublicThreatCampaignApi
			}
			postIndex := iNdEx + msglen
			if postIndex < 0 {
				return ErrInvalidLengthPublicThreatCampaignApi
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			v := &CVEIDList{}
			if err := v.Unmarshal(dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			m.ThreatsFilter = &ThreatsRequest_CveIds{v}
			iNdEx = postIndex
		case 3:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field WafSecEventId", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowPublicThreatCampaignApi
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthPublicThreatCampaignApi
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthPublicThreatCampaignApi
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.ThreatsFilter = &ThreatsRequest_WafSecEventId{string(dAtA[iNdEx:postIndex])}
			iNdEx = postIndex
		case 4:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Cursor", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowPublicThreatCampaignApi
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthPublicThreatCampaignApi
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthPublicThreatCampaignApi
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.Cursor = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		case 5:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field ReportFields", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowPublicThreatCampaignApi
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthPublicThreatCampaignApi
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthPublicThreatCampaignApi
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.ReportFields = append(m.ReportFields, string(dAtA[iNdEx:postIndex]))
			iNdEx = postIndex
		case 6:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field PrimaryTag", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowPublicThreatCampaignApi
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthPublicThreatCampaignApi
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthPublicThreatCampaignApi
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.ThreatsFilter = &ThreatsRequest_PrimaryTag{string(dAtA[iNdEx:postIndex])}
			iNdEx = postIndex
		default:
			iNdEx = preIndex
			skippy, err := skipPublicThreatCampaignApi(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if skippy < 0 {
				return ErrInvalidLengthPublicThreatCampaignApi
			}
			if (iNdEx + skippy) < 0 {
				return ErrInvalidLengthPublicThreatCampaignApi
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func (m *ThreatsResponse) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowPublicThreatCampaignApi
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: ThreatsResponse: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: ThreatsResponse: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Threats", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowPublicThreatCampaignApi
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthPublicThreatCampaignApi
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthPublicThreatCampaignApi
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.Threats = append(m.Threats, string(dAtA[iNdEx:postIndex]))
			iNdEx = postIndex
		case 2:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field NextCursor", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowPublicThreatCampaignApi
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthPublicThreatCampaignApi
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthPublicThreatCampaignApi
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.NextCursor = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		default:
			iNdEx = preIndex
			skippy, err := skipPublicThreatCampaignApi(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if skippy < 0 {
				return ErrInvalidLengthPublicThreatCampaignApi
			}
			if (iNdEx + skippy) < 0 {
				return ErrInvalidLengthPublicThreatCampaignApi
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func (m *CVEIDList) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowPublicThreatCampaignApi
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: CVEIDList: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: CVEIDList: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Ids", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowPublicThreatCampaignApi
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthPublicThreatCampaignApi
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthPublicThreatCampaignApi
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.Ids = append(m.Ids, string(dAtA[iNdEx:postIndex]))
			iNdEx = postIndex
		default:
			iNdEx = preIndex
			skippy, err := skipPublicThreatCampaignApi(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if skippy < 0 {
				return ErrInvalidLengthPublicThreatCampaignApi
			}
			if (iNdEx + skippy) < 0 {
				return ErrInvalidLengthPublicThreatCampaignApi
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func skipPublicThreatCampaignApi(dAtA []byte) (n int, err error) {
	l := len(dAtA)
	iNdEx := 0
	depth := 0
	for iNdEx < l {
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return 0, ErrIntOverflowPublicThreatCampaignApi
			}
			if iNdEx >= l {
				return 0, io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= (uint64(b) & 0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		wireType := int(wire & 0x7)
		switch wireType {
		case 0:
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return 0, ErrIntOverflowPublicThreatCampaignApi
				}
				if iNdEx >= l {
					return 0, io.ErrUnexpectedEOF
				}
				iNdEx++
				if dAtA[iNdEx-1] < 0x80 {
					break
				}
			}
		case 1:
			iNdEx += 8
		case 2:
			var length int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return 0, ErrIntOverflowPublicThreatCampaignApi
				}
				if iNdEx >= l {
					return 0, io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				length |= (int(b) & 0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if length < 0 {
				return 0, ErrInvalidLengthPublicThreatCampaignApi
			}
			iNdEx += length
		case 3:
			depth++
		case 4:
			if depth == 0 {
				return 0, ErrUnexpectedEndOfGroupPublicThreatCampaignApi
			}
			depth--
		case 5:
			iNdEx += 4
		default:
			return 0, fmt.Errorf("proto: illegal wireType %d", wireType)
		}
		if iNdEx < 0 {
			return 0, ErrInvalidLengthPublicThreatCampaignApi
		}
		if depth == 0 {
			return iNdEx, nil
		}
	}
	return 0, io.ErrUnexpectedEOF
}

var (
	ErrInvalidLengthPublicThreatCampaignApi        = fmt.Errorf("proto: negative length found during unmarshaling")
	ErrIntOverflowPublicThreatCampaignApi          = fmt.Errorf("proto: integer overflow")
	ErrUnexpectedEndOfGroupPublicThreatCampaignApi = fmt.Errorf("proto: unexpected end of group")
)
