// Code generated by protoc-gen-gogo. DO NOT EDIT.
// source: ves.io/schema/shape/bot_defense/bot_network_policy/types.proto

package bot_network_policy

import (
	fmt "fmt"
	_ "github.com/gogo/protobuf/gogoproto"
	proto "github.com/gogo/protobuf/proto"
	_ "github.com/gogo/protobuf/types"
	golang_proto "github.com/golang/protobuf/proto"
	_ "github.com/volterraedge/terraform-provider-volterra/pbgo/extschema/schema"
	bot_defense "github.com/volterraedge/terraform-provider-volterra/pbgo/extschema/schema/shape/bot_defense"
	_ "github.com/volterraedge/terraform-provider-volterra/pbgo/extschema/schema/shape/bot_defense/bot_policy_version"
	views "github.com/volterraedge/terraform-provider-volterra/pbgo/extschema/schema/views"
	io "io"
	math "math"
	math_bits "math/bits"
	reflect "reflect"
	strings "strings"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = golang_proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.GoGoProtoPackageIsVersion3 // please upgrade the proto package

// GlobalSpecType
//
// x-displayName: "Global Specification"
// Configures Bot network Policy
type GlobalSpecType struct {
	// network_policy_version
	//
	// x-displayName: "network Policy Version"
	// The list of references to network Policy Version
	// The network policy includes multiple network policy versions
	NetworkPolicyVersion []*views.ObjectRefType `protobuf:"bytes,1,rep,name=network_policy_version,json=networkPolicyVersion,proto3" json:"network_policy_version,omitempty"`
	// The latest version number for this policy
	//
	// x-displayName: "Version"
	LatestVersion string `protobuf:"bytes,2,opt,name=latest_version,json=latestVersion,proto3" json:"latest_version,omitempty"`
	// Last Modified By
	//
	// x-displayName: "Last Modified By"
	// x-example: "[Services] F5 or user@email.com"
	// Last Modified By the user email
	UpdateUser string `protobuf:"bytes,4,opt,name=update_user,json=updateUser,proto3" json:"update_user,omitempty"`
	//SPM Policy ID
	//
	// x-displayName: "SPM Policy ID"
	// x-example: "12344567"
	// Policy ID in SPM server
	SpmPolicyId string `protobuf:"bytes,7,opt,name=spm_policy_id,json=spmPolicyId,proto3" json:"spm_policy_id,omitempty"`
	//PC-Graph Policy ID for Latest Published Policy Version
	//
	// x-displayName: "PC-Graph Policy ID for Latest Published Policy Version"
	// Policy ID in PC-Graph server
	// This PC-Graph policy ID is for the latest published policy version (v1.0, v2.0...).
	PcGraphLatestVersionPolicyId string `protobuf:"bytes,8,opt,name=pc_graph_latest_version_policy_id,json=pcGraphLatestVersionPolicyId,proto3" json:"pc_graph_latest_version_policy_id,omitempty"`
	//Policy Comments
	//
	// x-displayName: "Comments"
	// x-example: "This is comment"
	// Policy Comments from user
	Comments string `protobuf:"bytes,9,opt,name=comments,proto3" json:"comments,omitempty"`
	// Bot Infrastructure with in-use version
	//
	// x-displayName: "Bot Infrastructures with in-use policy version"
	// The list of Bot Infra Name with its in use policy version
	BotInfrasWithVersion []*bot_defense.BotInfraWithVersion `protobuf:"bytes,10,rep,name=bot_infras_with_version,json=botInfrasWithVersion,proto3" json:"bot_infras_with_version,omitempty"`
	// Network policy content
	//
	// x-displayName: "Routing"
	// Network Policy Content
	NetworkPolicyContent *bot_defense.NetworkPolicyContent `protobuf:"bytes,11,opt,name=network_policy_content,json=networkPolicyContent,proto3" json:"network_policy_content,omitempty"`
	//PC-Graph Policy ID for Draft Policy Version
	//
	// x-displayName: "PC-Graph Policy ID for Draft Policy Version"
	// Draft Policy ID in PC-Graph server
	// This PC-Graph draft policy ID is for the draft policy version (Draft base v1.0, Draft base v2.0...)".
	PcGraphDraftPolicyId string `protobuf:"bytes,12,opt,name=pc_graph_draft_policy_id,json=pcGraphDraftPolicyId,proto3" json:"pc_graph_draft_policy_id,omitempty"`
	// CoSSE Bot Infrastructure with Delivered Version
	//
	// x-displayName: "CoSSE Bot Infrastructure with Delivered Policy Version"
	// The list of CoSSE Bot Infra Name with its delivered policy version
	CosseBotInfrasWithDeliveredVersion []*bot_defense.CosseBotInfraWithDeliveredVersion `protobuf:"bytes,13,rep,name=cosse_bot_infras_with_delivered_version,json=cosseBotInfrasWithDeliveredVersion,proto3" json:"cosse_bot_infras_with_delivered_version,omitempty"`
	// Used for CoSSE Policy
	//
	// x-displayName: "Used for CoSSE Policy"
	// x-example: "false"
	// Used for CoSSE Policy
	UsedForCosse bool `protobuf:"varint,14,opt,name=used_for_cosse,json=usedForCosse,proto3" json:"used_for_cosse,omitempty"`
}

func (m *GlobalSpecType) Reset()      { *m = GlobalSpecType{} }
func (*GlobalSpecType) ProtoMessage() {}
func (*GlobalSpecType) Descriptor() ([]byte, []int) {
	return fileDescriptor_094a873eb8cc7794, []int{0}
}
func (m *GlobalSpecType) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *GlobalSpecType) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	b = b[:cap(b)]
	n, err := m.MarshalToSizedBuffer(b)
	if err != nil {
		return nil, err
	}
	return b[:n], nil
}
func (m *GlobalSpecType) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GlobalSpecType.Merge(m, src)
}
func (m *GlobalSpecType) XXX_Size() int {
	return m.Size()
}
func (m *GlobalSpecType) XXX_DiscardUnknown() {
	xxx_messageInfo_GlobalSpecType.DiscardUnknown(m)
}

var xxx_messageInfo_GlobalSpecType proto.InternalMessageInfo

func (m *GlobalSpecType) GetNetworkPolicyVersion() []*views.ObjectRefType {
	if m != nil {
		return m.NetworkPolicyVersion
	}
	return nil
}

func (m *GlobalSpecType) GetLatestVersion() string {
	if m != nil {
		return m.LatestVersion
	}
	return ""
}

func (m *GlobalSpecType) GetUpdateUser() string {
	if m != nil {
		return m.UpdateUser
	}
	return ""
}

func (m *GlobalSpecType) GetSpmPolicyId() string {
	if m != nil {
		return m.SpmPolicyId
	}
	return ""
}

func (m *GlobalSpecType) GetPcGraphLatestVersionPolicyId() string {
	if m != nil {
		return m.PcGraphLatestVersionPolicyId
	}
	return ""
}

func (m *GlobalSpecType) GetComments() string {
	if m != nil {
		return m.Comments
	}
	return ""
}

func (m *GlobalSpecType) GetBotInfrasWithVersion() []*bot_defense.BotInfraWithVersion {
	if m != nil {
		return m.BotInfrasWithVersion
	}
	return nil
}

func (m *GlobalSpecType) GetNetworkPolicyContent() *bot_defense.NetworkPolicyContent {
	if m != nil {
		return m.NetworkPolicyContent
	}
	return nil
}

func (m *GlobalSpecType) GetPcGraphDraftPolicyId() string {
	if m != nil {
		return m.PcGraphDraftPolicyId
	}
	return ""
}

func (m *GlobalSpecType) GetCosseBotInfrasWithDeliveredVersion() []*bot_defense.CosseBotInfraWithDeliveredVersion {
	if m != nil {
		return m.CosseBotInfrasWithDeliveredVersion
	}
	return nil
}

func (m *GlobalSpecType) GetUsedForCosse() bool {
	if m != nil {
		return m.UsedForCosse
	}
	return false
}

// Replace Bot network Policy
//
// x-displayName: "Replace Bot network Policy"
// Replace Bot network Policy
type ReplaceSpecType struct {
	LatestVersion        string                            `protobuf:"bytes,2,opt,name=latest_version,json=latestVersion,proto3" json:"latest_version,omitempty"`
	UpdateUser           string                            `protobuf:"bytes,4,opt,name=update_user,json=updateUser,proto3" json:"update_user,omitempty"`
	Comments             string                            `protobuf:"bytes,9,opt,name=comments,proto3" json:"comments,omitempty"`
	NetworkPolicyContent *bot_defense.NetworkPolicyContent `protobuf:"bytes,11,opt,name=network_policy_content,json=networkPolicyContent,proto3" json:"network_policy_content,omitempty"`
	PcGraphDraftPolicyId string                            `protobuf:"bytes,12,opt,name=pc_graph_draft_policy_id,json=pcGraphDraftPolicyId,proto3" json:"pc_graph_draft_policy_id,omitempty"`
}

func (m *ReplaceSpecType) Reset()      { *m = ReplaceSpecType{} }
func (*ReplaceSpecType) ProtoMessage() {}
func (*ReplaceSpecType) Descriptor() ([]byte, []int) {
	return fileDescriptor_094a873eb8cc7794, []int{1}
}
func (m *ReplaceSpecType) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *ReplaceSpecType) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	b = b[:cap(b)]
	n, err := m.MarshalToSizedBuffer(b)
	if err != nil {
		return nil, err
	}
	return b[:n], nil
}
func (m *ReplaceSpecType) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ReplaceSpecType.Merge(m, src)
}
func (m *ReplaceSpecType) XXX_Size() int {
	return m.Size()
}
func (m *ReplaceSpecType) XXX_DiscardUnknown() {
	xxx_messageInfo_ReplaceSpecType.DiscardUnknown(m)
}

var xxx_messageInfo_ReplaceSpecType proto.InternalMessageInfo

func (m *ReplaceSpecType) GetLatestVersion() string {
	if m != nil {
		return m.LatestVersion
	}
	return ""
}

func (m *ReplaceSpecType) GetUpdateUser() string {
	if m != nil {
		return m.UpdateUser
	}
	return ""
}

func (m *ReplaceSpecType) GetComments() string {
	if m != nil {
		return m.Comments
	}
	return ""
}

func (m *ReplaceSpecType) GetNetworkPolicyContent() *bot_defense.NetworkPolicyContent {
	if m != nil {
		return m.NetworkPolicyContent
	}
	return nil
}

func (m *ReplaceSpecType) GetPcGraphDraftPolicyId() string {
	if m != nil {
		return m.PcGraphDraftPolicyId
	}
	return ""
}

// Get Bot network Policy
//
// x-displayName: "Get Bot network Policy"
// Get Bot network Policy
type GetSpecType struct {
	LatestVersion                      string                                           `protobuf:"bytes,2,opt,name=latest_version,json=latestVersion,proto3" json:"latest_version,omitempty"`
	UpdateUser                         string                                           `protobuf:"bytes,4,opt,name=update_user,json=updateUser,proto3" json:"update_user,omitempty"`
	BotInfrasWithVersion               []*bot_defense.BotInfraWithVersion               `protobuf:"bytes,10,rep,name=bot_infras_with_version,json=botInfrasWithVersion,proto3" json:"bot_infras_with_version,omitempty"`
	NetworkPolicyContent               *bot_defense.NetworkPolicyContent                `protobuf:"bytes,11,opt,name=network_policy_content,json=networkPolicyContent,proto3" json:"network_policy_content,omitempty"`
	CosseBotInfrasWithDeliveredVersion []*bot_defense.CosseBotInfraWithDeliveredVersion `protobuf:"bytes,13,rep,name=cosse_bot_infras_with_delivered_version,json=cosseBotInfrasWithDeliveredVersion,proto3" json:"cosse_bot_infras_with_delivered_version,omitempty"`
	UsedForCosse                       bool                                             `protobuf:"varint,14,opt,name=used_for_cosse,json=usedForCosse,proto3" json:"used_for_cosse,omitempty"`
}

func (m *GetSpecType) Reset()      { *m = GetSpecType{} }
func (*GetSpecType) ProtoMessage() {}
func (*GetSpecType) Descriptor() ([]byte, []int) {
	return fileDescriptor_094a873eb8cc7794, []int{2}
}
func (m *GetSpecType) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *GetSpecType) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	b = b[:cap(b)]
	n, err := m.MarshalToSizedBuffer(b)
	if err != nil {
		return nil, err
	}
	return b[:n], nil
}
func (m *GetSpecType) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GetSpecType.Merge(m, src)
}
func (m *GetSpecType) XXX_Size() int {
	return m.Size()
}
func (m *GetSpecType) XXX_DiscardUnknown() {
	xxx_messageInfo_GetSpecType.DiscardUnknown(m)
}

var xxx_messageInfo_GetSpecType proto.InternalMessageInfo

func (m *GetSpecType) GetLatestVersion() string {
	if m != nil {
		return m.LatestVersion
	}
	return ""
}

func (m *GetSpecType) GetUpdateUser() string {
	if m != nil {
		return m.UpdateUser
	}
	return ""
}

func (m *GetSpecType) GetBotInfrasWithVersion() []*bot_defense.BotInfraWithVersion {
	if m != nil {
		return m.BotInfrasWithVersion
	}
	return nil
}

func (m *GetSpecType) GetNetworkPolicyContent() *bot_defense.NetworkPolicyContent {
	if m != nil {
		return m.NetworkPolicyContent
	}
	return nil
}

func (m *GetSpecType) GetCosseBotInfrasWithDeliveredVersion() []*bot_defense.CosseBotInfraWithDeliveredVersion {
	if m != nil {
		return m.CosseBotInfrasWithDeliveredVersion
	}
	return nil
}

func (m *GetSpecType) GetUsedForCosse() bool {
	if m != nil {
		return m.UsedForCosse
	}
	return false
}

func init() {
	proto.RegisterType((*GlobalSpecType)(nil), "ves.io.schema.shape.bot_defense.bot_network_policy.GlobalSpecType")
	golang_proto.RegisterType((*GlobalSpecType)(nil), "ves.io.schema.shape.bot_defense.bot_network_policy.GlobalSpecType")
	proto.RegisterType((*ReplaceSpecType)(nil), "ves.io.schema.shape.bot_defense.bot_network_policy.ReplaceSpecType")
	golang_proto.RegisterType((*ReplaceSpecType)(nil), "ves.io.schema.shape.bot_defense.bot_network_policy.ReplaceSpecType")
	proto.RegisterType((*GetSpecType)(nil), "ves.io.schema.shape.bot_defense.bot_network_policy.GetSpecType")
	golang_proto.RegisterType((*GetSpecType)(nil), "ves.io.schema.shape.bot_defense.bot_network_policy.GetSpecType")
}

func init() {
	proto.RegisterFile("ves.io/schema/shape/bot_defense/bot_network_policy/types.proto", fileDescriptor_094a873eb8cc7794)
}
func init() {
	golang_proto.RegisterFile("ves.io/schema/shape/bot_defense/bot_network_policy/types.proto", fileDescriptor_094a873eb8cc7794)
}

var fileDescriptor_094a873eb8cc7794 = []byte{
	// 878 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xcc, 0x56, 0xcf, 0x6f, 0xe3, 0x44,
	0x14, 0xce, 0xb4, 0xd9, 0x26, 0x3b, 0xd9, 0x66, 0x2b, 0xab, 0x02, 0x6f, 0x59, 0xb9, 0x21, 0xda,
	0x85, 0x68, 0x57, 0xb5, 0xd9, 0xb2, 0x5c, 0xf6, 0x50, 0xa4, 0xec, 0x8a, 0x6a, 0x2b, 0x04, 0x2b,
	0xf3, 0x4b, 0xe2, 0x62, 0x39, 0xf6, 0x8b, 0x63, 0x6a, 0x7b, 0x66, 0x67, 0x26, 0x29, 0x3d, 0x54,
	0xda, 0x3f, 0x01, 0x71, 0xe7, 0x84, 0x84, 0x10, 0x7f, 0x02, 0x7b, 0x59, 0x71, 0x42, 0x9c, 0x7a,
	0x41, 0xca, 0x91, 0x3a, 0x97, 0x22, 0x2e, 0xfd, 0x0b, 0x10, 0xf2, 0xd8, 0x31, 0x76, 0x12, 0xa9,
	0xb9, 0x54, 0x70, 0x1b, 0xcf, 0xfb, 0xbe, 0xf7, 0xe6, 0x7d, 0xf3, 0x3e, 0xdb, 0x78, 0x6f, 0x04,
	0x5c, 0xf7, 0x89, 0xc1, 0x9d, 0x01, 0x84, 0xb6, 0xc1, 0x07, 0x36, 0x05, 0xa3, 0x47, 0x84, 0xe5,
	0x42, 0x1f, 0x22, 0x9e, 0xae, 0x23, 0x10, 0x47, 0x84, 0x1d, 0x5a, 0x94, 0x04, 0xbe, 0x73, 0x6c,
	0x88, 0x63, 0x0a, 0x5c, 0xa7, 0x8c, 0x08, 0xa2, 0xec, 0xa6, 0x7c, 0x3d, 0xe5, 0xeb, 0x92, 0xaf,
	0x17, 0xf8, 0xfa, 0x3c, 0x7f, 0x6b, 0xc7, 0xf3, 0xc5, 0x60, 0xd8, 0xd3, 0x1d, 0x12, 0x1a, 0x1e,
	0xf1, 0x88, 0x21, 0x53, 0xf5, 0x86, 0x7d, 0xf9, 0x24, 0x1f, 0xe4, 0x2a, 0x2d, 0xb1, 0x75, 0xcb,
	0x23, 0xc4, 0x0b, 0xe0, 0x5f, 0x94, 0x1d, 0x1d, 0x67, 0xa1, 0xed, 0xd9, 0x90, 0xf0, 0x43, 0xe0,
	0xc2, 0x0e, 0x69, 0x06, 0x78, 0xa3, 0xdc, 0x1e, 0xa1, 0xc2, 0x27, 0x51, 0x76, 0xf6, 0xad, 0x77,
	0x96, 0xe9, 0x3d, 0x3d, 0x73, 0xc6, 0xd8, 0x5b, 0x9e, 0x61, 0x8d, 0x80, 0x71, 0x9f, 0x44, 0x45,
	0xb5, 0xb6, 0x6e, 0x95, 0xf9, 0xc5, 0xd0, 0xed, 0x72, 0x68, 0x64, 0x07, 0xbe, 0x6b, 0x0b, 0xc8,
	0xa2, 0xad, 0x99, 0xa8, 0x0f, 0x47, 0x56, 0xb9, 0x99, 0xed, 0x79, 0x04, 0x2f, 0x16, 0x68, 0xff,
	0xbd, 0x86, 0x9b, 0xfb, 0x01, 0xe9, 0xd9, 0xc1, 0x27, 0x14, 0x9c, 0x4f, 0x8f, 0x29, 0x28, 0x0c,
	0xbf, 0x56, 0xbe, 0x9a, 0xe9, 0xa1, 0x55, 0xd4, 0x5a, 0xed, 0x34, 0x76, 0xdb, 0x7a, 0xf9, 0x76,
	0x65, 0x52, 0xfd, 0xe3, 0xde, 0x57, 0xe0, 0x08, 0x13, 0xfa, 0x49, 0x8e, 0xae, 0xfa, 0xd3, 0x89,
	0x32, 0xdf, 0xf5, 0xf8, 0x04, 0x99, 0x9b, 0x59, 0xee, 0x67, 0x32, 0xf2, 0x79, 0x1a, 0x50, 0xee,
	0xe2, 0x66, 0x60, 0x0b, 0xe0, 0x22, 0xaf, 0xb5, 0xd2, 0x42, 0x9d, 0xeb, 0xe6, 0x7a, 0xba, 0x3b,
	0x85, 0x6d, 0xe3, 0xc6, 0x90, 0x26, 0x02, 0x58, 0x43, 0x0e, 0x4c, 0xad, 0x4a, 0x0c, 0x4e, 0xb7,
	0x3e, 0xe3, 0xc0, 0x94, 0xfb, 0x78, 0x9d, 0xd3, 0x70, 0x5a, 0xd6, 0x77, 0xd5, 0x5a, 0x02, 0xe9,
	0xd6, 0xc6, 0x27, 0xe8, 0xfc, 0x25, 0x42, 0x66, 0x83, 0xd3, 0x30, 0xad, 0xfc, 0xd4, 0x55, 0x9e,
	0xe1, 0x37, 0xa9, 0x63, 0x79, 0xcc, 0xa6, 0x03, 0xab, 0x5c, 0xbd, 0x90, 0xa0, 0x5e, 0x4e, 0x70,
	0x9b, 0x3a, 0xfb, 0x09, 0xe1, 0xc3, 0xe2, 0xb9, 0xf2, 0x8c, 0x6f, 0xe1, 0xba, 0x43, 0xc2, 0x10,
	0x22, 0xc1, 0xd5, 0xeb, 0x92, 0x88, 0x7f, 0xfe, 0xf3, 0xd5, 0xea, 0x35, 0xb6, 0xaa, 0xbe, 0xd8,
	0x30, 0xf3, 0x98, 0x72, 0x84, 0x5f, 0x4f, 0xd4, 0xf1, 0xa3, 0x3e, 0xb3, 0xb9, 0x75, 0xe4, 0x8b,
	0x41, 0xde, 0x37, 0x96, 0x1a, 0x3f, 0xd4, 0x2f, 0x73, 0x50, 0x97, 0x88, 0xa7, 0x09, 0xfd, 0x0b,
	0x5f, 0x0c, 0xb2, 0x63, 0x64, 0xc5, 0xbe, 0x45, 0x2b, 0x2a, 0x32, 0x37, 0x7b, 0x19, 0x80, 0x17,
	0x10, 0xca, 0xf3, 0xb9, 0xbb, 0x75, 0x48, 0x24, 0x20, 0x12, 0x6a, 0xa3, 0x85, 0x3a, 0x8d, 0xdd,
	0xf7, 0x2e, 0xad, 0xfb, 0x51, 0xf1, 0xfa, 0x1e, 0xa7, 0xe4, 0x6e, 0xf5, 0x22, 0xd1, 0xa6, 0x7c,
	0xb5, 0x59, 0x4c, 0x79, 0x1f, 0xab, 0xb9, 0xca, 0x2e, 0xb3, 0xfb, 0xa2, 0x20, 0xee, 0x8d, 0xb2,
	0xb8, 0x9b, 0x99, 0xb8, 0x4f, 0x12, 0x58, 0x2e, 0xea, 0xf7, 0x08, 0xbf, 0xed, 0x10, 0xce, 0xc1,
	0x9a, 0xd5, 0xcc, 0x85, 0xc0, 0x1f, 0x01, 0x03, 0x37, 0x57, 0x6f, 0x5d, 0xaa, 0xd7, 0xbd, 0xb4,
	0x8b, 0xc7, 0x49, 0xbe, 0xa2, 0x84, 0x4f, 0xa6, 0xa9, 0x16, 0x69, 0xd9, 0x76, 0x8a, 0x70, 0xbe,
	0x08, 0xaf, 0xdc, 0xc1, 0xcd, 0x21, 0x07, 0xd7, 0xea, 0x13, 0x66, 0x49, 0xb8, 0xda, 0x6c, 0xa1,
	0x4e, 0xdd, 0xbc, 0x91, 0xec, 0x7e, 0x40, 0x98, 0xac, 0x78, 0x50, 0xad, 0xaf, 0x6e, 0x54, 0x0f,
	0xaa, 0xf5, 0x6b, 0x1b, 0x6b, 0x07, 0xd5, 0xfa, 0xda, 0x46, 0xad, 0xfd, 0xd7, 0x0a, 0xbe, 0x69,
	0x02, 0x0d, 0x6c, 0x07, 0x72, 0x07, 0xde, 0x5f, 0xec, 0x86, 0x6e, 0x55, 0xaa, 0x34, 0xe3, 0x89,
	0xbb, 0x0b, 0x3c, 0x91, 0x21, 0x8b, 0xce, 0xb8, 0x37, 0x37, 0x9a, 0xcd, 0x04, 0xb3, 0x70, 0x3c,
	0x0f, 0xaf, 0x64, 0x4a, 0xae, 0x68, 0x3e, 0x1e, 0xdd, 0xf9, 0x6d, 0x6f, 0xe6, 0x15, 0xf6, 0xcb,
	0x4b, 0x74, 0x13, 0xaf, 0xe3, 0x9a, 0x49, 0x86, 0xc2, 0x8f, 0x3c, 0x65, 0xe5, 0xc1, 0x83, 0x54,
	0xf3, 0xf6, 0xef, 0x55, 0xdc, 0xd8, 0x07, 0x91, 0x2b, 0xbd, 0xe4, 0x7b, 0x67, 0x49, 0x8d, 0x9f,
	0x5f, 0x8d, 0xad, 0xd3, 0x42, 0xff, 0x1b, 0x43, 0x7f, 0xf7, 0x9f, 0xf8, 0x31, 0x15, 0x61, 0x19,
	0x27, 0xde, 0x5b, 0xec, 0xc4, 0x2c, 0x43, 0xc9, 0x8f, 0x8f, 0x1e, 0x2e, 0x9a, 0x9d, 0x6d, 0xdc,
	0xc4, 0xb5, 0x69, 0x36, 0xb4, 0xdb, 0x41, 0xf3, 0xb3, 0x34, 0xe3, 0xe2, 0xee, 0x0f, 0xe8, 0xf4,
	0x4c, 0xab, 0x8c, 0xcf, 0xb4, 0xca, 0xc5, 0x99, 0x86, 0x5e, 0xc4, 0x1a, 0xfa, 0x31, 0xd6, 0xd0,
	0xaf, 0xb1, 0x86, 0x4e, 0x63, 0x0d, 0x8d, 0x63, 0x0d, 0xfd, 0x11, 0x6b, 0xe8, 0x3c, 0xd6, 0x2a,
	0x17, 0xb1, 0x86, 0xbe, 0x99, 0x68, 0x95, 0x57, 0x13, 0x0d, 0x9d, 0x4e, 0xb4, 0xca, 0x78, 0xa2,
	0x55, 0xbe, 0x1c, 0x78, 0x84, 0x1e, 0x7a, 0xfa, 0x88, 0x04, 0x02, 0x18, 0xb3, 0xf5, 0x21, 0x37,
	0xe4, 0xa2, 0x4f, 0x58, 0xb8, 0x43, 0x19, 0x19, 0xf9, 0x2e, 0xb0, 0x9d, 0x69, 0xd8, 0xa0, 0x3d,
	0x8f, 0x18, 0xf0, 0xb5, 0x98, 0xfe, 0x70, 0x2c, 0xff, 0x97, 0xd6, 0x5b, 0x93, 0x9f, 0xfd, 0x77,
	0xff, 0x09, 0x00, 0x00, 0xff, 0xff, 0x0d, 0xf6, 0x42, 0xc9, 0xe2, 0x09, 0x00, 0x00,
}

func (this *GlobalSpecType) Equal(that interface{}) bool {
	if that == nil {
		return this == nil
	}

	that1, ok := that.(*GlobalSpecType)
	if !ok {
		that2, ok := that.(GlobalSpecType)
		if ok {
			that1 = &that2
		} else {
			return false
		}
	}
	if that1 == nil {
		return this == nil
	} else if this == nil {
		return false
	}
	if len(this.NetworkPolicyVersion) != len(that1.NetworkPolicyVersion) {
		return false
	}
	for i := range this.NetworkPolicyVersion {
		if !this.NetworkPolicyVersion[i].Equal(that1.NetworkPolicyVersion[i]) {
			return false
		}
	}
	if this.LatestVersion != that1.LatestVersion {
		return false
	}
	if this.UpdateUser != that1.UpdateUser {
		return false
	}
	if this.SpmPolicyId != that1.SpmPolicyId {
		return false
	}
	if this.PcGraphLatestVersionPolicyId != that1.PcGraphLatestVersionPolicyId {
		return false
	}
	if this.Comments != that1.Comments {
		return false
	}
	if len(this.BotInfrasWithVersion) != len(that1.BotInfrasWithVersion) {
		return false
	}
	for i := range this.BotInfrasWithVersion {
		if !this.BotInfrasWithVersion[i].Equal(that1.BotInfrasWithVersion[i]) {
			return false
		}
	}
	if !this.NetworkPolicyContent.Equal(that1.NetworkPolicyContent) {
		return false
	}
	if this.PcGraphDraftPolicyId != that1.PcGraphDraftPolicyId {
		return false
	}
	if len(this.CosseBotInfrasWithDeliveredVersion) != len(that1.CosseBotInfrasWithDeliveredVersion) {
		return false
	}
	for i := range this.CosseBotInfrasWithDeliveredVersion {
		if !this.CosseBotInfrasWithDeliveredVersion[i].Equal(that1.CosseBotInfrasWithDeliveredVersion[i]) {
			return false
		}
	}
	if this.UsedForCosse != that1.UsedForCosse {
		return false
	}
	return true
}
func (this *ReplaceSpecType) Equal(that interface{}) bool {
	if that == nil {
		return this == nil
	}

	that1, ok := that.(*ReplaceSpecType)
	if !ok {
		that2, ok := that.(ReplaceSpecType)
		if ok {
			that1 = &that2
		} else {
			return false
		}
	}
	if that1 == nil {
		return this == nil
	} else if this == nil {
		return false
	}
	if this.LatestVersion != that1.LatestVersion {
		return false
	}
	if this.UpdateUser != that1.UpdateUser {
		return false
	}
	if this.Comments != that1.Comments {
		return false
	}
	if !this.NetworkPolicyContent.Equal(that1.NetworkPolicyContent) {
		return false
	}
	if this.PcGraphDraftPolicyId != that1.PcGraphDraftPolicyId {
		return false
	}
	return true
}
func (this *GetSpecType) Equal(that interface{}) bool {
	if that == nil {
		return this == nil
	}

	that1, ok := that.(*GetSpecType)
	if !ok {
		that2, ok := that.(GetSpecType)
		if ok {
			that1 = &that2
		} else {
			return false
		}
	}
	if that1 == nil {
		return this == nil
	} else if this == nil {
		return false
	}
	if this.LatestVersion != that1.LatestVersion {
		return false
	}
	if this.UpdateUser != that1.UpdateUser {
		return false
	}
	if len(this.BotInfrasWithVersion) != len(that1.BotInfrasWithVersion) {
		return false
	}
	for i := range this.BotInfrasWithVersion {
		if !this.BotInfrasWithVersion[i].Equal(that1.BotInfrasWithVersion[i]) {
			return false
		}
	}
	if !this.NetworkPolicyContent.Equal(that1.NetworkPolicyContent) {
		return false
	}
	if len(this.CosseBotInfrasWithDeliveredVersion) != len(that1.CosseBotInfrasWithDeliveredVersion) {
		return false
	}
	for i := range this.CosseBotInfrasWithDeliveredVersion {
		if !this.CosseBotInfrasWithDeliveredVersion[i].Equal(that1.CosseBotInfrasWithDeliveredVersion[i]) {
			return false
		}
	}
	if this.UsedForCosse != that1.UsedForCosse {
		return false
	}
	return true
}
func (this *GlobalSpecType) GoString() string {
	if this == nil {
		return "nil"
	}
	s := make([]string, 0, 15)
	s = append(s, "&bot_network_policy.GlobalSpecType{")
	if this.NetworkPolicyVersion != nil {
		s = append(s, "NetworkPolicyVersion: "+fmt.Sprintf("%#v", this.NetworkPolicyVersion)+",\n")
	}
	s = append(s, "LatestVersion: "+fmt.Sprintf("%#v", this.LatestVersion)+",\n")
	s = append(s, "UpdateUser: "+fmt.Sprintf("%#v", this.UpdateUser)+",\n")
	s = append(s, "SpmPolicyId: "+fmt.Sprintf("%#v", this.SpmPolicyId)+",\n")
	s = append(s, "PcGraphLatestVersionPolicyId: "+fmt.Sprintf("%#v", this.PcGraphLatestVersionPolicyId)+",\n")
	s = append(s, "Comments: "+fmt.Sprintf("%#v", this.Comments)+",\n")
	if this.BotInfrasWithVersion != nil {
		s = append(s, "BotInfrasWithVersion: "+fmt.Sprintf("%#v", this.BotInfrasWithVersion)+",\n")
	}
	if this.NetworkPolicyContent != nil {
		s = append(s, "NetworkPolicyContent: "+fmt.Sprintf("%#v", this.NetworkPolicyContent)+",\n")
	}
	s = append(s, "PcGraphDraftPolicyId: "+fmt.Sprintf("%#v", this.PcGraphDraftPolicyId)+",\n")
	if this.CosseBotInfrasWithDeliveredVersion != nil {
		s = append(s, "CosseBotInfrasWithDeliveredVersion: "+fmt.Sprintf("%#v", this.CosseBotInfrasWithDeliveredVersion)+",\n")
	}
	s = append(s, "UsedForCosse: "+fmt.Sprintf("%#v", this.UsedForCosse)+",\n")
	s = append(s, "}")
	return strings.Join(s, "")
}
func (this *ReplaceSpecType) GoString() string {
	if this == nil {
		return "nil"
	}
	s := make([]string, 0, 9)
	s = append(s, "&bot_network_policy.ReplaceSpecType{")
	s = append(s, "LatestVersion: "+fmt.Sprintf("%#v", this.LatestVersion)+",\n")
	s = append(s, "UpdateUser: "+fmt.Sprintf("%#v", this.UpdateUser)+",\n")
	s = append(s, "Comments: "+fmt.Sprintf("%#v", this.Comments)+",\n")
	if this.NetworkPolicyContent != nil {
		s = append(s, "NetworkPolicyContent: "+fmt.Sprintf("%#v", this.NetworkPolicyContent)+",\n")
	}
	s = append(s, "PcGraphDraftPolicyId: "+fmt.Sprintf("%#v", this.PcGraphDraftPolicyId)+",\n")
	s = append(s, "}")
	return strings.Join(s, "")
}
func (this *GetSpecType) GoString() string {
	if this == nil {
		return "nil"
	}
	s := make([]string, 0, 10)
	s = append(s, "&bot_network_policy.GetSpecType{")
	s = append(s, "LatestVersion: "+fmt.Sprintf("%#v", this.LatestVersion)+",\n")
	s = append(s, "UpdateUser: "+fmt.Sprintf("%#v", this.UpdateUser)+",\n")
	if this.BotInfrasWithVersion != nil {
		s = append(s, "BotInfrasWithVersion: "+fmt.Sprintf("%#v", this.BotInfrasWithVersion)+",\n")
	}
	if this.NetworkPolicyContent != nil {
		s = append(s, "NetworkPolicyContent: "+fmt.Sprintf("%#v", this.NetworkPolicyContent)+",\n")
	}
	if this.CosseBotInfrasWithDeliveredVersion != nil {
		s = append(s, "CosseBotInfrasWithDeliveredVersion: "+fmt.Sprintf("%#v", this.CosseBotInfrasWithDeliveredVersion)+",\n")
	}
	s = append(s, "UsedForCosse: "+fmt.Sprintf("%#v", this.UsedForCosse)+",\n")
	s = append(s, "}")
	return strings.Join(s, "")
}
func valueToGoStringTypes(v interface{}, typ string) string {
	rv := reflect.ValueOf(v)
	if rv.IsNil() {
		return "nil"
	}
	pv := reflect.Indirect(rv).Interface()
	return fmt.Sprintf("func(v %v) *%v { return &v } ( %#v )", typ, typ, pv)
}
func (m *GlobalSpecType) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *GlobalSpecType) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *GlobalSpecType) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	if m.UsedForCosse {
		i--
		if m.UsedForCosse {
			dAtA[i] = 1
		} else {
			dAtA[i] = 0
		}
		i--
		dAtA[i] = 0x70
	}
	if len(m.CosseBotInfrasWithDeliveredVersion) > 0 {
		for iNdEx := len(m.CosseBotInfrasWithDeliveredVersion) - 1; iNdEx >= 0; iNdEx-- {
			{
				size, err := m.CosseBotInfrasWithDeliveredVersion[iNdEx].MarshalToSizedBuffer(dAtA[:i])
				if err != nil {
					return 0, err
				}
				i -= size
				i = encodeVarintTypes(dAtA, i, uint64(size))
			}
			i--
			dAtA[i] = 0x6a
		}
	}
	if len(m.PcGraphDraftPolicyId) > 0 {
		i -= len(m.PcGraphDraftPolicyId)
		copy(dAtA[i:], m.PcGraphDraftPolicyId)
		i = encodeVarintTypes(dAtA, i, uint64(len(m.PcGraphDraftPolicyId)))
		i--
		dAtA[i] = 0x62
	}
	if m.NetworkPolicyContent != nil {
		{
			size, err := m.NetworkPolicyContent.MarshalToSizedBuffer(dAtA[:i])
			if err != nil {
				return 0, err
			}
			i -= size
			i = encodeVarintTypes(dAtA, i, uint64(size))
		}
		i--
		dAtA[i] = 0x5a
	}
	if len(m.BotInfrasWithVersion) > 0 {
		for iNdEx := len(m.BotInfrasWithVersion) - 1; iNdEx >= 0; iNdEx-- {
			{
				size, err := m.BotInfrasWithVersion[iNdEx].MarshalToSizedBuffer(dAtA[:i])
				if err != nil {
					return 0, err
				}
				i -= size
				i = encodeVarintTypes(dAtA, i, uint64(size))
			}
			i--
			dAtA[i] = 0x52
		}
	}
	if len(m.Comments) > 0 {
		i -= len(m.Comments)
		copy(dAtA[i:], m.Comments)
		i = encodeVarintTypes(dAtA, i, uint64(len(m.Comments)))
		i--
		dAtA[i] = 0x4a
	}
	if len(m.PcGraphLatestVersionPolicyId) > 0 {
		i -= len(m.PcGraphLatestVersionPolicyId)
		copy(dAtA[i:], m.PcGraphLatestVersionPolicyId)
		i = encodeVarintTypes(dAtA, i, uint64(len(m.PcGraphLatestVersionPolicyId)))
		i--
		dAtA[i] = 0x42
	}
	if len(m.SpmPolicyId) > 0 {
		i -= len(m.SpmPolicyId)
		copy(dAtA[i:], m.SpmPolicyId)
		i = encodeVarintTypes(dAtA, i, uint64(len(m.SpmPolicyId)))
		i--
		dAtA[i] = 0x3a
	}
	if len(m.UpdateUser) > 0 {
		i -= len(m.UpdateUser)
		copy(dAtA[i:], m.UpdateUser)
		i = encodeVarintTypes(dAtA, i, uint64(len(m.UpdateUser)))
		i--
		dAtA[i] = 0x22
	}
	if len(m.LatestVersion) > 0 {
		i -= len(m.LatestVersion)
		copy(dAtA[i:], m.LatestVersion)
		i = encodeVarintTypes(dAtA, i, uint64(len(m.LatestVersion)))
		i--
		dAtA[i] = 0x12
	}
	if len(m.NetworkPolicyVersion) > 0 {
		for iNdEx := len(m.NetworkPolicyVersion) - 1; iNdEx >= 0; iNdEx-- {
			{
				size, err := m.NetworkPolicyVersion[iNdEx].MarshalToSizedBuffer(dAtA[:i])
				if err != nil {
					return 0, err
				}
				i -= size
				i = encodeVarintTypes(dAtA, i, uint64(size))
			}
			i--
			dAtA[i] = 0xa
		}
	}
	return len(dAtA) - i, nil
}

func (m *ReplaceSpecType) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *ReplaceSpecType) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *ReplaceSpecType) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	if len(m.PcGraphDraftPolicyId) > 0 {
		i -= len(m.PcGraphDraftPolicyId)
		copy(dAtA[i:], m.PcGraphDraftPolicyId)
		i = encodeVarintTypes(dAtA, i, uint64(len(m.PcGraphDraftPolicyId)))
		i--
		dAtA[i] = 0x62
	}
	if m.NetworkPolicyContent != nil {
		{
			size, err := m.NetworkPolicyContent.MarshalToSizedBuffer(dAtA[:i])
			if err != nil {
				return 0, err
			}
			i -= size
			i = encodeVarintTypes(dAtA, i, uint64(size))
		}
		i--
		dAtA[i] = 0x5a
	}
	if len(m.Comments) > 0 {
		i -= len(m.Comments)
		copy(dAtA[i:], m.Comments)
		i = encodeVarintTypes(dAtA, i, uint64(len(m.Comments)))
		i--
		dAtA[i] = 0x4a
	}
	if len(m.UpdateUser) > 0 {
		i -= len(m.UpdateUser)
		copy(dAtA[i:], m.UpdateUser)
		i = encodeVarintTypes(dAtA, i, uint64(len(m.UpdateUser)))
		i--
		dAtA[i] = 0x22
	}
	if len(m.LatestVersion) > 0 {
		i -= len(m.LatestVersion)
		copy(dAtA[i:], m.LatestVersion)
		i = encodeVarintTypes(dAtA, i, uint64(len(m.LatestVersion)))
		i--
		dAtA[i] = 0x12
	}
	return len(dAtA) - i, nil
}

func (m *GetSpecType) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *GetSpecType) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *GetSpecType) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	if m.UsedForCosse {
		i--
		if m.UsedForCosse {
			dAtA[i] = 1
		} else {
			dAtA[i] = 0
		}
		i--
		dAtA[i] = 0x70
	}
	if len(m.CosseBotInfrasWithDeliveredVersion) > 0 {
		for iNdEx := len(m.CosseBotInfrasWithDeliveredVersion) - 1; iNdEx >= 0; iNdEx-- {
			{
				size, err := m.CosseBotInfrasWithDeliveredVersion[iNdEx].MarshalToSizedBuffer(dAtA[:i])
				if err != nil {
					return 0, err
				}
				i -= size
				i = encodeVarintTypes(dAtA, i, uint64(size))
			}
			i--
			dAtA[i] = 0x6a
		}
	}
	if m.NetworkPolicyContent != nil {
		{
			size, err := m.NetworkPolicyContent.MarshalToSizedBuffer(dAtA[:i])
			if err != nil {
				return 0, err
			}
			i -= size
			i = encodeVarintTypes(dAtA, i, uint64(size))
		}
		i--
		dAtA[i] = 0x5a
	}
	if len(m.BotInfrasWithVersion) > 0 {
		for iNdEx := len(m.BotInfrasWithVersion) - 1; iNdEx >= 0; iNdEx-- {
			{
				size, err := m.BotInfrasWithVersion[iNdEx].MarshalToSizedBuffer(dAtA[:i])
				if err != nil {
					return 0, err
				}
				i -= size
				i = encodeVarintTypes(dAtA, i, uint64(size))
			}
			i--
			dAtA[i] = 0x52
		}
	}
	if len(m.UpdateUser) > 0 {
		i -= len(m.UpdateUser)
		copy(dAtA[i:], m.UpdateUser)
		i = encodeVarintTypes(dAtA, i, uint64(len(m.UpdateUser)))
		i--
		dAtA[i] = 0x22
	}
	if len(m.LatestVersion) > 0 {
		i -= len(m.LatestVersion)
		copy(dAtA[i:], m.LatestVersion)
		i = encodeVarintTypes(dAtA, i, uint64(len(m.LatestVersion)))
		i--
		dAtA[i] = 0x12
	}
	return len(dAtA) - i, nil
}

func encodeVarintTypes(dAtA []byte, offset int, v uint64) int {
	offset -= sovTypes(v)
	base := offset
	for v >= 1<<7 {
		dAtA[offset] = uint8(v&0x7f | 0x80)
		v >>= 7
		offset++
	}
	dAtA[offset] = uint8(v)
	return base
}
func (m *GlobalSpecType) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	if len(m.NetworkPolicyVersion) > 0 {
		for _, e := range m.NetworkPolicyVersion {
			l = e.Size()
			n += 1 + l + sovTypes(uint64(l))
		}
	}
	l = len(m.LatestVersion)
	if l > 0 {
		n += 1 + l + sovTypes(uint64(l))
	}
	l = len(m.UpdateUser)
	if l > 0 {
		n += 1 + l + sovTypes(uint64(l))
	}
	l = len(m.SpmPolicyId)
	if l > 0 {
		n += 1 + l + sovTypes(uint64(l))
	}
	l = len(m.PcGraphLatestVersionPolicyId)
	if l > 0 {
		n += 1 + l + sovTypes(uint64(l))
	}
	l = len(m.Comments)
	if l > 0 {
		n += 1 + l + sovTypes(uint64(l))
	}
	if len(m.BotInfrasWithVersion) > 0 {
		for _, e := range m.BotInfrasWithVersion {
			l = e.Size()
			n += 1 + l + sovTypes(uint64(l))
		}
	}
	if m.NetworkPolicyContent != nil {
		l = m.NetworkPolicyContent.Size()
		n += 1 + l + sovTypes(uint64(l))
	}
	l = len(m.PcGraphDraftPolicyId)
	if l > 0 {
		n += 1 + l + sovTypes(uint64(l))
	}
	if len(m.CosseBotInfrasWithDeliveredVersion) > 0 {
		for _, e := range m.CosseBotInfrasWithDeliveredVersion {
			l = e.Size()
			n += 1 + l + sovTypes(uint64(l))
		}
	}
	if m.UsedForCosse {
		n += 2
	}
	return n
}

func (m *ReplaceSpecType) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	l = len(m.LatestVersion)
	if l > 0 {
		n += 1 + l + sovTypes(uint64(l))
	}
	l = len(m.UpdateUser)
	if l > 0 {
		n += 1 + l + sovTypes(uint64(l))
	}
	l = len(m.Comments)
	if l > 0 {
		n += 1 + l + sovTypes(uint64(l))
	}
	if m.NetworkPolicyContent != nil {
		l = m.NetworkPolicyContent.Size()
		n += 1 + l + sovTypes(uint64(l))
	}
	l = len(m.PcGraphDraftPolicyId)
	if l > 0 {
		n += 1 + l + sovTypes(uint64(l))
	}
	return n
}

func (m *GetSpecType) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	l = len(m.LatestVersion)
	if l > 0 {
		n += 1 + l + sovTypes(uint64(l))
	}
	l = len(m.UpdateUser)
	if l > 0 {
		n += 1 + l + sovTypes(uint64(l))
	}
	if len(m.BotInfrasWithVersion) > 0 {
		for _, e := range m.BotInfrasWithVersion {
			l = e.Size()
			n += 1 + l + sovTypes(uint64(l))
		}
	}
	if m.NetworkPolicyContent != nil {
		l = m.NetworkPolicyContent.Size()
		n += 1 + l + sovTypes(uint64(l))
	}
	if len(m.CosseBotInfrasWithDeliveredVersion) > 0 {
		for _, e := range m.CosseBotInfrasWithDeliveredVersion {
			l = e.Size()
			n += 1 + l + sovTypes(uint64(l))
		}
	}
	if m.UsedForCosse {
		n += 2
	}
	return n
}

func sovTypes(x uint64) (n int) {
	return (math_bits.Len64(x|1) + 6) / 7
}
func sozTypes(x uint64) (n int) {
	return sovTypes(uint64((x << 1) ^ uint64((int64(x) >> 63))))
}
func (this *GlobalSpecType) String() string {
	if this == nil {
		return "nil"
	}
	repeatedStringForNetworkPolicyVersion := "[]*ObjectRefType{"
	for _, f := range this.NetworkPolicyVersion {
		repeatedStringForNetworkPolicyVersion += strings.Replace(fmt.Sprintf("%v", f), "ObjectRefType", "views.ObjectRefType", 1) + ","
	}
	repeatedStringForNetworkPolicyVersion += "}"
	repeatedStringForBotInfrasWithVersion := "[]*BotInfraWithVersion{"
	for _, f := range this.BotInfrasWithVersion {
		repeatedStringForBotInfrasWithVersion += strings.Replace(fmt.Sprintf("%v", f), "BotInfraWithVersion", "bot_defense.BotInfraWithVersion", 1) + ","
	}
	repeatedStringForBotInfrasWithVersion += "}"
	repeatedStringForCosseBotInfrasWithDeliveredVersion := "[]*CosseBotInfraWithDeliveredVersion{"
	for _, f := range this.CosseBotInfrasWithDeliveredVersion {
		repeatedStringForCosseBotInfrasWithDeliveredVersion += strings.Replace(fmt.Sprintf("%v", f), "CosseBotInfraWithDeliveredVersion", "bot_defense.CosseBotInfraWithDeliveredVersion", 1) + ","
	}
	repeatedStringForCosseBotInfrasWithDeliveredVersion += "}"
	s := strings.Join([]string{`&GlobalSpecType{`,
		`NetworkPolicyVersion:` + repeatedStringForNetworkPolicyVersion + `,`,
		`LatestVersion:` + fmt.Sprintf("%v", this.LatestVersion) + `,`,
		`UpdateUser:` + fmt.Sprintf("%v", this.UpdateUser) + `,`,
		`SpmPolicyId:` + fmt.Sprintf("%v", this.SpmPolicyId) + `,`,
		`PcGraphLatestVersionPolicyId:` + fmt.Sprintf("%v", this.PcGraphLatestVersionPolicyId) + `,`,
		`Comments:` + fmt.Sprintf("%v", this.Comments) + `,`,
		`BotInfrasWithVersion:` + repeatedStringForBotInfrasWithVersion + `,`,
		`NetworkPolicyContent:` + strings.Replace(fmt.Sprintf("%v", this.NetworkPolicyContent), "NetworkPolicyContent", "bot_defense.NetworkPolicyContent", 1) + `,`,
		`PcGraphDraftPolicyId:` + fmt.Sprintf("%v", this.PcGraphDraftPolicyId) + `,`,
		`CosseBotInfrasWithDeliveredVersion:` + repeatedStringForCosseBotInfrasWithDeliveredVersion + `,`,
		`UsedForCosse:` + fmt.Sprintf("%v", this.UsedForCosse) + `,`,
		`}`,
	}, "")
	return s
}
func (this *ReplaceSpecType) String() string {
	if this == nil {
		return "nil"
	}
	s := strings.Join([]string{`&ReplaceSpecType{`,
		`LatestVersion:` + fmt.Sprintf("%v", this.LatestVersion) + `,`,
		`UpdateUser:` + fmt.Sprintf("%v", this.UpdateUser) + `,`,
		`Comments:` + fmt.Sprintf("%v", this.Comments) + `,`,
		`NetworkPolicyContent:` + strings.Replace(fmt.Sprintf("%v", this.NetworkPolicyContent), "NetworkPolicyContent", "bot_defense.NetworkPolicyContent", 1) + `,`,
		`PcGraphDraftPolicyId:` + fmt.Sprintf("%v", this.PcGraphDraftPolicyId) + `,`,
		`}`,
	}, "")
	return s
}
func (this *GetSpecType) String() string {
	if this == nil {
		return "nil"
	}
	repeatedStringForBotInfrasWithVersion := "[]*BotInfraWithVersion{"
	for _, f := range this.BotInfrasWithVersion {
		repeatedStringForBotInfrasWithVersion += strings.Replace(fmt.Sprintf("%v", f), "BotInfraWithVersion", "bot_defense.BotInfraWithVersion", 1) + ","
	}
	repeatedStringForBotInfrasWithVersion += "}"
	repeatedStringForCosseBotInfrasWithDeliveredVersion := "[]*CosseBotInfraWithDeliveredVersion{"
	for _, f := range this.CosseBotInfrasWithDeliveredVersion {
		repeatedStringForCosseBotInfrasWithDeliveredVersion += strings.Replace(fmt.Sprintf("%v", f), "CosseBotInfraWithDeliveredVersion", "bot_defense.CosseBotInfraWithDeliveredVersion", 1) + ","
	}
	repeatedStringForCosseBotInfrasWithDeliveredVersion += "}"
	s := strings.Join([]string{`&GetSpecType{`,
		`LatestVersion:` + fmt.Sprintf("%v", this.LatestVersion) + `,`,
		`UpdateUser:` + fmt.Sprintf("%v", this.UpdateUser) + `,`,
		`BotInfrasWithVersion:` + repeatedStringForBotInfrasWithVersion + `,`,
		`NetworkPolicyContent:` + strings.Replace(fmt.Sprintf("%v", this.NetworkPolicyContent), "NetworkPolicyContent", "bot_defense.NetworkPolicyContent", 1) + `,`,
		`CosseBotInfrasWithDeliveredVersion:` + repeatedStringForCosseBotInfrasWithDeliveredVersion + `,`,
		`UsedForCosse:` + fmt.Sprintf("%v", this.UsedForCosse) + `,`,
		`}`,
	}, "")
	return s
}
func valueToStringTypes(v interface{}) string {
	rv := reflect.ValueOf(v)
	if rv.IsNil() {
		return "nil"
	}
	pv := reflect.Indirect(rv).Interface()
	return fmt.Sprintf("*%v", pv)
}
func (m *GlobalSpecType) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowTypes
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: GlobalSpecType: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: GlobalSpecType: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field NetworkPolicyVersion", wireType)
			}
			var msglen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowTypes
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				msglen |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if msglen < 0 {
				return ErrInvalidLengthTypes
			}
			postIndex := iNdEx + msglen
			if postIndex < 0 {
				return ErrInvalidLengthTypes
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.NetworkPolicyVersion = append(m.NetworkPolicyVersion, &views.ObjectRefType{})
			if err := m.NetworkPolicyVersion[len(m.NetworkPolicyVersion)-1].Unmarshal(dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			iNdEx = postIndex
		case 2:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field LatestVersion", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowTypes
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthTypes
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthTypes
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.LatestVersion = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		case 4:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field UpdateUser", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowTypes
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthTypes
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthTypes
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.UpdateUser = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		case 7:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field SpmPolicyId", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowTypes
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthTypes
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthTypes
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.SpmPolicyId = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		case 8:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field PcGraphLatestVersionPolicyId", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowTypes
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthTypes
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthTypes
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.PcGraphLatestVersionPolicyId = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		case 9:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Comments", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowTypes
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthTypes
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthTypes
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.Comments = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		case 10:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field BotInfrasWithVersion", wireType)
			}
			var msglen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowTypes
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				msglen |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if msglen < 0 {
				return ErrInvalidLengthTypes
			}
			postIndex := iNdEx + msglen
			if postIndex < 0 {
				return ErrInvalidLengthTypes
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.BotInfrasWithVersion = append(m.BotInfrasWithVersion, &bot_defense.BotInfraWithVersion{})
			if err := m.BotInfrasWithVersion[len(m.BotInfrasWithVersion)-1].Unmarshal(dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			iNdEx = postIndex
		case 11:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field NetworkPolicyContent", wireType)
			}
			var msglen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowTypes
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				msglen |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if msglen < 0 {
				return ErrInvalidLengthTypes
			}
			postIndex := iNdEx + msglen
			if postIndex < 0 {
				return ErrInvalidLengthTypes
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			if m.NetworkPolicyContent == nil {
				m.NetworkPolicyContent = &bot_defense.NetworkPolicyContent{}
			}
			if err := m.NetworkPolicyContent.Unmarshal(dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			iNdEx = postIndex
		case 12:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field PcGraphDraftPolicyId", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowTypes
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthTypes
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthTypes
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.PcGraphDraftPolicyId = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		case 13:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field CosseBotInfrasWithDeliveredVersion", wireType)
			}
			var msglen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowTypes
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				msglen |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if msglen < 0 {
				return ErrInvalidLengthTypes
			}
			postIndex := iNdEx + msglen
			if postIndex < 0 {
				return ErrInvalidLengthTypes
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.CosseBotInfrasWithDeliveredVersion = append(m.CosseBotInfrasWithDeliveredVersion, &bot_defense.CosseBotInfraWithDeliveredVersion{})
			if err := m.CosseBotInfrasWithDeliveredVersion[len(m.CosseBotInfrasWithDeliveredVersion)-1].Unmarshal(dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			iNdEx = postIndex
		case 14:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field UsedForCosse", wireType)
			}
			var v int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowTypes
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				v |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			m.UsedForCosse = bool(v != 0)
		default:
			iNdEx = preIndex
			skippy, err := skipTypes(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if skippy < 0 {
				return ErrInvalidLengthTypes
			}
			if (iNdEx + skippy) < 0 {
				return ErrInvalidLengthTypes
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func (m *ReplaceSpecType) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowTypes
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: ReplaceSpecType: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: ReplaceSpecType: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 2:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field LatestVersion", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowTypes
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthTypes
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthTypes
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.LatestVersion = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		case 4:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field UpdateUser", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowTypes
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthTypes
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthTypes
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.UpdateUser = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		case 9:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Comments", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowTypes
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthTypes
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthTypes
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.Comments = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		case 11:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field NetworkPolicyContent", wireType)
			}
			var msglen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowTypes
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				msglen |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if msglen < 0 {
				return ErrInvalidLengthTypes
			}
			postIndex := iNdEx + msglen
			if postIndex < 0 {
				return ErrInvalidLengthTypes
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			if m.NetworkPolicyContent == nil {
				m.NetworkPolicyContent = &bot_defense.NetworkPolicyContent{}
			}
			if err := m.NetworkPolicyContent.Unmarshal(dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			iNdEx = postIndex
		case 12:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field PcGraphDraftPolicyId", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowTypes
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthTypes
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthTypes
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.PcGraphDraftPolicyId = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		default:
			iNdEx = preIndex
			skippy, err := skipTypes(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if skippy < 0 {
				return ErrInvalidLengthTypes
			}
			if (iNdEx + skippy) < 0 {
				return ErrInvalidLengthTypes
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func (m *GetSpecType) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowTypes
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: GetSpecType: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: GetSpecType: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 2:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field LatestVersion", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowTypes
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthTypes
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthTypes
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.LatestVersion = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		case 4:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field UpdateUser", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowTypes
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthTypes
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthTypes
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.UpdateUser = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		case 10:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field BotInfrasWithVersion", wireType)
			}
			var msglen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowTypes
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				msglen |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if msglen < 0 {
				return ErrInvalidLengthTypes
			}
			postIndex := iNdEx + msglen
			if postIndex < 0 {
				return ErrInvalidLengthTypes
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.BotInfrasWithVersion = append(m.BotInfrasWithVersion, &bot_defense.BotInfraWithVersion{})
			if err := m.BotInfrasWithVersion[len(m.BotInfrasWithVersion)-1].Unmarshal(dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			iNdEx = postIndex
		case 11:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field NetworkPolicyContent", wireType)
			}
			var msglen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowTypes
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				msglen |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if msglen < 0 {
				return ErrInvalidLengthTypes
			}
			postIndex := iNdEx + msglen
			if postIndex < 0 {
				return ErrInvalidLengthTypes
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			if m.NetworkPolicyContent == nil {
				m.NetworkPolicyContent = &bot_defense.NetworkPolicyContent{}
			}
			if err := m.NetworkPolicyContent.Unmarshal(dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			iNdEx = postIndex
		case 13:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field CosseBotInfrasWithDeliveredVersion", wireType)
			}
			var msglen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowTypes
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				msglen |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if msglen < 0 {
				return ErrInvalidLengthTypes
			}
			postIndex := iNdEx + msglen
			if postIndex < 0 {
				return ErrInvalidLengthTypes
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.CosseBotInfrasWithDeliveredVersion = append(m.CosseBotInfrasWithDeliveredVersion, &bot_defense.CosseBotInfraWithDeliveredVersion{})
			if err := m.CosseBotInfrasWithDeliveredVersion[len(m.CosseBotInfrasWithDeliveredVersion)-1].Unmarshal(dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			iNdEx = postIndex
		case 14:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field UsedForCosse", wireType)
			}
			var v int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowTypes
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				v |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			m.UsedForCosse = bool(v != 0)
		default:
			iNdEx = preIndex
			skippy, err := skipTypes(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if skippy < 0 {
				return ErrInvalidLengthTypes
			}
			if (iNdEx + skippy) < 0 {
				return ErrInvalidLengthTypes
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func skipTypes(dAtA []byte) (n int, err error) {
	l := len(dAtA)
	iNdEx := 0
	depth := 0
	for iNdEx < l {
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return 0, ErrIntOverflowTypes
			}
			if iNdEx >= l {
				return 0, io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= (uint64(b) & 0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		wireType := int(wire & 0x7)
		switch wireType {
		case 0:
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return 0, ErrIntOverflowTypes
				}
				if iNdEx >= l {
					return 0, io.ErrUnexpectedEOF
				}
				iNdEx++
				if dAtA[iNdEx-1] < 0x80 {
					break
				}
			}
		case 1:
			iNdEx += 8
		case 2:
			var length int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return 0, ErrIntOverflowTypes
				}
				if iNdEx >= l {
					return 0, io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				length |= (int(b) & 0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if length < 0 {
				return 0, ErrInvalidLengthTypes
			}
			iNdEx += length
		case 3:
			depth++
		case 4:
			if depth == 0 {
				return 0, ErrUnexpectedEndOfGroupTypes
			}
			depth--
		case 5:
			iNdEx += 4
		default:
			return 0, fmt.Errorf("proto: illegal wireType %d", wireType)
		}
		if iNdEx < 0 {
			return 0, ErrInvalidLengthTypes
		}
		if depth == 0 {
			return iNdEx, nil
		}
	}
	return 0, io.ErrUnexpectedEOF
}

var (
	ErrInvalidLengthTypes        = fmt.Errorf("proto: negative length found during unmarshaling")
	ErrIntOverflowTypes          = fmt.Errorf("proto: integer overflow")
	ErrUnexpectedEndOfGroupTypes = fmt.Errorf("proto: unexpected end of group")
)
