// Code generated by protoc-gen-gogo. DO NOT EDIT.
// source: ves.io/schema/flow/public_customapi_akar.proto

// Flows
//
// x-displayName: "Flows"
// APIs to get Flow records and data

package flow

import (
	context "context"
	fmt "fmt"
	_ "github.com/gogo/googleapis/google/api"
	_ "github.com/gogo/protobuf/gogoproto"
	proto "github.com/gogo/protobuf/proto"
	golang_proto "github.com/golang/protobuf/proto"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
	_ "github.com/volterraedge/terraform-provider-volterra/pbgo/extschema/schema"
	_ "github.com/volterraedge/terraform-provider-volterra/pbgo/extschema/schema/vesenv"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = golang_proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.GoGoProtoPackageIsVersion3 // please upgrade the proto package

func init() {
	proto.RegisterFile("ves.io/schema/flow/public_customapi_akar.proto", fileDescriptor_3f0412dba6d1f0c2)
}
func init() {
	golang_proto.RegisterFile("ves.io/schema/flow/public_customapi_akar.proto", fileDescriptor_3f0412dba6d1f0c2)
}

var fileDescriptor_3f0412dba6d1f0c2 = []byte{
	// 543 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x9c, 0x93, 0x4d, 0x8b, 0xd4, 0x4e,
	0x10, 0xc6, 0xd3, 0xfb, 0xe7, 0x2f, 0x18, 0x3d, 0x48, 0x40, 0x5c, 0x46, 0x69, 0x64, 0xf0, 0x05,
	0xc4, 0x4e, 0x83, 0xe2, 0x41, 0x05, 0x51, 0x07, 0xdf, 0x6e, 0xe2, 0xaa, 0x07, 0x2f, 0x4b, 0x27,
	0xa9, 0xc9, 0x36, 0x9b, 0x74, 0xb5, 0xe9, 0x4e, 0x66, 0xe7, 0x26, 0xf3, 0x09, 0x04, 0xbf, 0x84,
	0x27, 0x8f, 0x7a, 0x10, 0x64, 0x6f, 0xab, 0x17, 0x19, 0xf0, 0xb2, 0x47, 0x27, 0xe3, 0xc1, 0xe3,
	0x7e, 0x04, 0xd9, 0x4c, 0x32, 0x64, 0x74, 0x70, 0xd5, 0x5b, 0x57, 0x9e, 0x5f, 0xba, 0x9f, 0xa7,
	0x8a, 0x72, 0xfd, 0x02, 0x8c, 0x2f, 0x91, 0x9b, 0x70, 0x03, 0x52, 0xc1, 0xfb, 0x09, 0x0e, 0xb8,
	0xce, 0x83, 0x44, 0x86, 0xeb, 0x61, 0x6e, 0x2c, 0xa6, 0x42, 0xcb, 0x75, 0xb1, 0x29, 0x32, 0x5f,
	0x67, 0x68, 0xd1, 0xf3, 0x66, 0xbc, 0x3f, 0xe3, 0xfd, 0x7d, 0xbe, 0xc3, 0x62, 0x69, 0x37, 0xf2,
	0xc0, 0x0f, 0x31, 0xe5, 0x31, 0xc6, 0xc8, 0x2b, 0x34, 0xc8, 0xfb, 0x55, 0x55, 0x15, 0xd5, 0x69,
	0x76, 0x45, 0xe7, 0x54, 0x8c, 0x18, 0x27, 0xc0, 0x85, 0x96, 0x5c, 0x28, 0x85, 0x56, 0x58, 0x89,
	0xca, 0xd4, 0x2a, 0x5d, 0x62, 0xc8, 0x0e, 0x35, 0x34, 0xfa, 0xc9, 0x45, 0x1d, 0x75, 0xfb, 0xe7,
	0xee, 0xa2, 0x58, 0x80, 0x01, 0x55, 0x2c, 0x32, 0x97, 0x3e, 0xfd, 0xef, 0x9e, 0xe8, 0x55, 0xd1,
	0xee, 0x26, 0x38, 0xe8, 0xa1, 0x52, 0x10, 0xee, 0xeb, 0xb7, 0x1e, 0x3e, 0xf0, 0xde, 0x10, 0xf7,
	0xf0, 0x5a, 0x1e, 0x98, 0x30, 0x93, 0x01, 0x78, 0x67, 0xfc, 0x5f, 0xc3, 0xfa, 0x73, 0xf9, 0x11,
	0x3c, 0xcf, 0xc1, 0xd8, 0xce, 0xd9, 0x03, 0x28, 0xa3, 0x51, 0x19, 0xe8, 0x3e, 0x2e, 0x77, 0x56,
	0x8f, 0xf6, 0xaf, 0x6c, 0x85, 0x2c, 0x90, 0x49, 0x22, 0x55, 0x3c, 0xfa, 0xf2, 0xed, 0xd5, 0xca,
	0x8d, 0xee, 0xd5, 0xba, 0xdd, 0x5c, 0x89, 0x14, 0x8c, 0x16, 0x21, 0x18, 0x6e, 0x86, 0xc6, 0x42,
	0x5a, 0x65, 0x67, 0x21, 0x26, 0xc9, 0xcc, 0x20, 0x17, 0x51, 0x84, 0x8a, 0x9b, 0xe6, 0xea, 0x6b,
	0xe4, 0x82, 0xf7, 0x96, 0xb8, 0x47, 0x9e, 0xa8, 0xf9, 0x27, 0xef, 0xdc, 0x32, 0x33, 0x2d, 0xa0,
	0x31, 0x7d, 0xfe, 0x40, 0xae, 0xb6, 0xfd, 0x74, 0xa9, 0xed, 0x9b, 0xdd, 0xeb, 0x7f, 0x6b, 0x3b,
	0x57, 0x0b, 0xc6, 0xdf, 0xad, 0xb8, 0xc7, 0xef, 0x81, 0xad, 0xfb, 0x54, 0x0d, 0x68, 0xcd, 0x0a,
	0x9b, 0x1b, 0x8f, 0xfd, 0xa6, 0x9f, 0x2d, 0xae, 0x49, 0xe2, 0xff, 0x29, 0x5e, 0x07, 0xfa, 0x40,
	0xca, 0x9d, 0x55, 0x6c, 0x27, 0xba, 0x78, 0xba, 0xaa, 0x7e, 0xb2, 0xcd, 0x52, 0x54, 0xd2, 0x62,
	0xd6, 0x56, 0x85, 0xc2, 0x54, 0x24, 0x43, 0x16, 0x81, 0xad, 0x21, 0x63, 0x85, 0x8a, 0x44, 0x16,
	0xcd, 0xe9, 0x02, 0x0c, 0x93, 0xc8, 0x06, 0x10, 0x30, 0x11, 0x86, 0x60, 0x0c, 0xcb, 0x40, 0x44,
	0x55, 0xd3, 0xee, 0x78, 0xbd, 0x7f, 0x9c, 0xb5, 0x6e, 0xde, 0xb2, 0xb9, 0xe9, 0xb8, 0xdb, 0xef,
	0xc9, 0x7f, 0xa3, 0xcf, 0xab, 0x2b, 0xc7, 0xc8, 0xed, 0x11, 0x19, 0x4f, 0xa8, 0xb3, 0x3b, 0xa1,
	0xce, 0xde, 0x84, 0x92, 0x17, 0x25, 0x25, 0xaf, 0x4b, 0x4a, 0x3e, 0x96, 0x94, 0x8c, 0x4b, 0x4a,
	0xbe, 0x96, 0x94, 0x7c, 0x2f, 0xa9, 0xb3, 0x57, 0x52, 0xf2, 0x72, 0x4a, 0x9d, 0xed, 0x29, 0x25,
	0xe3, 0x29, 0x75, 0x76, 0xa7, 0xd4, 0x79, 0x76, 0x3f, 0x46, 0xbd, 0x19, 0xfb, 0x05, 0x26, 0x16,
	0xb2, 0x4c, 0xf8, 0xb9, 0xe1, 0xd5, 0xa1, 0x8f, 0x59, 0xca, 0x74, 0x86, 0x85, 0x8c, 0x20, 0x63,
	0x8d, 0xcc, 0x75, 0x10, 0x23, 0x87, 0x2d, 0x5b, 0x6f, 0x56, 0x6b, 0x3b, 0x83, 0x43, 0xd5, 0x5e,
	0x5d, 0xfe, 0x11, 0x00, 0x00, 0xff, 0xff, 0x8d, 0x17, 0x21, 0xf5, 0x4b, 0x04, 0x00, 0x00,
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConn

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion4

// CustomFlowConnectionAPIClient is the client API for CustomFlowConnectionAPI service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://godoc.org/google.golang.org/grpc#ClientConn.NewStream.
type CustomFlowConnectionAPIClient interface {
	// Subscribe
	//
	// x-displayName: "Subscribe to Flow Collection"
	// Subscribe to Flow Collection
	Subscribe(ctx context.Context, in *SubscribeRequest, opts ...grpc.CallOption) (*SubscribeResponse, error)
	// Unsubscribe
	//
	// x-displayName: "Unsubscribe to Flow Collection"
	// Unsubscribe to Flow Collection
	Unsubscribe(ctx context.Context, in *UnsubscribeRequest, opts ...grpc.CallOption) (*UnsubscribeResponse, error)
	// Check subscription status
	//
	// x-displayName: "Check subscription status for Flow Collection"
	// Check subscription status flow Flow Collection
	GetSubscriptionStatus(ctx context.Context, in *SubscriptionStatusRequest, opts ...grpc.CallOption) (*SubscriptionStatusResponse, error)
}

type customFlowConnectionAPIClient struct {
	cc *grpc.ClientConn
}

func NewCustomFlowConnectionAPIClient(cc *grpc.ClientConn) CustomFlowConnectionAPIClient {
	return &customFlowConnectionAPIClient{cc}
}

func (c *customFlowConnectionAPIClient) Subscribe(ctx context.Context, in *SubscribeRequest, opts ...grpc.CallOption) (*SubscribeResponse, error) {
	out := new(SubscribeResponse)
	err := c.cc.Invoke(ctx, "/ves.io.schema.flow.CustomFlowConnectionAPI/Subscribe", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *customFlowConnectionAPIClient) Unsubscribe(ctx context.Context, in *UnsubscribeRequest, opts ...grpc.CallOption) (*UnsubscribeResponse, error) {
	out := new(UnsubscribeResponse)
	err := c.cc.Invoke(ctx, "/ves.io.schema.flow.CustomFlowConnectionAPI/Unsubscribe", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *customFlowConnectionAPIClient) GetSubscriptionStatus(ctx context.Context, in *SubscriptionStatusRequest, opts ...grpc.CallOption) (*SubscriptionStatusResponse, error) {
	out := new(SubscriptionStatusResponse)
	err := c.cc.Invoke(ctx, "/ves.io.schema.flow.CustomFlowConnectionAPI/GetSubscriptionStatus", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// CustomFlowConnectionAPIServer is the server API for CustomFlowConnectionAPI service.
type CustomFlowConnectionAPIServer interface {
	// Subscribe
	//
	// x-displayName: "Subscribe to Flow Collection"
	// Subscribe to Flow Collection
	Subscribe(context.Context, *SubscribeRequest) (*SubscribeResponse, error)
	// Unsubscribe
	//
	// x-displayName: "Unsubscribe to Flow Collection"
	// Unsubscribe to Flow Collection
	Unsubscribe(context.Context, *UnsubscribeRequest) (*UnsubscribeResponse, error)
	// Check subscription status
	//
	// x-displayName: "Check subscription status for Flow Collection"
	// Check subscription status flow Flow Collection
	GetSubscriptionStatus(context.Context, *SubscriptionStatusRequest) (*SubscriptionStatusResponse, error)
}

// UnimplementedCustomFlowConnectionAPIServer can be embedded to have forward compatible implementations.
type UnimplementedCustomFlowConnectionAPIServer struct {
}

func (*UnimplementedCustomFlowConnectionAPIServer) Subscribe(ctx context.Context, req *SubscribeRequest) (*SubscribeResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Subscribe not implemented")
}
func (*UnimplementedCustomFlowConnectionAPIServer) Unsubscribe(ctx context.Context, req *UnsubscribeRequest) (*UnsubscribeResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Unsubscribe not implemented")
}
func (*UnimplementedCustomFlowConnectionAPIServer) GetSubscriptionStatus(ctx context.Context, req *SubscriptionStatusRequest) (*SubscriptionStatusResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetSubscriptionStatus not implemented")
}

func RegisterCustomFlowConnectionAPIServer(s *grpc.Server, srv CustomFlowConnectionAPIServer) {
	s.RegisterService(&_CustomFlowConnectionAPI_serviceDesc, srv)
}

func _CustomFlowConnectionAPI_Subscribe_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(SubscribeRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(CustomFlowConnectionAPIServer).Subscribe(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/ves.io.schema.flow.CustomFlowConnectionAPI/Subscribe",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(CustomFlowConnectionAPIServer).Subscribe(ctx, req.(*SubscribeRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _CustomFlowConnectionAPI_Unsubscribe_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(UnsubscribeRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(CustomFlowConnectionAPIServer).Unsubscribe(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/ves.io.schema.flow.CustomFlowConnectionAPI/Unsubscribe",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(CustomFlowConnectionAPIServer).Unsubscribe(ctx, req.(*UnsubscribeRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _CustomFlowConnectionAPI_GetSubscriptionStatus_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(SubscriptionStatusRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(CustomFlowConnectionAPIServer).GetSubscriptionStatus(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/ves.io.schema.flow.CustomFlowConnectionAPI/GetSubscriptionStatus",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(CustomFlowConnectionAPIServer).GetSubscriptionStatus(ctx, req.(*SubscriptionStatusRequest))
	}
	return interceptor(ctx, in, info, handler)
}

var _CustomFlowConnectionAPI_serviceDesc = grpc.ServiceDesc{
	ServiceName: "ves.io.schema.flow.CustomFlowConnectionAPI",
	HandlerType: (*CustomFlowConnectionAPIServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "Subscribe",
			Handler:    _CustomFlowConnectionAPI_Subscribe_Handler,
		},
		{
			MethodName: "Unsubscribe",
			Handler:    _CustomFlowConnectionAPI_Unsubscribe_Handler,
		},
		{
			MethodName: "GetSubscriptionStatus",
			Handler:    _CustomFlowConnectionAPI_GetSubscriptionStatus_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "ves.io/schema/flow/public_customapi_akar.proto",
}
