// Code generated by protoc-gen-gogo. DO NOT EDIT.
// source: ves.io/schema/geo_location_set/types.proto

package geo_location_set

import (
	fmt "fmt"
	_ "github.com/gogo/protobuf/gogoproto"
	proto "github.com/gogo/protobuf/proto"
	_ "github.com/gogo/protobuf/types"
	schema "github.com/volterraedge/terraform-provider-volterra/pbgo/extschema/schema"
	views "github.com/volterraedge/terraform-provider-volterra/pbgo/extschema/schema/views"
	io "io"
	math "math"
	math_bits "math/bits"
	reflect "reflect"
	strings "strings"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.GoGoProtoPackageIsVersion3 // please upgrade the proto package

// Geolocation Set
//
// x-displayName: "Geolocation Set"
// Geolocation Set can be composed of states, provinces, countries or continents.
type GlobalSpecType struct {
	// Geolocation Set
	//
	// x-required
	// x-displayName: "Geolocation Label Selector"
	// Select the geo_location_set.
	//
	// Types that are valid to be assigned to LocationChoice:
	//	*GlobalSpecType_Global
	//	*GlobalSpecType_CustomGeoLocationSelector
	LocationChoice isGlobalSpecType_LocationChoice `protobuf_oneof:"location_choice"`
	// backward reference object list
	//
	// x-displayName: "DNS Load balancers"
	// a list of dns load balancers associated with this geo location set
	DnsLoadBalancers []*views.ObjectRefType `protobuf:"bytes,4,rep,name=dns_load_balancers,json=dnsLoadBalancers,proto3" json:"dns_load_balancers,omitempty"`
}

func (m *GlobalSpecType) Reset()      { *m = GlobalSpecType{} }
func (*GlobalSpecType) ProtoMessage() {}
func (*GlobalSpecType) Descriptor() ([]byte, []int) {
	return fileDescriptor_54da32594f6f9b9b, []int{0}
}
func (m *GlobalSpecType) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *GlobalSpecType) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	b = b[:cap(b)]
	n, err := m.MarshalToSizedBuffer(b)
	if err != nil {
		return nil, err
	}
	return b[:n], nil
}
func (m *GlobalSpecType) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GlobalSpecType.Merge(m, src)
}
func (m *GlobalSpecType) XXX_Size() int {
	return m.Size()
}
func (m *GlobalSpecType) XXX_DiscardUnknown() {
	xxx_messageInfo_GlobalSpecType.DiscardUnknown(m)
}

var xxx_messageInfo_GlobalSpecType proto.InternalMessageInfo

type isGlobalSpecType_LocationChoice interface {
	isGlobalSpecType_LocationChoice()
	Equal(interface{}) bool
	MarshalTo([]byte) (int, error)
	Size() int
}

type GlobalSpecType_Global struct {
	Global *schema.Empty `protobuf:"bytes,2,opt,name=global,proto3,oneof" json:"global,omitempty"`
}
type GlobalSpecType_CustomGeoLocationSelector struct {
	CustomGeoLocationSelector *schema.LabelSelectorType `protobuf:"bytes,3,opt,name=custom_geo_location_selector,json=customGeoLocationSelector,proto3,oneof" json:"custom_geo_location_selector,omitempty"`
}

func (*GlobalSpecType_Global) isGlobalSpecType_LocationChoice()                    {}
func (*GlobalSpecType_CustomGeoLocationSelector) isGlobalSpecType_LocationChoice() {}

func (m *GlobalSpecType) GetLocationChoice() isGlobalSpecType_LocationChoice {
	if m != nil {
		return m.LocationChoice
	}
	return nil
}

func (m *GlobalSpecType) GetGlobal() *schema.Empty {
	if x, ok := m.GetLocationChoice().(*GlobalSpecType_Global); ok {
		return x.Global
	}
	return nil
}

func (m *GlobalSpecType) GetCustomGeoLocationSelector() *schema.LabelSelectorType {
	if x, ok := m.GetLocationChoice().(*GlobalSpecType_CustomGeoLocationSelector); ok {
		return x.CustomGeoLocationSelector
	}
	return nil
}

func (m *GlobalSpecType) GetDnsLoadBalancers() []*views.ObjectRefType {
	if m != nil {
		return m.DnsLoadBalancers
	}
	return nil
}

// XXX_OneofWrappers is for the internal use of the proto package.
func (*GlobalSpecType) XXX_OneofWrappers() []interface{} {
	return []interface{}{
		(*GlobalSpecType_Global)(nil),
		(*GlobalSpecType_CustomGeoLocationSelector)(nil),
	}
}

// Geolocation
//
// x-displayName: "Create Geolocation"
// Creates a Geolocation Set
type CreateSpecType struct {
	// Types that are valid to be assigned to LocationChoice:
	//	*CreateSpecType_Global
	//	*CreateSpecType_CustomGeoLocationSelector
	LocationChoice isCreateSpecType_LocationChoice `protobuf_oneof:"location_choice"`
}

func (m *CreateSpecType) Reset()      { *m = CreateSpecType{} }
func (*CreateSpecType) ProtoMessage() {}
func (*CreateSpecType) Descriptor() ([]byte, []int) {
	return fileDescriptor_54da32594f6f9b9b, []int{1}
}
func (m *CreateSpecType) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *CreateSpecType) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	b = b[:cap(b)]
	n, err := m.MarshalToSizedBuffer(b)
	if err != nil {
		return nil, err
	}
	return b[:n], nil
}
func (m *CreateSpecType) XXX_Merge(src proto.Message) {
	xxx_messageInfo_CreateSpecType.Merge(m, src)
}
func (m *CreateSpecType) XXX_Size() int {
	return m.Size()
}
func (m *CreateSpecType) XXX_DiscardUnknown() {
	xxx_messageInfo_CreateSpecType.DiscardUnknown(m)
}

var xxx_messageInfo_CreateSpecType proto.InternalMessageInfo

type isCreateSpecType_LocationChoice interface {
	isCreateSpecType_LocationChoice()
	Equal(interface{}) bool
	MarshalTo([]byte) (int, error)
	Size() int
}

type CreateSpecType_Global struct {
	Global *schema.Empty `protobuf:"bytes,2,opt,name=global,proto3,oneof" json:"global,omitempty"`
}
type CreateSpecType_CustomGeoLocationSelector struct {
	CustomGeoLocationSelector *schema.LabelSelectorType `protobuf:"bytes,3,opt,name=custom_geo_location_selector,json=customGeoLocationSelector,proto3,oneof" json:"custom_geo_location_selector,omitempty"`
}

func (*CreateSpecType_Global) isCreateSpecType_LocationChoice()                    {}
func (*CreateSpecType_CustomGeoLocationSelector) isCreateSpecType_LocationChoice() {}

func (m *CreateSpecType) GetLocationChoice() isCreateSpecType_LocationChoice {
	if m != nil {
		return m.LocationChoice
	}
	return nil
}

func (m *CreateSpecType) GetGlobal() *schema.Empty {
	if x, ok := m.GetLocationChoice().(*CreateSpecType_Global); ok {
		return x.Global
	}
	return nil
}

func (m *CreateSpecType) GetCustomGeoLocationSelector() *schema.LabelSelectorType {
	if x, ok := m.GetLocationChoice().(*CreateSpecType_CustomGeoLocationSelector); ok {
		return x.CustomGeoLocationSelector
	}
	return nil
}

// XXX_OneofWrappers is for the internal use of the proto package.
func (*CreateSpecType) XXX_OneofWrappers() []interface{} {
	return []interface{}{
		(*CreateSpecType_Global)(nil),
		(*CreateSpecType_CustomGeoLocationSelector)(nil),
	}
}

// Geolocation
//
// x-displayName: "Replace Geolocation Set"
// Amends a Geolocation Set
type ReplaceSpecType struct {
	// Types that are valid to be assigned to LocationChoice:
	//	*ReplaceSpecType_Global
	//	*ReplaceSpecType_CustomGeoLocationSelector
	LocationChoice isReplaceSpecType_LocationChoice `protobuf_oneof:"location_choice"`
}

func (m *ReplaceSpecType) Reset()      { *m = ReplaceSpecType{} }
func (*ReplaceSpecType) ProtoMessage() {}
func (*ReplaceSpecType) Descriptor() ([]byte, []int) {
	return fileDescriptor_54da32594f6f9b9b, []int{2}
}
func (m *ReplaceSpecType) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *ReplaceSpecType) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	b = b[:cap(b)]
	n, err := m.MarshalToSizedBuffer(b)
	if err != nil {
		return nil, err
	}
	return b[:n], nil
}
func (m *ReplaceSpecType) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ReplaceSpecType.Merge(m, src)
}
func (m *ReplaceSpecType) XXX_Size() int {
	return m.Size()
}
func (m *ReplaceSpecType) XXX_DiscardUnknown() {
	xxx_messageInfo_ReplaceSpecType.DiscardUnknown(m)
}

var xxx_messageInfo_ReplaceSpecType proto.InternalMessageInfo

type isReplaceSpecType_LocationChoice interface {
	isReplaceSpecType_LocationChoice()
	Equal(interface{}) bool
	MarshalTo([]byte) (int, error)
	Size() int
}

type ReplaceSpecType_Global struct {
	Global *schema.Empty `protobuf:"bytes,2,opt,name=global,proto3,oneof" json:"global,omitempty"`
}
type ReplaceSpecType_CustomGeoLocationSelector struct {
	CustomGeoLocationSelector *schema.LabelSelectorType `protobuf:"bytes,3,opt,name=custom_geo_location_selector,json=customGeoLocationSelector,proto3,oneof" json:"custom_geo_location_selector,omitempty"`
}

func (*ReplaceSpecType_Global) isReplaceSpecType_LocationChoice()                    {}
func (*ReplaceSpecType_CustomGeoLocationSelector) isReplaceSpecType_LocationChoice() {}

func (m *ReplaceSpecType) GetLocationChoice() isReplaceSpecType_LocationChoice {
	if m != nil {
		return m.LocationChoice
	}
	return nil
}

func (m *ReplaceSpecType) GetGlobal() *schema.Empty {
	if x, ok := m.GetLocationChoice().(*ReplaceSpecType_Global); ok {
		return x.Global
	}
	return nil
}

func (m *ReplaceSpecType) GetCustomGeoLocationSelector() *schema.LabelSelectorType {
	if x, ok := m.GetLocationChoice().(*ReplaceSpecType_CustomGeoLocationSelector); ok {
		return x.CustomGeoLocationSelector
	}
	return nil
}

// XXX_OneofWrappers is for the internal use of the proto package.
func (*ReplaceSpecType) XXX_OneofWrappers() []interface{} {
	return []interface{}{
		(*ReplaceSpecType_Global)(nil),
		(*ReplaceSpecType_CustomGeoLocationSelector)(nil),
	}
}

// Geolocation Set
//
// x-displayName: "Get Geolocation Set"
// Reads a Geolocation
type GetSpecType struct {
	// Types that are valid to be assigned to LocationChoice:
	//	*GetSpecType_Global
	//	*GetSpecType_CustomGeoLocationSelector
	LocationChoice   isGetSpecType_LocationChoice `protobuf_oneof:"location_choice"`
	DnsLoadBalancers []*views.ObjectRefType       `protobuf:"bytes,4,rep,name=dns_load_balancers,json=dnsLoadBalancers,proto3" json:"dns_load_balancers,omitempty"`
}

func (m *GetSpecType) Reset()      { *m = GetSpecType{} }
func (*GetSpecType) ProtoMessage() {}
func (*GetSpecType) Descriptor() ([]byte, []int) {
	return fileDescriptor_54da32594f6f9b9b, []int{3}
}
func (m *GetSpecType) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *GetSpecType) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	b = b[:cap(b)]
	n, err := m.MarshalToSizedBuffer(b)
	if err != nil {
		return nil, err
	}
	return b[:n], nil
}
func (m *GetSpecType) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GetSpecType.Merge(m, src)
}
func (m *GetSpecType) XXX_Size() int {
	return m.Size()
}
func (m *GetSpecType) XXX_DiscardUnknown() {
	xxx_messageInfo_GetSpecType.DiscardUnknown(m)
}

var xxx_messageInfo_GetSpecType proto.InternalMessageInfo

type isGetSpecType_LocationChoice interface {
	isGetSpecType_LocationChoice()
	Equal(interface{}) bool
	MarshalTo([]byte) (int, error)
	Size() int
}

type GetSpecType_Global struct {
	Global *schema.Empty `protobuf:"bytes,2,opt,name=global,proto3,oneof" json:"global,omitempty"`
}
type GetSpecType_CustomGeoLocationSelector struct {
	CustomGeoLocationSelector *schema.LabelSelectorType `protobuf:"bytes,3,opt,name=custom_geo_location_selector,json=customGeoLocationSelector,proto3,oneof" json:"custom_geo_location_selector,omitempty"`
}

func (*GetSpecType_Global) isGetSpecType_LocationChoice()                    {}
func (*GetSpecType_CustomGeoLocationSelector) isGetSpecType_LocationChoice() {}

func (m *GetSpecType) GetLocationChoice() isGetSpecType_LocationChoice {
	if m != nil {
		return m.LocationChoice
	}
	return nil
}

func (m *GetSpecType) GetGlobal() *schema.Empty {
	if x, ok := m.GetLocationChoice().(*GetSpecType_Global); ok {
		return x.Global
	}
	return nil
}

func (m *GetSpecType) GetCustomGeoLocationSelector() *schema.LabelSelectorType {
	if x, ok := m.GetLocationChoice().(*GetSpecType_CustomGeoLocationSelector); ok {
		return x.CustomGeoLocationSelector
	}
	return nil
}

func (m *GetSpecType) GetDnsLoadBalancers() []*views.ObjectRefType {
	if m != nil {
		return m.DnsLoadBalancers
	}
	return nil
}

// XXX_OneofWrappers is for the internal use of the proto package.
func (*GetSpecType) XXX_OneofWrappers() []interface{} {
	return []interface{}{
		(*GetSpecType_Global)(nil),
		(*GetSpecType_CustomGeoLocationSelector)(nil),
	}
}

func init() {
	proto.RegisterType((*GlobalSpecType)(nil), "ves.io.schema.geo_location_set.GlobalSpecType")
	proto.RegisterType((*CreateSpecType)(nil), "ves.io.schema.geo_location_set.CreateSpecType")
	proto.RegisterType((*ReplaceSpecType)(nil), "ves.io.schema.geo_location_set.ReplaceSpecType")
	proto.RegisterType((*GetSpecType)(nil), "ves.io.schema.geo_location_set.GetSpecType")
}

func init() {
	proto.RegisterFile("ves.io/schema/geo_location_set/types.proto", fileDescriptor_54da32594f6f9b9b)
}

var fileDescriptor_54da32594f6f9b9b = []byte{
	// 562 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xdc, 0x54, 0xbf, 0x6f, 0xd3, 0x40,
	0x14, 0xf6, 0x4b, 0x42, 0x8a, 0x5c, 0xa9, 0x3f, 0x4c, 0x87, 0x34, 0x54, 0x47, 0x94, 0x01, 0x55,
	0x88, 0xd8, 0x22, 0xdd, 0x3a, 0x74, 0x08, 0x42, 0xa9, 0x50, 0x24, 0x50, 0xda, 0x89, 0xc5, 0x3a,
	0x9f, 0x5f, 0x1c, 0x83, 0x93, 0x67, 0xd9, 0x97, 0x40, 0x06, 0x24, 0xc4, 0x1f, 0x80, 0x98, 0xf9,
	0x0b, 0x10, 0x0b, 0x7f, 0x40, 0x3a, 0x30, 0x22, 0xa6, 0x8c, 0x19, 0x1b, 0x67, 0x61, 0xac, 0x18,
	0x99, 0x50, 0x1d, 0x07, 0x1a, 0x07, 0x18, 0x0a, 0x03, 0x62, 0xbb, 0xbb, 0xef, 0x7b, 0xdf, 0xbb,
	0xef, 0xb3, 0xef, 0xa9, 0xb7, 0xfa, 0x18, 0xea, 0x2e, 0x19, 0xa1, 0x68, 0x63, 0x87, 0x1b, 0x0e,
	0x92, 0xe9, 0x91, 0xe0, 0xd2, 0xa5, 0xae, 0x19, 0xa2, 0x34, 0xe4, 0xc0, 0xc7, 0x50, 0xf7, 0x03,
	0x92, 0xa4, 0xb1, 0x19, 0x57, 0x9f, 0x71, 0xf5, 0x34, 0xb7, 0x58, 0x71, 0x5c, 0xd9, 0xee, 0x59,
	0xba, 0xa0, 0x8e, 0xe1, 0x90, 0x43, 0x46, 0x5c, 0x66, 0xf5, 0x5a, 0xf1, 0x2e, 0xde, 0xc4, 0xab,
	0x99, 0x5c, 0x71, 0xdb, 0x21, 0x72, 0x3c, 0xfc, 0xc1, 0xe2, 0xdd, 0x41, 0x02, 0x5d, 0x5f, 0xbc,
	0x15, 0xf9, 0xe7, 0x3d, 0xc2, 0x79, 0xdd, 0x22, 0x78, 0xe1, 0x86, 0xc5, 0x9d, 0x45, 0xa8, 0xcf,
	0x3d, 0xd7, 0xe6, 0x12, 0x13, 0xb4, 0x94, 0x42, 0x5d, 0x7c, 0x6a, 0x2e, 0x4a, 0xdf, 0x58, 0x66,
	0x84, 0x17, 0x1b, 0x94, 0x47, 0x19, 0x75, 0xad, 0xee, 0x91, 0xc5, 0xbd, 0x23, 0x1f, 0xc5, 0xf1,
	0xc0, 0x47, 0x4d, 0x57, 0xf3, 0x4e, 0x7c, 0x52, 0xc8, 0x94, 0x60, 0x77, 0xb5, 0xba, 0xa5, 0x2f,
	0xc6, 0x74, 0xaf, 0xe3, 0xcb, 0xc1, 0xa1, 0xd2, 0x4c, 0x58, 0x5a, 0x5f, 0xdd, 0x11, 0xbd, 0x50,
	0x52, 0xc7, 0x4c, 0x05, 0xe8, 0xa1, 0x90, 0x14, 0x14, 0xb2, 0xb1, 0x4a, 0x29, 0xa5, 0xd2, 0xe0,
	0x16, 0x7a, 0x47, 0x09, 0xe7, 0xbc, 0x6f, 0x6d, 0xf3, 0xcd, 0x09, 0x64, 0x55, 0x58, 0x89, 0x4e,
	0x20, 0xaf, 0xe6, 0xae, 0xe4, 0x61, 0xe5, 0x50, 0x69, 0x6e, 0xcf, 0xa4, 0xeb, 0x48, 0x8d, 0x44,
	0x78, 0x5e, 0xa3, 0xb5, 0x54, 0xcd, 0xee, 0x86, 0xa6, 0x47, 0xdc, 0x36, 0x2d, 0xee, 0xf1, 0xae,
	0xc0, 0x20, 0x2c, 0xe4, 0x4a, 0xd9, 0xdd, 0xd5, 0x6a, 0x39, 0xd5, 0x2d, 0x36, 0xae, 0x3f, 0xb0,
	0x1e, 0xa3, 0x90, 0x4d, 0x6c, 0xc5, 0xfd, 0xb6, 0xde, 0x3d, 0xdf, 0x5c, 0x12, 0x68, 0x6e, 0xd8,
	0xdd, 0xb0, 0x41, 0xdc, 0xae, 0xcd, 0x15, 0xf7, 0x73, 0x5f, 0x0e, 0xe0, 0x4e, 0xad, 0xac, 0xae,
	0x7f, 0xb7, 0x26, 0xda, 0xe4, 0x0a, 0xd4, 0xd6, 0x3f, 0x0c, 0x21, 0x33, 0x1a, 0x02, 0x44, 0x43,
	0xc8, 0x56, 0x6f, 0xef, 0xdd, 0xcf, 0x5d, 0x85, 0x8d, 0x4c, 0xf9, 0x14, 0xd4, 0xb5, 0xbb, 0x01,
	0x72, 0x89, 0x97, 0x8e, 0x54, 0xfc, 0x9d, 0x48, 0x7f, 0x9b, 0xdf, 0xfe, 0xe6, 0xa7, 0x83, 0xd4,
	0xa7, 0xaf, 0xdd, 0x5c, 0x36, 0x79, 0xed, 0xe5, 0x57, 0x48, 0x1f, 0x96, 0x27, 0xa0, 0xae, 0x37,
	0xd1, 0xf7, 0xb8, 0xf8, 0x7f, 0x3d, 0xbe, 0xcf, 0xa8, 0xab, 0x75, 0x94, 0xff, 0xb4, 0x3f, 0xed,
	0xe1, 0x9f, 0xbd, 0x81, 0x9f, 0xfc, 0xed, 0x97, 0x4f, 0xac, 0xf6, 0x0a, 0x46, 0x13, 0xa6, 0x8c,
	0x27, 0x4c, 0x39, 0x9b, 0x30, 0x78, 0x11, 0x31, 0x78, 0x1b, 0x31, 0xf8, 0x18, 0x31, 0x18, 0x45,
	0x0c, 0xc6, 0x11, 0x83, 0xd3, 0x88, 0xc1, 0xe7, 0x88, 0x29, 0x67, 0x11, 0x83, 0xd7, 0x53, 0xa6,
	0x8c, 0xa6, 0x4c, 0x19, 0x4f, 0x99, 0xf2, 0xe8, 0xd8, 0x21, 0xff, 0x89, 0xa3, 0xf7, 0xc9, 0x93,
	0x18, 0x04, 0x5c, 0xef, 0x85, 0x46, 0xbc, 0x68, 0x51, 0xd0, 0xa9, 0xf8, 0x01, 0xf5, 0x5d, 0x1b,
	0x83, 0xca, 0x1c, 0x36, 0x7c, 0xcb, 0x21, 0x03, 0x9f, 0xc9, 0x64, 0xac, 0xfd, 0x62, 0xd6, 0x5b,
	0xf9, 0x78, 0xc6, 0xed, 0x7d, 0x0b, 0x00, 0x00, 0xff, 0xff, 0xb5, 0x42, 0x30, 0xea, 0x14, 0x06,
	0x00, 0x00,
}

func (this *GlobalSpecType) Equal(that interface{}) bool {
	if that == nil {
		return this == nil
	}

	that1, ok := that.(*GlobalSpecType)
	if !ok {
		that2, ok := that.(GlobalSpecType)
		if ok {
			that1 = &that2
		} else {
			return false
		}
	}
	if that1 == nil {
		return this == nil
	} else if this == nil {
		return false
	}
	if that1.LocationChoice == nil {
		if this.LocationChoice != nil {
			return false
		}
	} else if this.LocationChoice == nil {
		return false
	} else if !this.LocationChoice.Equal(that1.LocationChoice) {
		return false
	}
	if len(this.DnsLoadBalancers) != len(that1.DnsLoadBalancers) {
		return false
	}
	for i := range this.DnsLoadBalancers {
		if !this.DnsLoadBalancers[i].Equal(that1.DnsLoadBalancers[i]) {
			return false
		}
	}
	return true
}
func (this *GlobalSpecType_Global) Equal(that interface{}) bool {
	if that == nil {
		return this == nil
	}

	that1, ok := that.(*GlobalSpecType_Global)
	if !ok {
		that2, ok := that.(GlobalSpecType_Global)
		if ok {
			that1 = &that2
		} else {
			return false
		}
	}
	if that1 == nil {
		return this == nil
	} else if this == nil {
		return false
	}
	if !this.Global.Equal(that1.Global) {
		return false
	}
	return true
}
func (this *GlobalSpecType_CustomGeoLocationSelector) Equal(that interface{}) bool {
	if that == nil {
		return this == nil
	}

	that1, ok := that.(*GlobalSpecType_CustomGeoLocationSelector)
	if !ok {
		that2, ok := that.(GlobalSpecType_CustomGeoLocationSelector)
		if ok {
			that1 = &that2
		} else {
			return false
		}
	}
	if that1 == nil {
		return this == nil
	} else if this == nil {
		return false
	}
	if !this.CustomGeoLocationSelector.Equal(that1.CustomGeoLocationSelector) {
		return false
	}
	return true
}
func (this *CreateSpecType) Equal(that interface{}) bool {
	if that == nil {
		return this == nil
	}

	that1, ok := that.(*CreateSpecType)
	if !ok {
		that2, ok := that.(CreateSpecType)
		if ok {
			that1 = &that2
		} else {
			return false
		}
	}
	if that1 == nil {
		return this == nil
	} else if this == nil {
		return false
	}
	if that1.LocationChoice == nil {
		if this.LocationChoice != nil {
			return false
		}
	} else if this.LocationChoice == nil {
		return false
	} else if !this.LocationChoice.Equal(that1.LocationChoice) {
		return false
	}
	return true
}
func (this *CreateSpecType_Global) Equal(that interface{}) bool {
	if that == nil {
		return this == nil
	}

	that1, ok := that.(*CreateSpecType_Global)
	if !ok {
		that2, ok := that.(CreateSpecType_Global)
		if ok {
			that1 = &that2
		} else {
			return false
		}
	}
	if that1 == nil {
		return this == nil
	} else if this == nil {
		return false
	}
	if !this.Global.Equal(that1.Global) {
		return false
	}
	return true
}
func (this *CreateSpecType_CustomGeoLocationSelector) Equal(that interface{}) bool {
	if that == nil {
		return this == nil
	}

	that1, ok := that.(*CreateSpecType_CustomGeoLocationSelector)
	if !ok {
		that2, ok := that.(CreateSpecType_CustomGeoLocationSelector)
		if ok {
			that1 = &that2
		} else {
			return false
		}
	}
	if that1 == nil {
		return this == nil
	} else if this == nil {
		return false
	}
	if !this.CustomGeoLocationSelector.Equal(that1.CustomGeoLocationSelector) {
		return false
	}
	return true
}
func (this *ReplaceSpecType) Equal(that interface{}) bool {
	if that == nil {
		return this == nil
	}

	that1, ok := that.(*ReplaceSpecType)
	if !ok {
		that2, ok := that.(ReplaceSpecType)
		if ok {
			that1 = &that2
		} else {
			return false
		}
	}
	if that1 == nil {
		return this == nil
	} else if this == nil {
		return false
	}
	if that1.LocationChoice == nil {
		if this.LocationChoice != nil {
			return false
		}
	} else if this.LocationChoice == nil {
		return false
	} else if !this.LocationChoice.Equal(that1.LocationChoice) {
		return false
	}
	return true
}
func (this *ReplaceSpecType_Global) Equal(that interface{}) bool {
	if that == nil {
		return this == nil
	}

	that1, ok := that.(*ReplaceSpecType_Global)
	if !ok {
		that2, ok := that.(ReplaceSpecType_Global)
		if ok {
			that1 = &that2
		} else {
			return false
		}
	}
	if that1 == nil {
		return this == nil
	} else if this == nil {
		return false
	}
	if !this.Global.Equal(that1.Global) {
		return false
	}
	return true
}
func (this *ReplaceSpecType_CustomGeoLocationSelector) Equal(that interface{}) bool {
	if that == nil {
		return this == nil
	}

	that1, ok := that.(*ReplaceSpecType_CustomGeoLocationSelector)
	if !ok {
		that2, ok := that.(ReplaceSpecType_CustomGeoLocationSelector)
		if ok {
			that1 = &that2
		} else {
			return false
		}
	}
	if that1 == nil {
		return this == nil
	} else if this == nil {
		return false
	}
	if !this.CustomGeoLocationSelector.Equal(that1.CustomGeoLocationSelector) {
		return false
	}
	return true
}
func (this *GetSpecType) Equal(that interface{}) bool {
	if that == nil {
		return this == nil
	}

	that1, ok := that.(*GetSpecType)
	if !ok {
		that2, ok := that.(GetSpecType)
		if ok {
			that1 = &that2
		} else {
			return false
		}
	}
	if that1 == nil {
		return this == nil
	} else if this == nil {
		return false
	}
	if that1.LocationChoice == nil {
		if this.LocationChoice != nil {
			return false
		}
	} else if this.LocationChoice == nil {
		return false
	} else if !this.LocationChoice.Equal(that1.LocationChoice) {
		return false
	}
	if len(this.DnsLoadBalancers) != len(that1.DnsLoadBalancers) {
		return false
	}
	for i := range this.DnsLoadBalancers {
		if !this.DnsLoadBalancers[i].Equal(that1.DnsLoadBalancers[i]) {
			return false
		}
	}
	return true
}
func (this *GetSpecType_Global) Equal(that interface{}) bool {
	if that == nil {
		return this == nil
	}

	that1, ok := that.(*GetSpecType_Global)
	if !ok {
		that2, ok := that.(GetSpecType_Global)
		if ok {
			that1 = &that2
		} else {
			return false
		}
	}
	if that1 == nil {
		return this == nil
	} else if this == nil {
		return false
	}
	if !this.Global.Equal(that1.Global) {
		return false
	}
	return true
}
func (this *GetSpecType_CustomGeoLocationSelector) Equal(that interface{}) bool {
	if that == nil {
		return this == nil
	}

	that1, ok := that.(*GetSpecType_CustomGeoLocationSelector)
	if !ok {
		that2, ok := that.(GetSpecType_CustomGeoLocationSelector)
		if ok {
			that1 = &that2
		} else {
			return false
		}
	}
	if that1 == nil {
		return this == nil
	} else if this == nil {
		return false
	}
	if !this.CustomGeoLocationSelector.Equal(that1.CustomGeoLocationSelector) {
		return false
	}
	return true
}
func (this *GlobalSpecType) GoString() string {
	if this == nil {
		return "nil"
	}
	s := make([]string, 0, 7)
	s = append(s, "&geo_location_set.GlobalSpecType{")
	if this.LocationChoice != nil {
		s = append(s, "LocationChoice: "+fmt.Sprintf("%#v", this.LocationChoice)+",\n")
	}
	if this.DnsLoadBalancers != nil {
		s = append(s, "DnsLoadBalancers: "+fmt.Sprintf("%#v", this.DnsLoadBalancers)+",\n")
	}
	s = append(s, "}")
	return strings.Join(s, "")
}
func (this *GlobalSpecType_Global) GoString() string {
	if this == nil {
		return "nil"
	}
	s := strings.Join([]string{`&geo_location_set.GlobalSpecType_Global{` +
		`Global:` + fmt.Sprintf("%#v", this.Global) + `}`}, ", ")
	return s
}
func (this *GlobalSpecType_CustomGeoLocationSelector) GoString() string {
	if this == nil {
		return "nil"
	}
	s := strings.Join([]string{`&geo_location_set.GlobalSpecType_CustomGeoLocationSelector{` +
		`CustomGeoLocationSelector:` + fmt.Sprintf("%#v", this.CustomGeoLocationSelector) + `}`}, ", ")
	return s
}
func (this *CreateSpecType) GoString() string {
	if this == nil {
		return "nil"
	}
	s := make([]string, 0, 6)
	s = append(s, "&geo_location_set.CreateSpecType{")
	if this.LocationChoice != nil {
		s = append(s, "LocationChoice: "+fmt.Sprintf("%#v", this.LocationChoice)+",\n")
	}
	s = append(s, "}")
	return strings.Join(s, "")
}
func (this *CreateSpecType_Global) GoString() string {
	if this == nil {
		return "nil"
	}
	s := strings.Join([]string{`&geo_location_set.CreateSpecType_Global{` +
		`Global:` + fmt.Sprintf("%#v", this.Global) + `}`}, ", ")
	return s
}
func (this *CreateSpecType_CustomGeoLocationSelector) GoString() string {
	if this == nil {
		return "nil"
	}
	s := strings.Join([]string{`&geo_location_set.CreateSpecType_CustomGeoLocationSelector{` +
		`CustomGeoLocationSelector:` + fmt.Sprintf("%#v", this.CustomGeoLocationSelector) + `}`}, ", ")
	return s
}
func (this *ReplaceSpecType) GoString() string {
	if this == nil {
		return "nil"
	}
	s := make([]string, 0, 6)
	s = append(s, "&geo_location_set.ReplaceSpecType{")
	if this.LocationChoice != nil {
		s = append(s, "LocationChoice: "+fmt.Sprintf("%#v", this.LocationChoice)+",\n")
	}
	s = append(s, "}")
	return strings.Join(s, "")
}
func (this *ReplaceSpecType_Global) GoString() string {
	if this == nil {
		return "nil"
	}
	s := strings.Join([]string{`&geo_location_set.ReplaceSpecType_Global{` +
		`Global:` + fmt.Sprintf("%#v", this.Global) + `}`}, ", ")
	return s
}
func (this *ReplaceSpecType_CustomGeoLocationSelector) GoString() string {
	if this == nil {
		return "nil"
	}
	s := strings.Join([]string{`&geo_location_set.ReplaceSpecType_CustomGeoLocationSelector{` +
		`CustomGeoLocationSelector:` + fmt.Sprintf("%#v", this.CustomGeoLocationSelector) + `}`}, ", ")
	return s
}
func (this *GetSpecType) GoString() string {
	if this == nil {
		return "nil"
	}
	s := make([]string, 0, 7)
	s = append(s, "&geo_location_set.GetSpecType{")
	if this.LocationChoice != nil {
		s = append(s, "LocationChoice: "+fmt.Sprintf("%#v", this.LocationChoice)+",\n")
	}
	if this.DnsLoadBalancers != nil {
		s = append(s, "DnsLoadBalancers: "+fmt.Sprintf("%#v", this.DnsLoadBalancers)+",\n")
	}
	s = append(s, "}")
	return strings.Join(s, "")
}
func (this *GetSpecType_Global) GoString() string {
	if this == nil {
		return "nil"
	}
	s := strings.Join([]string{`&geo_location_set.GetSpecType_Global{` +
		`Global:` + fmt.Sprintf("%#v", this.Global) + `}`}, ", ")
	return s
}
func (this *GetSpecType_CustomGeoLocationSelector) GoString() string {
	if this == nil {
		return "nil"
	}
	s := strings.Join([]string{`&geo_location_set.GetSpecType_CustomGeoLocationSelector{` +
		`CustomGeoLocationSelector:` + fmt.Sprintf("%#v", this.CustomGeoLocationSelector) + `}`}, ", ")
	return s
}
func valueToGoStringTypes(v interface{}, typ string) string {
	rv := reflect.ValueOf(v)
	if rv.IsNil() {
		return "nil"
	}
	pv := reflect.Indirect(rv).Interface()
	return fmt.Sprintf("func(v %v) *%v { return &v } ( %#v )", typ, typ, pv)
}
func (m *GlobalSpecType) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *GlobalSpecType) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *GlobalSpecType) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	if len(m.DnsLoadBalancers) > 0 {
		for iNdEx := len(m.DnsLoadBalancers) - 1; iNdEx >= 0; iNdEx-- {
			{
				size, err := m.DnsLoadBalancers[iNdEx].MarshalToSizedBuffer(dAtA[:i])
				if err != nil {
					return 0, err
				}
				i -= size
				i = encodeVarintTypes(dAtA, i, uint64(size))
			}
			i--
			dAtA[i] = 0x22
		}
	}
	if m.LocationChoice != nil {
		{
			size := m.LocationChoice.Size()
			i -= size
			if _, err := m.LocationChoice.MarshalTo(dAtA[i:]); err != nil {
				return 0, err
			}
		}
	}
	return len(dAtA) - i, nil
}

func (m *GlobalSpecType_Global) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *GlobalSpecType_Global) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	if m.Global != nil {
		{
			size, err := m.Global.MarshalToSizedBuffer(dAtA[:i])
			if err != nil {
				return 0, err
			}
			i -= size
			i = encodeVarintTypes(dAtA, i, uint64(size))
		}
		i--
		dAtA[i] = 0x12
	}
	return len(dAtA) - i, nil
}
func (m *GlobalSpecType_CustomGeoLocationSelector) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *GlobalSpecType_CustomGeoLocationSelector) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	if m.CustomGeoLocationSelector != nil {
		{
			size, err := m.CustomGeoLocationSelector.MarshalToSizedBuffer(dAtA[:i])
			if err != nil {
				return 0, err
			}
			i -= size
			i = encodeVarintTypes(dAtA, i, uint64(size))
		}
		i--
		dAtA[i] = 0x1a
	}
	return len(dAtA) - i, nil
}
func (m *CreateSpecType) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *CreateSpecType) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *CreateSpecType) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	if m.LocationChoice != nil {
		{
			size := m.LocationChoice.Size()
			i -= size
			if _, err := m.LocationChoice.MarshalTo(dAtA[i:]); err != nil {
				return 0, err
			}
		}
	}
	return len(dAtA) - i, nil
}

func (m *CreateSpecType_Global) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *CreateSpecType_Global) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	if m.Global != nil {
		{
			size, err := m.Global.MarshalToSizedBuffer(dAtA[:i])
			if err != nil {
				return 0, err
			}
			i -= size
			i = encodeVarintTypes(dAtA, i, uint64(size))
		}
		i--
		dAtA[i] = 0x12
	}
	return len(dAtA) - i, nil
}
func (m *CreateSpecType_CustomGeoLocationSelector) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *CreateSpecType_CustomGeoLocationSelector) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	if m.CustomGeoLocationSelector != nil {
		{
			size, err := m.CustomGeoLocationSelector.MarshalToSizedBuffer(dAtA[:i])
			if err != nil {
				return 0, err
			}
			i -= size
			i = encodeVarintTypes(dAtA, i, uint64(size))
		}
		i--
		dAtA[i] = 0x1a
	}
	return len(dAtA) - i, nil
}
func (m *ReplaceSpecType) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *ReplaceSpecType) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *ReplaceSpecType) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	if m.LocationChoice != nil {
		{
			size := m.LocationChoice.Size()
			i -= size
			if _, err := m.LocationChoice.MarshalTo(dAtA[i:]); err != nil {
				return 0, err
			}
		}
	}
	return len(dAtA) - i, nil
}

func (m *ReplaceSpecType_Global) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *ReplaceSpecType_Global) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	if m.Global != nil {
		{
			size, err := m.Global.MarshalToSizedBuffer(dAtA[:i])
			if err != nil {
				return 0, err
			}
			i -= size
			i = encodeVarintTypes(dAtA, i, uint64(size))
		}
		i--
		dAtA[i] = 0x12
	}
	return len(dAtA) - i, nil
}
func (m *ReplaceSpecType_CustomGeoLocationSelector) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *ReplaceSpecType_CustomGeoLocationSelector) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	if m.CustomGeoLocationSelector != nil {
		{
			size, err := m.CustomGeoLocationSelector.MarshalToSizedBuffer(dAtA[:i])
			if err != nil {
				return 0, err
			}
			i -= size
			i = encodeVarintTypes(dAtA, i, uint64(size))
		}
		i--
		dAtA[i] = 0x1a
	}
	return len(dAtA) - i, nil
}
func (m *GetSpecType) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *GetSpecType) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *GetSpecType) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	if len(m.DnsLoadBalancers) > 0 {
		for iNdEx := len(m.DnsLoadBalancers) - 1; iNdEx >= 0; iNdEx-- {
			{
				size, err := m.DnsLoadBalancers[iNdEx].MarshalToSizedBuffer(dAtA[:i])
				if err != nil {
					return 0, err
				}
				i -= size
				i = encodeVarintTypes(dAtA, i, uint64(size))
			}
			i--
			dAtA[i] = 0x22
		}
	}
	if m.LocationChoice != nil {
		{
			size := m.LocationChoice.Size()
			i -= size
			if _, err := m.LocationChoice.MarshalTo(dAtA[i:]); err != nil {
				return 0, err
			}
		}
	}
	return len(dAtA) - i, nil
}

func (m *GetSpecType_Global) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *GetSpecType_Global) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	if m.Global != nil {
		{
			size, err := m.Global.MarshalToSizedBuffer(dAtA[:i])
			if err != nil {
				return 0, err
			}
			i -= size
			i = encodeVarintTypes(dAtA, i, uint64(size))
		}
		i--
		dAtA[i] = 0x12
	}
	return len(dAtA) - i, nil
}
func (m *GetSpecType_CustomGeoLocationSelector) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *GetSpecType_CustomGeoLocationSelector) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	if m.CustomGeoLocationSelector != nil {
		{
			size, err := m.CustomGeoLocationSelector.MarshalToSizedBuffer(dAtA[:i])
			if err != nil {
				return 0, err
			}
			i -= size
			i = encodeVarintTypes(dAtA, i, uint64(size))
		}
		i--
		dAtA[i] = 0x1a
	}
	return len(dAtA) - i, nil
}
func encodeVarintTypes(dAtA []byte, offset int, v uint64) int {
	offset -= sovTypes(v)
	base := offset
	for v >= 1<<7 {
		dAtA[offset] = uint8(v&0x7f | 0x80)
		v >>= 7
		offset++
	}
	dAtA[offset] = uint8(v)
	return base
}
func (m *GlobalSpecType) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	if m.LocationChoice != nil {
		n += m.LocationChoice.Size()
	}
	if len(m.DnsLoadBalancers) > 0 {
		for _, e := range m.DnsLoadBalancers {
			l = e.Size()
			n += 1 + l + sovTypes(uint64(l))
		}
	}
	return n
}

func (m *GlobalSpecType_Global) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	if m.Global != nil {
		l = m.Global.Size()
		n += 1 + l + sovTypes(uint64(l))
	}
	return n
}
func (m *GlobalSpecType_CustomGeoLocationSelector) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	if m.CustomGeoLocationSelector != nil {
		l = m.CustomGeoLocationSelector.Size()
		n += 1 + l + sovTypes(uint64(l))
	}
	return n
}
func (m *CreateSpecType) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	if m.LocationChoice != nil {
		n += m.LocationChoice.Size()
	}
	return n
}

func (m *CreateSpecType_Global) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	if m.Global != nil {
		l = m.Global.Size()
		n += 1 + l + sovTypes(uint64(l))
	}
	return n
}
func (m *CreateSpecType_CustomGeoLocationSelector) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	if m.CustomGeoLocationSelector != nil {
		l = m.CustomGeoLocationSelector.Size()
		n += 1 + l + sovTypes(uint64(l))
	}
	return n
}
func (m *ReplaceSpecType) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	if m.LocationChoice != nil {
		n += m.LocationChoice.Size()
	}
	return n
}

func (m *ReplaceSpecType_Global) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	if m.Global != nil {
		l = m.Global.Size()
		n += 1 + l + sovTypes(uint64(l))
	}
	return n
}
func (m *ReplaceSpecType_CustomGeoLocationSelector) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	if m.CustomGeoLocationSelector != nil {
		l = m.CustomGeoLocationSelector.Size()
		n += 1 + l + sovTypes(uint64(l))
	}
	return n
}
func (m *GetSpecType) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	if m.LocationChoice != nil {
		n += m.LocationChoice.Size()
	}
	if len(m.DnsLoadBalancers) > 0 {
		for _, e := range m.DnsLoadBalancers {
			l = e.Size()
			n += 1 + l + sovTypes(uint64(l))
		}
	}
	return n
}

func (m *GetSpecType_Global) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	if m.Global != nil {
		l = m.Global.Size()
		n += 1 + l + sovTypes(uint64(l))
	}
	return n
}
func (m *GetSpecType_CustomGeoLocationSelector) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	if m.CustomGeoLocationSelector != nil {
		l = m.CustomGeoLocationSelector.Size()
		n += 1 + l + sovTypes(uint64(l))
	}
	return n
}

func sovTypes(x uint64) (n int) {
	return (math_bits.Len64(x|1) + 6) / 7
}
func sozTypes(x uint64) (n int) {
	return sovTypes(uint64((x << 1) ^ uint64((int64(x) >> 63))))
}
func (this *GlobalSpecType) String() string {
	if this == nil {
		return "nil"
	}
	repeatedStringForDnsLoadBalancers := "[]*ObjectRefType{"
	for _, f := range this.DnsLoadBalancers {
		repeatedStringForDnsLoadBalancers += strings.Replace(fmt.Sprintf("%v", f), "ObjectRefType", "views.ObjectRefType", 1) + ","
	}
	repeatedStringForDnsLoadBalancers += "}"
	s := strings.Join([]string{`&GlobalSpecType{`,
		`LocationChoice:` + fmt.Sprintf("%v", this.LocationChoice) + `,`,
		`DnsLoadBalancers:` + repeatedStringForDnsLoadBalancers + `,`,
		`}`,
	}, "")
	return s
}
func (this *GlobalSpecType_Global) String() string {
	if this == nil {
		return "nil"
	}
	s := strings.Join([]string{`&GlobalSpecType_Global{`,
		`Global:` + strings.Replace(fmt.Sprintf("%v", this.Global), "Empty", "schema.Empty", 1) + `,`,
		`}`,
	}, "")
	return s
}
func (this *GlobalSpecType_CustomGeoLocationSelector) String() string {
	if this == nil {
		return "nil"
	}
	s := strings.Join([]string{`&GlobalSpecType_CustomGeoLocationSelector{`,
		`CustomGeoLocationSelector:` + strings.Replace(fmt.Sprintf("%v", this.CustomGeoLocationSelector), "LabelSelectorType", "schema.LabelSelectorType", 1) + `,`,
		`}`,
	}, "")
	return s
}
func (this *CreateSpecType) String() string {
	if this == nil {
		return "nil"
	}
	s := strings.Join([]string{`&CreateSpecType{`,
		`LocationChoice:` + fmt.Sprintf("%v", this.LocationChoice) + `,`,
		`}`,
	}, "")
	return s
}
func (this *CreateSpecType_Global) String() string {
	if this == nil {
		return "nil"
	}
	s := strings.Join([]string{`&CreateSpecType_Global{`,
		`Global:` + strings.Replace(fmt.Sprintf("%v", this.Global), "Empty", "schema.Empty", 1) + `,`,
		`}`,
	}, "")
	return s
}
func (this *CreateSpecType_CustomGeoLocationSelector) String() string {
	if this == nil {
		return "nil"
	}
	s := strings.Join([]string{`&CreateSpecType_CustomGeoLocationSelector{`,
		`CustomGeoLocationSelector:` + strings.Replace(fmt.Sprintf("%v", this.CustomGeoLocationSelector), "LabelSelectorType", "schema.LabelSelectorType", 1) + `,`,
		`}`,
	}, "")
	return s
}
func (this *ReplaceSpecType) String() string {
	if this == nil {
		return "nil"
	}
	s := strings.Join([]string{`&ReplaceSpecType{`,
		`LocationChoice:` + fmt.Sprintf("%v", this.LocationChoice) + `,`,
		`}`,
	}, "")
	return s
}
func (this *ReplaceSpecType_Global) String() string {
	if this == nil {
		return "nil"
	}
	s := strings.Join([]string{`&ReplaceSpecType_Global{`,
		`Global:` + strings.Replace(fmt.Sprintf("%v", this.Global), "Empty", "schema.Empty", 1) + `,`,
		`}`,
	}, "")
	return s
}
func (this *ReplaceSpecType_CustomGeoLocationSelector) String() string {
	if this == nil {
		return "nil"
	}
	s := strings.Join([]string{`&ReplaceSpecType_CustomGeoLocationSelector{`,
		`CustomGeoLocationSelector:` + strings.Replace(fmt.Sprintf("%v", this.CustomGeoLocationSelector), "LabelSelectorType", "schema.LabelSelectorType", 1) + `,`,
		`}`,
	}, "")
	return s
}
func (this *GetSpecType) String() string {
	if this == nil {
		return "nil"
	}
	repeatedStringForDnsLoadBalancers := "[]*ObjectRefType{"
	for _, f := range this.DnsLoadBalancers {
		repeatedStringForDnsLoadBalancers += strings.Replace(fmt.Sprintf("%v", f), "ObjectRefType", "views.ObjectRefType", 1) + ","
	}
	repeatedStringForDnsLoadBalancers += "}"
	s := strings.Join([]string{`&GetSpecType{`,
		`LocationChoice:` + fmt.Sprintf("%v", this.LocationChoice) + `,`,
		`DnsLoadBalancers:` + repeatedStringForDnsLoadBalancers + `,`,
		`}`,
	}, "")
	return s
}
func (this *GetSpecType_Global) String() string {
	if this == nil {
		return "nil"
	}
	s := strings.Join([]string{`&GetSpecType_Global{`,
		`Global:` + strings.Replace(fmt.Sprintf("%v", this.Global), "Empty", "schema.Empty", 1) + `,`,
		`}`,
	}, "")
	return s
}
func (this *GetSpecType_CustomGeoLocationSelector) String() string {
	if this == nil {
		return "nil"
	}
	s := strings.Join([]string{`&GetSpecType_CustomGeoLocationSelector{`,
		`CustomGeoLocationSelector:` + strings.Replace(fmt.Sprintf("%v", this.CustomGeoLocationSelector), "LabelSelectorType", "schema.LabelSelectorType", 1) + `,`,
		`}`,
	}, "")
	return s
}
func valueToStringTypes(v interface{}) string {
	rv := reflect.ValueOf(v)
	if rv.IsNil() {
		return "nil"
	}
	pv := reflect.Indirect(rv).Interface()
	return fmt.Sprintf("*%v", pv)
}
func (m *GlobalSpecType) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowTypes
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: GlobalSpecType: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: GlobalSpecType: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 2:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Global", wireType)
			}
			var msglen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowTypes
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				msglen |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if msglen < 0 {
				return ErrInvalidLengthTypes
			}
			postIndex := iNdEx + msglen
			if postIndex < 0 {
				return ErrInvalidLengthTypes
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			v := &schema.Empty{}
			if err := v.Unmarshal(dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			m.LocationChoice = &GlobalSpecType_Global{v}
			iNdEx = postIndex
		case 3:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field CustomGeoLocationSelector", wireType)
			}
			var msglen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowTypes
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				msglen |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if msglen < 0 {
				return ErrInvalidLengthTypes
			}
			postIndex := iNdEx + msglen
			if postIndex < 0 {
				return ErrInvalidLengthTypes
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			v := &schema.LabelSelectorType{}
			if err := v.Unmarshal(dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			m.LocationChoice = &GlobalSpecType_CustomGeoLocationSelector{v}
			iNdEx = postIndex
		case 4:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field DnsLoadBalancers", wireType)
			}
			var msglen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowTypes
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				msglen |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if msglen < 0 {
				return ErrInvalidLengthTypes
			}
			postIndex := iNdEx + msglen
			if postIndex < 0 {
				return ErrInvalidLengthTypes
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.DnsLoadBalancers = append(m.DnsLoadBalancers, &views.ObjectRefType{})
			if err := m.DnsLoadBalancers[len(m.DnsLoadBalancers)-1].Unmarshal(dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			iNdEx = postIndex
		default:
			iNdEx = preIndex
			skippy, err := skipTypes(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if skippy < 0 {
				return ErrInvalidLengthTypes
			}
			if (iNdEx + skippy) < 0 {
				return ErrInvalidLengthTypes
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func (m *CreateSpecType) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowTypes
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: CreateSpecType: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: CreateSpecType: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 2:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Global", wireType)
			}
			var msglen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowTypes
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				msglen |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if msglen < 0 {
				return ErrInvalidLengthTypes
			}
			postIndex := iNdEx + msglen
			if postIndex < 0 {
				return ErrInvalidLengthTypes
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			v := &schema.Empty{}
			if err := v.Unmarshal(dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			m.LocationChoice = &CreateSpecType_Global{v}
			iNdEx = postIndex
		case 3:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field CustomGeoLocationSelector", wireType)
			}
			var msglen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowTypes
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				msglen |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if msglen < 0 {
				return ErrInvalidLengthTypes
			}
			postIndex := iNdEx + msglen
			if postIndex < 0 {
				return ErrInvalidLengthTypes
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			v := &schema.LabelSelectorType{}
			if err := v.Unmarshal(dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			m.LocationChoice = &CreateSpecType_CustomGeoLocationSelector{v}
			iNdEx = postIndex
		default:
			iNdEx = preIndex
			skippy, err := skipTypes(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if skippy < 0 {
				return ErrInvalidLengthTypes
			}
			if (iNdEx + skippy) < 0 {
				return ErrInvalidLengthTypes
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func (m *ReplaceSpecType) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowTypes
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: ReplaceSpecType: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: ReplaceSpecType: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 2:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Global", wireType)
			}
			var msglen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowTypes
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				msglen |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if msglen < 0 {
				return ErrInvalidLengthTypes
			}
			postIndex := iNdEx + msglen
			if postIndex < 0 {
				return ErrInvalidLengthTypes
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			v := &schema.Empty{}
			if err := v.Unmarshal(dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			m.LocationChoice = &ReplaceSpecType_Global{v}
			iNdEx = postIndex
		case 3:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field CustomGeoLocationSelector", wireType)
			}
			var msglen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowTypes
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				msglen |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if msglen < 0 {
				return ErrInvalidLengthTypes
			}
			postIndex := iNdEx + msglen
			if postIndex < 0 {
				return ErrInvalidLengthTypes
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			v := &schema.LabelSelectorType{}
			if err := v.Unmarshal(dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			m.LocationChoice = &ReplaceSpecType_CustomGeoLocationSelector{v}
			iNdEx = postIndex
		default:
			iNdEx = preIndex
			skippy, err := skipTypes(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if skippy < 0 {
				return ErrInvalidLengthTypes
			}
			if (iNdEx + skippy) < 0 {
				return ErrInvalidLengthTypes
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func (m *GetSpecType) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowTypes
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: GetSpecType: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: GetSpecType: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 2:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Global", wireType)
			}
			var msglen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowTypes
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				msglen |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if msglen < 0 {
				return ErrInvalidLengthTypes
			}
			postIndex := iNdEx + msglen
			if postIndex < 0 {
				return ErrInvalidLengthTypes
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			v := &schema.Empty{}
			if err := v.Unmarshal(dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			m.LocationChoice = &GetSpecType_Global{v}
			iNdEx = postIndex
		case 3:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field CustomGeoLocationSelector", wireType)
			}
			var msglen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowTypes
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				msglen |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if msglen < 0 {
				return ErrInvalidLengthTypes
			}
			postIndex := iNdEx + msglen
			if postIndex < 0 {
				return ErrInvalidLengthTypes
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			v := &schema.LabelSelectorType{}
			if err := v.Unmarshal(dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			m.LocationChoice = &GetSpecType_CustomGeoLocationSelector{v}
			iNdEx = postIndex
		case 4:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field DnsLoadBalancers", wireType)
			}
			var msglen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowTypes
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				msglen |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if msglen < 0 {
				return ErrInvalidLengthTypes
			}
			postIndex := iNdEx + msglen
			if postIndex < 0 {
				return ErrInvalidLengthTypes
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.DnsLoadBalancers = append(m.DnsLoadBalancers, &views.ObjectRefType{})
			if err := m.DnsLoadBalancers[len(m.DnsLoadBalancers)-1].Unmarshal(dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			iNdEx = postIndex
		default:
			iNdEx = preIndex
			skippy, err := skipTypes(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if skippy < 0 {
				return ErrInvalidLengthTypes
			}
			if (iNdEx + skippy) < 0 {
				return ErrInvalidLengthTypes
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func skipTypes(dAtA []byte) (n int, err error) {
	l := len(dAtA)
	iNdEx := 0
	depth := 0
	for iNdEx < l {
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return 0, ErrIntOverflowTypes
			}
			if iNdEx >= l {
				return 0, io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= (uint64(b) & 0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		wireType := int(wire & 0x7)
		switch wireType {
		case 0:
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return 0, ErrIntOverflowTypes
				}
				if iNdEx >= l {
					return 0, io.ErrUnexpectedEOF
				}
				iNdEx++
				if dAtA[iNdEx-1] < 0x80 {
					break
				}
			}
		case 1:
			iNdEx += 8
		case 2:
			var length int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return 0, ErrIntOverflowTypes
				}
				if iNdEx >= l {
					return 0, io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				length |= (int(b) & 0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if length < 0 {
				return 0, ErrInvalidLengthTypes
			}
			iNdEx += length
		case 3:
			depth++
		case 4:
			if depth == 0 {
				return 0, ErrUnexpectedEndOfGroupTypes
			}
			depth--
		case 5:
			iNdEx += 4
		default:
			return 0, fmt.Errorf("proto: illegal wireType %d", wireType)
		}
		if iNdEx < 0 {
			return 0, ErrInvalidLengthTypes
		}
		if depth == 0 {
			return iNdEx, nil
		}
	}
	return 0, io.ErrUnexpectedEOF
}

var (
	ErrInvalidLengthTypes        = fmt.Errorf("proto: negative length found during unmarshaling")
	ErrIntOverflowTypes          = fmt.Errorf("proto: integer overflow")
	ErrUnexpectedEndOfGroupTypes = fmt.Errorf("proto: unexpected end of group")
)
